// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/account.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	model "github.com/zoobc/zoobc-core/common/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("service/account.proto", fileDescriptor_babdd3f8328330ae) }

var fileDescriptor_babdd3f8328330ae = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x87, 0x0a, 0x4b, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16,
	0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x94, 0x49,
	0x09, 0xe7, 0xe6, 0xa7, 0xa4, 0xe6, 0xa0, 0xea, 0x35, 0x3a, 0xcf, 0xc8, 0xc5, 0xe7, 0x08, 0x11,
	0x09, 0x86, 0x98, 0x22, 0x94, 0xca, 0xc5, 0xed, 0x9e, 0x5a, 0x02, 0x15, 0x2c, 0x16, 0x92, 0xd4,
	0x03, 0xeb, 0xd3, 0x43, 0x12, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x91, 0x92, 0xc2, 0x26,
	0x55, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0xaa, 0x24, 0xdf, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x49, 0x21,
	0x71, 0xfd, 0x32, 0x43, 0x98, 0x9d, 0xfa, 0xc8, 0xe6, 0x86, 0x71, 0x71, 0x21, 0xb8, 0x42, 0x12,
	0x18, 0x46, 0xc1, 0x2c, 0xe1, 0x83, 0xca, 0x40, 0x85, 0x95, 0xe4, 0xc0, 0x06, 0x4b, 0x08, 0x89,
	0x61, 0x37, 0xd8, 0x49, 0x27, 0x4a, 0x2b, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f,
	0x57, 0xbf, 0x2a, 0x3f, 0x3f, 0x29, 0x19, 0x42, 0xea, 0x26, 0xe7, 0x17, 0xa5, 0xea, 0x27, 0xe7,
	0xe7, 0xe6, 0xe6, 0xe7, 0xe9, 0x43, 0x83, 0x2c, 0x89, 0x0d, 0x1c, 0x0c, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x69, 0x9e, 0xfd, 0x23, 0x5b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	GetAccounts(ctx context.Context, in *model.GetAccountsRequest, opts ...grpc.CallOption) (*model.GetAccountsResponse, error)
	GetAccount(ctx context.Context, in *model.GetAccountRequest, opts ...grpc.CallOption) (*model.Account, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAccounts(ctx context.Context, in *model.GetAccountsRequest, opts ...grpc.CallOption) (*model.GetAccountsResponse, error) {
	out := new(model.GetAccountsResponse)
	err := c.cc.Invoke(ctx, "/service.AccountService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *model.GetAccountRequest, opts ...grpc.CallOption) (*model.Account, error) {
	out := new(model.Account)
	err := c.cc.Invoke(ctx, "/service.AccountService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	GetAccounts(context.Context, *model.GetAccountsRequest) (*model.GetAccountsResponse, error)
	GetAccount(context.Context, *model.GetAccountRequest) (*model.Account, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) GetAccounts(ctx context.Context, req *model.GetAccountsRequest) (*model.GetAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (*UnimplementedAccountServiceServer) GetAccount(ctx context.Context, req *model.GetAccountRequest) (*model.Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AccountService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccounts(ctx, req.(*model.GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AccountService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*model.GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccounts",
			Handler:    _AccountService_GetAccounts_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/account.proto",
}
