// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/p2pCommunication.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	model "github.com/zoobc/zoobc-core/common/model"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("service/p2pCommunication.proto", fileDescriptor_5d547fbc25d9babc) }

var fileDescriptor_5d547fbc25d9babc = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0x73, 0x51, 0x71, 0x5a, 0x6d, 0x3b, 0x82, 0xc1, 0x2d, 0xf5, 0x10, 0x50, 0xac, 0x68,
	0x16, 0xa2, 0xe0, 0xc1, 0x93, 0x69, 0x64, 0x29, 0xd2, 0x12, 0xa2, 0x27, 0x6f, 0xbb, 0xb3, 0x2f,
	0x76, 0x74, 0x67, 0xde, 0x3a, 0xf3, 0xb6, 0x58, 0xff, 0x18, 0xff, 0x56, 0xd9, 0x9d, 0xd9, 0xd9,
	0x59, 0x0c, 0xd8, 0x4b, 0x20, 0xbf, 0xef, 0x7b, 0xdf, 0x37, 0xef, 0x91, 0xb0, 0xa7, 0x16, 0xcc,
	0xb5, 0x14, 0x90, 0xd6, 0x8b, 0xfa, 0x0c, 0x95, 0x6a, 0xb4, 0x14, 0x39, 0x49, 0xd4, 0xf3, 0xda,
	0x20, 0x21, 0xbf, 0xe7, 0xf5, 0xe4, 0x50, 0x61, 0x09, 0x55, 0x5a, 0x03, 0x18, 0x27, 0xf5, 0x44,
	0x63, 0x09, 0x9e, 0x1c, 0x39, 0x02, 0xaa, 0xa6, 0x9b, 0x31, 0x2a, 0x2a, 0x14, 0x3f, 0x3c, 0x7a,
	0x1c, 0x21, 0x71, 0x95, 0x4b, 0x5f, 0x95, 0x4c, 0x1d, 0x27, 0x93, 0x6b, 0x9b, 0x8b, 0xe1, 0x0d,
	0xc9, 0x23, 0x27, 0x18, 0x10, 0x20, 0x6b, 0x72, 0x70, 0xf1, 0xe7, 0x0e, 0x3b, 0x5c, 0x2f, 0xd6,
	0xa3, 0x37, 0xf3, 0x77, 0x6c, 0x2f, 0x03, 0x5a, 0x03, 0x98, 0x73, 0xbd, 0x45, 0xfe, 0x64, 0xde,
	0x4d, 0xce, 0x23, 0xb6, 0x81, 0x9f, 0x0d, 0x58, 0x4a, 0xf6, 0xbc, 0x74, 0x89, 0x25, 0xcc, 0x26,
	0xfc, 0x3d, 0xdb, 0xcf, 0x80, 0x2e, 0xd0, 0x40, 0x6b, 0xb4, 0x7c, 0xdf, 0xcb, 0x1f, 0xdb, 0x55,
	0x92, 0xe3, 0x21, 0x27, 0x58, 0x36, 0x60, 0x6b, 0xd4, 0xb6, 0x1d, 0x7e, 0xcb, 0xee, 0x7f, 0x06,
	0x5d, 0xba, 0xc9, 0xa9, 0xf7, 0x06, 0xd2, 0x37, 0x8e, 0x22, 0x67, 0x13, 0x7e, 0xea, 0xa6, 0x96,
	0xed, 0x19, 0x42, 0x5f, 0xf7, 0xed, 0x1f, 0xeb, 0x92, 0x1d, 0xb4, 0xd6, 0x2f, 0xc3, 0x65, 0xf8,
	0x49, 0x54, 0x13, 0xf1, 0xbe, 0xec, 0xa1, 0x97, 0x37, 0xee, 0x66, 0xb3, 0x09, 0xff, 0xce, 0xa6,
	0x19, 0xd0, 0x59, 0xa3, 0x9a, 0x2a, 0x27, 0x79, 0x0d, 0x2b, 0xb9, 0xdd, 0x4a, 0xd1, 0x54, 0x74,
	0xc3, 0x9f, 0x0d, 0xeb, 0xed, 0xd2, 0xfb, 0xcc, 0xe7, 0xff, 0xb3, 0x85, 0x83, 0x58, 0x96, 0xb4,
	0x26, 0x54, 0x0a, 0xf5, 0x85, 0xac, 0xc0, 0x12, 0x6a, 0xe8, 0x56, 0x3b, 0x5f, 0x59, 0xfe, 0x22,
	0xca, 0xd9, 0x65, 0x29, 0xc3, 0xc9, 0x4e, 0x6f, 0xe1, 0x0c, 0xa5, 0x9f, 0xd8, 0x41, 0x06, 0x74,
	0x09, 0xbf, 0x28, 0x34, 0x9d, 0x0c, 0xf3, 0x03, 0x1f, 0xe2, 0xa7, 0xf1, 0xd1, 0xc7, 0x61, 0x1f,
	0xd8, 0x83, 0x78, 0xc8, 0xf2, 0xe3, 0x1d, 0x51, 0x21, 0xe8, 0x28, 0x0e, 0xb2, 0xab, 0x9c, 0xf2,
	0xd9, 0x64, 0xf9, 0xea, 0xeb, 0xcb, 0x6f, 0x92, 0xae, 0x9a, 0x62, 0x2e, 0x50, 0xa5, 0xbf, 0x11,
	0x0b, 0xe1, 0x3e, 0x5f, 0x0b, 0x34, 0x90, 0x8a, 0x6e, 0xa1, 0xd4, 0xff, 0xbd, 0x8a, 0xbb, 0xdd,
	0xaf, 0xfa, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0x4e, 0xee, 0x14, 0x90, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// P2PCommunicationClient is the client API for P2PCommunication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type P2PCommunicationClient interface {
	GetPeerInfo(ctx context.Context, in *model.GetPeerInfoRequest, opts ...grpc.CallOption) (*model.Node, error)
	GetMorePeers(ctx context.Context, in *model.Empty, opts ...grpc.CallOption) (*model.GetMorePeersResponse, error)
	SendPeers(ctx context.Context, in *model.SendPeersRequest, opts ...grpc.CallOption) (*model.Empty, error)
	SendBlock(ctx context.Context, in *model.Block, opts ...grpc.CallOption) (*model.Empty, error)
	SendTransaction(ctx context.Context, in *model.SendTransactionRequest, opts ...grpc.CallOption) (*model.Receipt, error)
	GetCumulativeDifficulty(ctx context.Context, in *model.GetCumulativeDifficultyRequest, opts ...grpc.CallOption) (*model.GetCumulativeDifficultyResponse, error)
	GetCommonMilestoneBlockIDs(ctx context.Context, in *model.GetCommonMilestoneBlockIdsRequest, opts ...grpc.CallOption) (*model.GetCommonMilestoneBlockIdsResponse, error)
	GetNextBlockIDs(ctx context.Context, in *model.GetNextBlockIdsRequest, opts ...grpc.CallOption) (*model.BlockIdsResponse, error)
	GetNextBlocks(ctx context.Context, in *model.GetNextBlocksRequest, opts ...grpc.CallOption) (*model.BlocksData, error)
}

type p2PCommunicationClient struct {
	cc *grpc.ClientConn
}

func NewP2PCommunicationClient(cc *grpc.ClientConn) P2PCommunicationClient {
	return &p2PCommunicationClient{cc}
}

func (c *p2PCommunicationClient) GetPeerInfo(ctx context.Context, in *model.GetPeerInfoRequest, opts ...grpc.CallOption) (*model.Node, error) {
	out := new(model.Node)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/GetPeerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) GetMorePeers(ctx context.Context, in *model.Empty, opts ...grpc.CallOption) (*model.GetMorePeersResponse, error) {
	out := new(model.GetMorePeersResponse)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/GetMorePeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) SendPeers(ctx context.Context, in *model.SendPeersRequest, opts ...grpc.CallOption) (*model.Empty, error) {
	out := new(model.Empty)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/SendPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) SendBlock(ctx context.Context, in *model.Block, opts ...grpc.CallOption) (*model.Empty, error) {
	out := new(model.Empty)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/SendBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) SendTransaction(ctx context.Context, in *model.SendTransactionRequest, opts ...grpc.CallOption) (*model.Receipt, error) {
	out := new(model.Receipt)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) GetCumulativeDifficulty(ctx context.Context, in *model.GetCumulativeDifficultyRequest, opts ...grpc.CallOption) (*model.GetCumulativeDifficultyResponse, error) {
	out := new(model.GetCumulativeDifficultyResponse)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/GetCumulativeDifficulty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) GetCommonMilestoneBlockIDs(ctx context.Context, in *model.GetCommonMilestoneBlockIdsRequest, opts ...grpc.CallOption) (*model.GetCommonMilestoneBlockIdsResponse, error) {
	out := new(model.GetCommonMilestoneBlockIdsResponse)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/GetCommonMilestoneBlockIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) GetNextBlockIDs(ctx context.Context, in *model.GetNextBlockIdsRequest, opts ...grpc.CallOption) (*model.BlockIdsResponse, error) {
	out := new(model.BlockIdsResponse)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/GetNextBlockIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PCommunicationClient) GetNextBlocks(ctx context.Context, in *model.GetNextBlocksRequest, opts ...grpc.CallOption) (*model.BlocksData, error) {
	out := new(model.BlocksData)
	err := c.cc.Invoke(ctx, "/service.P2PCommunication/GetNextBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// P2PCommunicationServer is the server API for P2PCommunication service.
type P2PCommunicationServer interface {
	GetPeerInfo(context.Context, *model.GetPeerInfoRequest) (*model.Node, error)
	GetMorePeers(context.Context, *model.Empty) (*model.GetMorePeersResponse, error)
	SendPeers(context.Context, *model.SendPeersRequest) (*model.Empty, error)
	SendBlock(context.Context, *model.Block) (*model.Empty, error)
	SendTransaction(context.Context, *model.SendTransactionRequest) (*model.Receipt, error)
	GetCumulativeDifficulty(context.Context, *model.GetCumulativeDifficultyRequest) (*model.GetCumulativeDifficultyResponse, error)
	GetCommonMilestoneBlockIDs(context.Context, *model.GetCommonMilestoneBlockIdsRequest) (*model.GetCommonMilestoneBlockIdsResponse, error)
	GetNextBlockIDs(context.Context, *model.GetNextBlockIdsRequest) (*model.BlockIdsResponse, error)
	GetNextBlocks(context.Context, *model.GetNextBlocksRequest) (*model.BlocksData, error)
}

func RegisterP2PCommunicationServer(s *grpc.Server, srv P2PCommunicationServer) {
	s.RegisterService(&_P2PCommunication_serviceDesc, srv)
}

func _P2PCommunication_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GetPeerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/GetPeerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).GetPeerInfo(ctx, req.(*model.GetPeerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_GetMorePeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).GetMorePeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/GetMorePeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).GetMorePeers(ctx, req.(*model.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_SendPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.SendPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).SendPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/SendPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).SendPeers(ctx, req.(*model.SendPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_SendBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).SendBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/SendBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).SendBlock(ctx, req.(*model.Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).SendTransaction(ctx, req.(*model.SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_GetCumulativeDifficulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GetCumulativeDifficultyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).GetCumulativeDifficulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/GetCumulativeDifficulty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).GetCumulativeDifficulty(ctx, req.(*model.GetCumulativeDifficultyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_GetCommonMilestoneBlockIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GetCommonMilestoneBlockIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).GetCommonMilestoneBlockIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/GetCommonMilestoneBlockIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).GetCommonMilestoneBlockIDs(ctx, req.(*model.GetCommonMilestoneBlockIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_GetNextBlockIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GetNextBlockIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).GetNextBlockIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/GetNextBlockIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).GetNextBlockIDs(ctx, req.(*model.GetNextBlockIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PCommunication_GetNextBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GetNextBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCommunicationServer).GetNextBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.P2PCommunication/GetNextBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCommunicationServer).GetNextBlocks(ctx, req.(*model.GetNextBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _P2PCommunication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.P2PCommunication",
	HandlerType: (*P2PCommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeerInfo",
			Handler:    _P2PCommunication_GetPeerInfo_Handler,
		},
		{
			MethodName: "GetMorePeers",
			Handler:    _P2PCommunication_GetMorePeers_Handler,
		},
		{
			MethodName: "SendPeers",
			Handler:    _P2PCommunication_SendPeers_Handler,
		},
		{
			MethodName: "SendBlock",
			Handler:    _P2PCommunication_SendBlock_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _P2PCommunication_SendTransaction_Handler,
		},
		{
			MethodName: "GetCumulativeDifficulty",
			Handler:    _P2PCommunication_GetCumulativeDifficulty_Handler,
		},
		{
			MethodName: "GetCommonMilestoneBlockIDs",
			Handler:    _P2PCommunication_GetCommonMilestoneBlockIDs_Handler,
		},
		{
			MethodName: "GetNextBlockIDs",
			Handler:    _P2PCommunication_GetNextBlockIDs_Handler,
		},
		{
			MethodName: "GetNextBlocks",
			Handler:    _P2PCommunication_GetNextBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/p2pCommunication.proto",
}
