// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/healthCheck.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HealthCheckResponse represent the response body of health check request
type HealthCheckResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45c88e150f25dc67, []int{0}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

// HealthCheckResponse represent the response body of health check request
type GetNodeStatusResponse struct {
	LastBlockHeight      uint32   `protobuf:"varint,1,opt,name=LastBlockHeight,proto3" json:"LastBlockHeight,omitempty"`
	LastBlockHash        string   `protobuf:"bytes,2,opt,name=LastBlockHash,proto3" json:"LastBlockHash,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	NodePublicKey        string   `protobuf:"bytes,4,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	UnresolvedPeers      uint32   `protobuf:"varint,5,opt,name=UnresolvedPeers,proto3" json:"UnresolvedPeers,omitempty"`
	ResolvedPeers        uint64   `protobuf:"varint,6,opt,name=ResolvedPeers,proto3" json:"ResolvedPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeStatusResponse) Reset()         { *m = GetNodeStatusResponse{} }
func (m *GetNodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeStatusResponse) ProtoMessage()    {}
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45c88e150f25dc67, []int{1}
}

func (m *GetNodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStatusResponse.Unmarshal(m, b)
}
func (m *GetNodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStatusResponse.Merge(m, src)
}
func (m *GetNodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeStatusResponse.Size(m)
}
func (m *GetNodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStatusResponse proto.InternalMessageInfo

func (m *GetNodeStatusResponse) GetLastBlockHeight() uint32 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *GetNodeStatusResponse) GetLastBlockHash() string {
	if m != nil {
		return m.LastBlockHash
	}
	return ""
}

func (m *GetNodeStatusResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetNodeStatusResponse) GetNodePublicKey() string {
	if m != nil {
		return m.NodePublicKey
	}
	return ""
}

func (m *GetNodeStatusResponse) GetUnresolvedPeers() uint32 {
	if m != nil {
		return m.UnresolvedPeers
	}
	return 0
}

func (m *GetNodeStatusResponse) GetResolvedPeers() uint64 {
	if m != nil {
		return m.ResolvedPeers
	}
	return 0
}

func init() {
	proto.RegisterType((*HealthCheckResponse)(nil), "model.HealthCheckResponse")
	proto.RegisterType((*GetNodeStatusResponse)(nil), "model.GetNodeStatusResponse")
}

func init() {
	proto.RegisterFile("model/healthCheck.proto", fileDescriptor_45c88e150f25dc67)
}

var fileDescriptor_45c88e150f25dc67 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0xa9, 0xae, 0x13, 0x03, 0x43, 0xa8, 0x8a, 0x39, 0x8e, 0xe1, 0xa1, 0x28, 0xae, 0x07,
	0xff, 0x83, 0x79, 0x70, 0xa0, 0xc8, 0x88, 0xe8, 0xc1, 0x5b, 0x9b, 0x3e, 0x96, 0xb2, 0xb4, 0x5f,
	0x49, 0x52, 0x61, 0xfe, 0xe3, 0x5e, 0xa5, 0x29, 0x6e, 0xa4, 0x97, 0xc0, 0xf7, 0x7b, 0xdf, 0xcb,
	0xf7, 0x78, 0xec, 0xa6, 0xa6, 0x12, 0x3a, 0x53, 0xc8, 0xb5, 0x53, 0x4f, 0x0a, 0x72, 0xb7, 0x6c,
	0x0d, 0x39, 0x4a, 0x62, 0x2f, 0x2c, 0xee, 0xd9, 0xe5, 0xfa, 0xa8, 0x09, 0xd8, 0x96, 0x1a, 0x8b,
	0xe4, 0x8a, 0xc5, 0x02, 0xad, 0xde, 0xf3, 0x68, 0x1e, 0xa5, 0xe7, 0x62, 0x18, 0x16, 0xbf, 0x11,
	0xbb, 0x7e, 0x86, 0x7b, 0xa3, 0x12, 0xef, 0x2e, 0x77, 0x9d, 0x3d, 0xec, 0xa7, 0xec, 0xe2, 0x35,
	0xb7, 0x6e, 0xa5, 0x49, 0xee, 0xd6, 0xa8, 0xb6, 0xca, 0x79, 0xe7, 0x4c, 0x8c, 0x71, 0x72, 0xcb,
	0x66, 0x47, 0x94, 0x5b, 0xc5, 0x4f, 0xfc, 0x85, 0x10, 0x26, 0x9c, 0x9d, 0x7d, 0xc2, 0xd8, 0x8a,
	0x1a, 0x7e, 0xea, 0xf5, 0xff, 0xb1, 0xf7, 0xf7, 0xf7, 0x37, 0x5d, 0xa1, 0x2b, 0xf9, 0x82, 0x3d,
	0x9f, 0x0c, 0xfe, 0x00, 0xf6, 0x79, 0x3e, 0x1a, 0x03, 0x4b, 0xfa, 0x1b, 0xe5, 0x06, 0x30, 0x96,
	0xc7, 0x43, 0x9e, 0x11, 0xee, 0xff, 0x13, 0xc1, 0xde, 0x74, 0x1e, 0xa5, 0x13, 0x11, 0xc2, 0xd5,
	0xdd, 0x57, 0xba, 0xad, 0x9c, 0xea, 0x8a, 0xa5, 0xa4, 0x3a, 0xfb, 0x21, 0x2a, 0xe4, 0xf0, 0x3e,
	0x48, 0x32, 0xc8, 0x24, 0xd5, 0x35, 0x35, 0x99, 0xaf, 0xb4, 0x98, 0xfa, 0x82, 0x1f, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x80, 0xc6, 0x02, 0xdb, 0x7b, 0x01, 0x00, 0x00,
}
