// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/host.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Host represent data sructure node and listed peers in node it's self
type Host struct {
	Info                 *Node            `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	ResolvedPeers        map[string]*Peer `protobuf:"bytes,2,rep,name=ResolvedPeers,proto3" json:"ResolvedPeers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UnresolvedPeers      map[string]*Peer `protobuf:"bytes,3,rep,name=UnresolvedPeers,proto3" json:"UnresolvedPeers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	KnownPeers           map[string]*Peer `protobuf:"bytes,4,rep,name=KnownPeers,proto3" json:"KnownPeers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BlacklistedPeers     map[string]*Peer `protobuf:"bytes,5,rep,name=BlacklistedPeers,proto3" json:"BlacklistedPeers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Stopped              bool             `protobuf:"varint,6,opt,name=Stopped,proto3" json:"Stopped,omitempty"`
	PriorityPeers        []*Peer          `protobuf:"bytes,7,rep,name=PriorityPeers,proto3" json:"PriorityPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_2105bc76e5d5e738, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetInfo() *Node {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Host) GetResolvedPeers() map[string]*Peer {
	if m != nil {
		return m.ResolvedPeers
	}
	return nil
}

func (m *Host) GetUnresolvedPeers() map[string]*Peer {
	if m != nil {
		return m.UnresolvedPeers
	}
	return nil
}

func (m *Host) GetKnownPeers() map[string]*Peer {
	if m != nil {
		return m.KnownPeers
	}
	return nil
}

func (m *Host) GetBlacklistedPeers() map[string]*Peer {
	if m != nil {
		return m.BlacklistedPeers
	}
	return nil
}

func (m *Host) GetStopped() bool {
	if m != nil {
		return m.Stopped
	}
	return false
}

func (m *Host) GetPriorityPeers() []*Peer {
	if m != nil {
		return m.PriorityPeers
	}
	return nil
}

type HostInfo struct {
	Host                 *Host          `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	ChainStatuses        []*ChainStatus `protobuf:"bytes,2,rep,name=ChainStatuses,proto3" json:"ChainStatuses,omitempty"`
	ScrambledNodes       []*Peer        `protobuf:"bytes,3,rep,name=ScrambledNodes,proto3" json:"ScrambledNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HostInfo) Reset()         { *m = HostInfo{} }
func (m *HostInfo) String() string { return proto.CompactTextString(m) }
func (*HostInfo) ProtoMessage()    {}
func (*HostInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2105bc76e5d5e738, []int{1}
}

func (m *HostInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfo.Unmarshal(m, b)
}
func (m *HostInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfo.Marshal(b, m, deterministic)
}
func (m *HostInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfo.Merge(m, src)
}
func (m *HostInfo) XXX_Size() int {
	return xxx_messageInfo_HostInfo.Size(m)
}
func (m *HostInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfo proto.InternalMessageInfo

func (m *HostInfo) GetHost() *Host {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *HostInfo) GetChainStatuses() []*ChainStatus {
	if m != nil {
		return m.ChainStatuses
	}
	return nil
}

func (m *HostInfo) GetScrambledNodes() []*Peer {
	if m != nil {
		return m.ScrambledNodes
	}
	return nil
}

type GetHostPeersResponse struct {
	ResolvedPeers        map[string]*Peer `protobuf:"bytes,1,rep,name=ResolvedPeers,proto3" json:"ResolvedPeers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UnresolvedPeers      map[string]*Peer `protobuf:"bytes,2,rep,name=UnresolvedPeers,proto3" json:"UnresolvedPeers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetHostPeersResponse) Reset()         { *m = GetHostPeersResponse{} }
func (m *GetHostPeersResponse) String() string { return proto.CompactTextString(m) }
func (*GetHostPeersResponse) ProtoMessage()    {}
func (*GetHostPeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2105bc76e5d5e738, []int{2}
}

func (m *GetHostPeersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostPeersResponse.Unmarshal(m, b)
}
func (m *GetHostPeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostPeersResponse.Marshal(b, m, deterministic)
}
func (m *GetHostPeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostPeersResponse.Merge(m, src)
}
func (m *GetHostPeersResponse) XXX_Size() int {
	return xxx_messageInfo_GetHostPeersResponse.Size(m)
}
func (m *GetHostPeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostPeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostPeersResponse proto.InternalMessageInfo

func (m *GetHostPeersResponse) GetResolvedPeers() map[string]*Peer {
	if m != nil {
		return m.ResolvedPeers
	}
	return nil
}

func (m *GetHostPeersResponse) GetUnresolvedPeers() map[string]*Peer {
	if m != nil {
		return m.UnresolvedPeers
	}
	return nil
}

func init() {
	proto.RegisterType((*Host)(nil), "model.Host")
	proto.RegisterMapType((map[string]*Peer)(nil), "model.Host.BlacklistedPeersEntry")
	proto.RegisterMapType((map[string]*Peer)(nil), "model.Host.KnownPeersEntry")
	proto.RegisterMapType((map[string]*Peer)(nil), "model.Host.ResolvedPeersEntry")
	proto.RegisterMapType((map[string]*Peer)(nil), "model.Host.UnresolvedPeersEntry")
	proto.RegisterType((*HostInfo)(nil), "model.HostInfo")
	proto.RegisterType((*GetHostPeersResponse)(nil), "model.GetHostPeersResponse")
	proto.RegisterMapType((map[string]*Peer)(nil), "model.GetHostPeersResponse.ResolvedPeersEntry")
	proto.RegisterMapType((map[string]*Peer)(nil), "model.GetHostPeersResponse.UnresolvedPeersEntry")
}

func init() { proto.RegisterFile("model/host.proto", fileDescriptor_2105bc76e5d5e738) }

var fileDescriptor_2105bc76e5d5e738 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0x7c, 0xb4, 0x65, 0xa2, 0xd0, 0x68, 0x55, 0x90, 0x15, 0x24, 0x9a, 0xe6, 0x14,
	0x21, 0xe1, 0x40, 0x7b, 0xa9, 0xe0, 0x56, 0x40, 0x40, 0x51, 0x21, 0xda, 0xc0, 0xa5, 0x37, 0x7f,
	0x0c, 0xc4, 0x8a, 0xbd, 0x63, 0xad, 0x37, 0x45, 0xe1, 0x51, 0x78, 0x2a, 0x1e, 0x83, 0xc7, 0x40,
	0xbb, 0x6b, 0x0b, 0xdb, 0x89, 0x50, 0x94, 0x13, 0x17, 0xcb, 0x9e, 0xf9, 0xcf, 0x6f, 0x77, 0x67,
	0xff, 0x63, 0x18, 0xa4, 0x14, 0x61, 0x32, 0x5d, 0x50, 0xae, 0xbc, 0x4c, 0x92, 0x22, 0xd6, 0x35,
	0x91, 0x61, 0x91, 0x10, 0x14, 0xa1, 0x4d, 0x94, 0x91, 0x0c, 0x51, 0x16, 0x91, 0x87, 0x36, 0x12,
	0x24, 0x14, 0x2e, 0xc3, 0x85, 0x1f, 0x0b, 0x1b, 0x1f, 0xff, 0xea, 0x42, 0xe7, 0x1d, 0xe5, 0x8a,
	0x9d, 0x42, 0xe7, 0xbd, 0xf8, 0x4a, 0xae, 0x33, 0x72, 0x26, 0xbd, 0xf3, 0x9e, 0x67, 0xf4, 0xde,
	0x47, 0x8a, 0x90, 0x9b, 0x04, 0x7b, 0x0d, 0x7d, 0x8e, 0x39, 0x25, 0x77, 0x18, 0xcd, 0x10, 0x65,
	0xee, 0xb6, 0x46, 0xed, 0x49, 0xef, 0xfc, 0x71, 0xa1, 0xd4, 0x10, 0xaf, 0x26, 0x78, 0x23, 0x94,
	0x5c, 0xf3, 0x7a, 0x11, 0xbb, 0x86, 0xe3, 0x2f, 0x42, 0xd6, 0x38, 0x6d, 0xc3, 0x19, 0x55, 0x39,
	0x0d, 0x89, 0x25, 0x35, 0x0b, 0xd9, 0x4b, 0x80, 0x0f, 0x82, 0xbe, 0x0b, 0x8b, 0xe9, 0x18, 0xcc,
	0xa3, 0x2a, 0xe6, 0x6f, 0xd6, 0x12, 0x2a, 0x72, 0x76, 0x03, 0x83, 0xab, 0xc4, 0x0f, 0x97, 0x49,
	0x9c, 0xab, 0x72, 0x27, 0x5d, 0x83, 0x38, 0xab, 0x22, 0x9a, 0x1a, 0x0b, 0xda, 0x28, 0x65, 0x2e,
	0x1c, 0xce, 0x15, 0x65, 0x19, 0x46, 0xee, 0xc1, 0xc8, 0x99, 0x1c, 0xf1, 0xf2, 0x93, 0x3d, 0x87,
	0xfe, 0x4c, 0xc6, 0x24, 0x63, 0xb5, 0xb6, 0xab, 0x1c, 0x9a, 0x55, 0xca, 0x0e, 0xeb, 0x18, 0xaf,
	0x2b, 0x86, 0x37, 0xc0, 0x36, 0x3b, 0xc9, 0x06, 0xd0, 0x5e, 0xe2, 0xda, 0x5c, 0xd0, 0x3d, 0xae,
	0x5f, 0xd9, 0x19, 0x74, 0xef, 0xfc, 0x64, 0x85, 0x6e, 0xab, 0x76, 0x69, 0x06, 0x69, 0x33, 0x2f,
	0x5a, 0x97, 0xce, 0xf0, 0x13, 0x9c, 0x6c, 0x6b, 0xe8, 0xfe, 0xc0, 0x6b, 0x38, 0x6e, 0xb4, 0x76,
	0x7f, 0xd6, 0x0c, 0x1e, 0x6c, 0xed, 0xf1, 0xde, 0xc4, 0xf1, 0x4f, 0x07, 0x8e, 0xf4, 0xdd, 0x19,
	0xd7, 0x9e, 0x5a, 0x7b, 0x37, 0x6c, 0xad, 0x43, 0xdc, 0xfa, 0xfe, 0x12, 0xfa, 0xaf, 0xf4, 0x3c,
	0xcc, 0x95, 0xaf, 0x56, 0x39, 0x96, 0xb6, 0x66, 0x85, 0xb2, 0x92, 0xe3, 0x75, 0x21, 0xbb, 0x80,
	0xfb, 0xf3, 0x50, 0xfa, 0x69, 0x90, 0x60, 0xa4, 0xe7, 0xa4, 0x74, 0x72, 0x6d, 0x5f, 0x0d, 0xc9,
	0xf8, 0x77, 0x0b, 0x4e, 0xde, 0xa2, 0xd2, 0x4b, 0x9b, 0xb3, 0x72, 0xcc, 0x33, 0x12, 0x39, 0xb2,
	0xcf, 0xcd, 0xf1, 0x72, 0x0c, 0xcc, 0x2b, 0x60, 0xdb, 0x6a, 0x76, 0x18, 0xb7, 0xdb, 0xcd, 0x71,
	0xb3, 0xe7, 0x7b, 0xf6, 0x2f, 0xee, 0x4e, 0xe3, 0xf7, 0xbf, 0xbb, 0xf4, 0xea, 0xc9, 0xed, 0xe4,
	0x5b, 0xac, 0x16, 0xab, 0xc0, 0x0b, 0x29, 0x9d, 0xfe, 0x20, 0x0a, 0x42, 0xfb, 0x7c, 0x1a, 0x92,
	0xc4, 0x69, 0x48, 0x69, 0x4a, 0x62, 0x6a, 0x6a, 0x83, 0x03, 0xf3, 0x37, 0xbc, 0xf8, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xd0, 0xc5, 0x9a, 0x89, 0x64, 0x05, 0x00, 0x00,
}
