// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/multiSignature.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PendingTransactionStatus int32

const (
	PendingTransactionStatus_PendingTransactionPending  PendingTransactionStatus = 0
	PendingTransactionStatus_PendingTransactionExecuted PendingTransactionStatus = 1
	PendingTransactionStatus_PendingTransactionNoOp     PendingTransactionStatus = 2
	PendingTransactionStatus_PendingTransactionExpired  PendingTransactionStatus = 3
)

var PendingTransactionStatus_name = map[int32]string{
	0: "PendingTransactionPending",
	1: "PendingTransactionExecuted",
	2: "PendingTransactionNoOp",
	3: "PendingTransactionExpired",
}

var PendingTransactionStatus_value = map[string]int32{
	"PendingTransactionPending":  0,
	"PendingTransactionExecuted": 1,
	"PendingTransactionNoOp":     2,
	"PendingTransactionExpired":  3,
}

func (x PendingTransactionStatus) String() string {
	return proto.EnumName(PendingTransactionStatus_name, int32(x))
}

func (PendingTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{0}
}

type MultiSignatureInfo struct {
	MinimumSignatures    uint32   `protobuf:"varint,1,opt,name=MinimumSignatures,proto3" json:"MinimumSignatures,omitempty"`
	Nonce                int64    `protobuf:"varint,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Addresses            []string `protobuf:"bytes,3,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
	MultisigAddress      string   `protobuf:"bytes,4,opt,name=MultisigAddress,proto3" json:"MultisigAddress,omitempty"`
	BlockHeight          uint32   `protobuf:"varint,5,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Latest               bool     `protobuf:"varint,6,opt,name=Latest,proto3" json:"Latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiSignatureInfo) Reset()         { *m = MultiSignatureInfo{} }
func (m *MultiSignatureInfo) String() string { return proto.CompactTextString(m) }
func (*MultiSignatureInfo) ProtoMessage()    {}
func (*MultiSignatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{0}
}

func (m *MultiSignatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSignatureInfo.Unmarshal(m, b)
}
func (m *MultiSignatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSignatureInfo.Marshal(b, m, deterministic)
}
func (m *MultiSignatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSignatureInfo.Merge(m, src)
}
func (m *MultiSignatureInfo) XXX_Size() int {
	return xxx_messageInfo_MultiSignatureInfo.Size(m)
}
func (m *MultiSignatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSignatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSignatureInfo proto.InternalMessageInfo

func (m *MultiSignatureInfo) GetMinimumSignatures() uint32 {
	if m != nil {
		return m.MinimumSignatures
	}
	return 0
}

func (m *MultiSignatureInfo) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MultiSignatureInfo) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *MultiSignatureInfo) GetMultisigAddress() string {
	if m != nil {
		return m.MultisigAddress
	}
	return ""
}

func (m *MultiSignatureInfo) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MultiSignatureInfo) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

// represent the signature posted by account
type SignatureInfo struct {
	TransactionHash      []byte            `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	Signatures           map[string][]byte `protobuf:"bytes,2,rep,name=Signatures,proto3" json:"Signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SignatureInfo) Reset()         { *m = SignatureInfo{} }
func (m *SignatureInfo) String() string { return proto.CompactTextString(m) }
func (*SignatureInfo) ProtoMessage()    {}
func (*SignatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{1}
}

func (m *SignatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureInfo.Unmarshal(m, b)
}
func (m *SignatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureInfo.Marshal(b, m, deterministic)
}
func (m *SignatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureInfo.Merge(m, src)
}
func (m *SignatureInfo) XXX_Size() int {
	return xxx_messageInfo_SignatureInfo.Size(m)
}
func (m *SignatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureInfo proto.InternalMessageInfo

func (m *SignatureInfo) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *SignatureInfo) GetSignatures() map[string][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// represent the pending signature counter stored by node for multi-signature transaction
type PendingSignature struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	AccountAddress       string   `protobuf:"bytes,2,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	BlockHeight          uint32   `protobuf:"varint,4,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Latest               bool     `protobuf:"varint,5,opt,name=Latest,proto3" json:"Latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingSignature) Reset()         { *m = PendingSignature{} }
func (m *PendingSignature) String() string { return proto.CompactTextString(m) }
func (*PendingSignature) ProtoMessage()    {}
func (*PendingSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{2}
}

func (m *PendingSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingSignature.Unmarshal(m, b)
}
func (m *PendingSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingSignature.Marshal(b, m, deterministic)
}
func (m *PendingSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingSignature.Merge(m, src)
}
func (m *PendingSignature) XXX_Size() int {
	return xxx_messageInfo_PendingSignature.Size(m)
}
func (m *PendingSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingSignature.DiscardUnknown(m)
}

var xxx_messageInfo_PendingSignature proto.InternalMessageInfo

func (m *PendingSignature) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *PendingSignature) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *PendingSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PendingSignature) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PendingSignature) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

// represent transaction inside multisig body
type PendingTransaction struct {
	SenderAddress        string                   `protobuf:"bytes,1,opt,name=SenderAddress,proto3" json:"SenderAddress,omitempty"`
	TransactionHash      []byte                   `protobuf:"bytes,2,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	TransactionBytes     []byte                   `protobuf:"bytes,3,opt,name=TransactionBytes,proto3" json:"TransactionBytes,omitempty"`
	Status               PendingTransactionStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=model.PendingTransactionStatus" json:"Status,omitempty"`
	BlockHeight          uint32                   `protobuf:"varint,5,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Latest               bool                     `protobuf:"varint,6,opt,name=Latest,proto3" json:"Latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PendingTransaction) Reset()         { *m = PendingTransaction{} }
func (m *PendingTransaction) String() string { return proto.CompactTextString(m) }
func (*PendingTransaction) ProtoMessage()    {}
func (*PendingTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{3}
}

func (m *PendingTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingTransaction.Unmarshal(m, b)
}
func (m *PendingTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingTransaction.Marshal(b, m, deterministic)
}
func (m *PendingTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingTransaction.Merge(m, src)
}
func (m *PendingTransaction) XXX_Size() int {
	return xxx_messageInfo_PendingTransaction.Size(m)
}
func (m *PendingTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_PendingTransaction proto.InternalMessageInfo

func (m *PendingTransaction) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *PendingTransaction) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *PendingTransaction) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

func (m *PendingTransaction) GetStatus() PendingTransactionStatus {
	if m != nil {
		return m.Status
	}
	return PendingTransactionStatus_PendingTransactionPending
}

func (m *PendingTransaction) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PendingTransaction) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

func init() {
	proto.RegisterEnum("model.PendingTransactionStatus", PendingTransactionStatus_name, PendingTransactionStatus_value)
	proto.RegisterType((*MultiSignatureInfo)(nil), "model.MultiSignatureInfo")
	proto.RegisterType((*SignatureInfo)(nil), "model.SignatureInfo")
	proto.RegisterMapType((map[string][]byte)(nil), "model.SignatureInfo.SignaturesEntry")
	proto.RegisterType((*PendingSignature)(nil), "model.PendingSignature")
	proto.RegisterType((*PendingTransaction)(nil), "model.PendingTransaction")
}

func init() { proto.RegisterFile("model/multiSignature.proto", fileDescriptor_136af44c597c17ae) }

var fileDescriptor_136af44c597c17ae = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x9d, 0x64, 0x53, 0xec, 0xd9, 0xed, 0x36, 0x0e, 0xb2, 0xc4, 0xe2, 0x9f, 0x50, 0x16,
	0x09, 0x45, 0x5b, 0x59, 0x2f, 0x14, 0xc1, 0x8b, 0x2d, 0x16, 0x56, 0x70, 0x57, 0x99, 0x7a, 0xe5,
	0x5d, 0x3a, 0x19, 0xd3, 0x61, 0x9b, 0x99, 0x92, 0x99, 0xc8, 0xd6, 0x5b, 0x5f, 0xc1, 0xc7, 0x11,
	0x1f, 0xc5, 0x67, 0x91, 0x4e, 0xd2, 0x36, 0x7f, 0xaa, 0xa0, 0x37, 0x21, 0xf3, 0xfb, 0x26, 0x67,
	0xce, 0xf7, 0xcd, 0x21, 0xd0, 0x4b, 0x64, 0xc4, 0x16, 0xa3, 0x24, 0x5b, 0x68, 0x3e, 0xe5, 0xb1,
	0x08, 0x75, 0x96, 0xb2, 0xe1, 0x32, 0x95, 0x5a, 0x62, 0xc7, 0x68, 0xfd, 0x5f, 0x08, 0xf0, 0x65,
	0x45, 0x7f, 0x2b, 0x3e, 0x4b, 0xfc, 0x04, 0xee, 0x5c, 0x72, 0xc1, 0x93, 0x2c, 0xd9, 0x72, 0xe5,
	0x21, 0x1f, 0x05, 0x1d, 0xd2, 0x14, 0xb0, 0x07, 0xce, 0x95, 0x14, 0x94, 0x79, 0x96, 0x8f, 0x02,
	0x7b, 0x6c, 0x3d, 0x43, 0x24, 0x07, 0xf8, 0x3e, 0xb4, 0xcf, 0xa3, 0x28, 0x65, 0x4a, 0x31, 0xe5,
	0xd9, 0xbe, 0x1d, 0xb4, 0xc9, 0x0e, 0xe0, 0x00, 0xba, 0xe6, 0x6c, 0xc5, 0xe3, 0x02, 0x7a, 0x07,
	0x3e, 0x0a, 0xda, 0xa4, 0x8e, 0xb1, 0x0f, 0x87, 0xe3, 0x85, 0xa4, 0xd7, 0x17, 0x8c, 0xc7, 0x73,
	0xed, 0x39, 0xa6, 0x93, 0x32, 0xc2, 0x27, 0xd0, 0x7a, 0x17, 0x6a, 0xa6, 0xb4, 0xd7, 0xf2, 0x51,
	0x70, 0x9b, 0x14, 0xab, 0xfe, 0x4f, 0x04, 0x9d, 0xaa, 0xb7, 0x00, 0xba, 0x1f, 0xd3, 0x50, 0xa8,
	0x90, 0x6a, 0x2e, 0xc5, 0x45, 0xa8, 0xe6, 0xc6, 0xd9, 0x11, 0xa9, 0x63, 0xfc, 0x06, 0xa0, 0x64,
	0xdf, 0xf2, 0xed, 0xe0, 0xf0, 0xec, 0x74, 0x68, 0x82, 0x1b, 0x56, 0x6a, 0xee, 0x56, 0x6a, 0x22,
	0x74, 0xba, 0x22, 0xa5, 0xef, 0x7a, 0xaf, 0xa1, 0x5b, 0x93, 0xb1, 0x0b, 0xf6, 0x35, 0x5b, 0x99,
	0x63, 0xdb, 0x64, 0xfd, 0x8a, 0xef, 0x82, 0xf3, 0x25, 0x5c, 0x64, 0x79, 0x84, 0x47, 0x24, 0x5f,
	0xbc, 0xb2, 0x5e, 0xa2, 0xfe, 0x0f, 0x04, 0xee, 0x07, 0x26, 0x22, 0x2e, 0xe2, 0x6d, 0x99, 0x7f,
	0xf0, 0xf0, 0x18, 0x8e, 0xcf, 0x29, 0x95, 0x99, 0xd0, 0x9b, 0x88, 0x2d, 0x73, 0x6a, 0x8d, 0xae,
	0x6f, 0x6a, 0x5b, 0xde, 0xb3, 0x4d, 0xad, 0x1d, 0xa8, 0xe7, 0x7f, 0xf0, 0xb7, 0xfc, 0x9d, 0x4a,
	0xfe, 0xdf, 0x2c, 0xc0, 0x45, 0xfb, 0xa5, 0xd6, 0xf0, 0x29, 0x74, 0xa6, 0x4c, 0x44, 0x2c, 0xdd,
	0x74, 0x95, 0x67, 0x51, 0x85, 0xfb, 0x6c, 0x5a, 0xfb, 0x6d, 0x0e, 0xc0, 0x2d, 0xa1, 0xf1, 0x4a,
	0x9b, 0x79, 0x5b, 0x6f, 0x6d, 0x70, 0xfc, 0x02, 0x5a, 0x53, 0x1d, 0xea, 0x2c, 0x9f, 0xb6, 0xe3,
	0xb3, 0x47, 0xc5, 0x95, 0x36, 0xdb, 0xcc, 0xb7, 0x91, 0x62, 0xfb, 0xff, 0x4f, 0xe1, 0xe0, 0x3b,
	0x02, 0xef, 0x4f, 0xe5, 0xf1, 0x03, 0xb8, 0xd7, 0xd4, 0x0a, 0xe2, 0xde, 0xc2, 0x0f, 0xa1, 0xd7,
	0x94, 0x27, 0x37, 0x8c, 0x66, 0x9a, 0x45, 0x2e, 0xc2, 0x3d, 0x38, 0x69, 0xea, 0x57, 0xf2, 0xfd,
	0xd2, 0xb5, 0xf6, 0x97, 0x9e, 0xdc, 0x2c, 0x79, 0xca, 0x22, 0xd7, 0x1e, 0x0f, 0x3e, 0x05, 0x31,
	0xd7, 0xf3, 0x6c, 0x36, 0xa4, 0x32, 0x19, 0x7d, 0x95, 0x72, 0x46, 0xf3, 0xe7, 0x53, 0x2a, 0x53,
	0x36, 0xa2, 0x32, 0x49, 0xa4, 0x18, 0x99, 0x74, 0x66, 0x2d, 0xf3, 0xdf, 0x78, 0xfe, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x25, 0x40, 0xb8, 0x4b, 0x55, 0x04, 0x00, 0x00,
}
