// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/multiSignature.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PendingTransactionStatus int32

const (
	PendingTransactionStatus_PendingTransactionPending  PendingTransactionStatus = 0
	PendingTransactionStatus_PendingTransactionExecuted PendingTransactionStatus = 1
	PendingTransactionStatus_PendingTransactionNoOp     PendingTransactionStatus = 2
	PendingTransactionStatus_PendingTransactionExpired  PendingTransactionStatus = 3
)

var PendingTransactionStatus_name = map[int32]string{
	0: "PendingTransactionPending",
	1: "PendingTransactionExecuted",
	2: "PendingTransactionNoOp",
	3: "PendingTransactionExpired",
}

var PendingTransactionStatus_value = map[string]int32{
	"PendingTransactionPending":  0,
	"PendingTransactionExecuted": 1,
	"PendingTransactionNoOp":     2,
	"PendingTransactionExpired":  3,
}

func (x PendingTransactionStatus) String() string {
	return proto.EnumName(PendingTransactionStatus_name, int32(x))
}

func (PendingTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{0}
}

type MultiSignatureInfo struct {
	MinimumSignatures    uint32   `protobuf:"varint,1,opt,name=MinimumSignatures,proto3" json:"MinimumSignatures,omitempty"`
	Nonce                int64    `protobuf:"varint,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Addresses            []string `protobuf:"bytes,3,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
	MultisigAddress      string   `protobuf:"bytes,4,opt,name=MultisigAddress,proto3" json:"MultisigAddress,omitempty"`
	BlockHeight          uint32   `protobuf:"varint,5,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Latest               bool     `protobuf:"varint,6,opt,name=Latest,proto3" json:"Latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiSignatureInfo) Reset()         { *m = MultiSignatureInfo{} }
func (m *MultiSignatureInfo) String() string { return proto.CompactTextString(m) }
func (*MultiSignatureInfo) ProtoMessage()    {}
func (*MultiSignatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{0}
}

func (m *MultiSignatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSignatureInfo.Unmarshal(m, b)
}
func (m *MultiSignatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSignatureInfo.Marshal(b, m, deterministic)
}
func (m *MultiSignatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSignatureInfo.Merge(m, src)
}
func (m *MultiSignatureInfo) XXX_Size() int {
	return xxx_messageInfo_MultiSignatureInfo.Size(m)
}
func (m *MultiSignatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSignatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSignatureInfo proto.InternalMessageInfo

func (m *MultiSignatureInfo) GetMinimumSignatures() uint32 {
	if m != nil {
		return m.MinimumSignatures
	}
	return 0
}

func (m *MultiSignatureInfo) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MultiSignatureInfo) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *MultiSignatureInfo) GetMultisigAddress() string {
	if m != nil {
		return m.MultisigAddress
	}
	return ""
}

func (m *MultiSignatureInfo) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MultiSignatureInfo) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

// represent the signature posted by account
type SignatureInfo struct {
	TransactionHash      []byte            `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	Signatures           map[string][]byte `protobuf:"bytes,2,rep,name=Signatures,proto3" json:"Signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SignatureInfo) Reset()         { *m = SignatureInfo{} }
func (m *SignatureInfo) String() string { return proto.CompactTextString(m) }
func (*SignatureInfo) ProtoMessage()    {}
func (*SignatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{1}
}

func (m *SignatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureInfo.Unmarshal(m, b)
}
func (m *SignatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureInfo.Marshal(b, m, deterministic)
}
func (m *SignatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureInfo.Merge(m, src)
}
func (m *SignatureInfo) XXX_Size() int {
	return xxx_messageInfo_SignatureInfo.Size(m)
}
func (m *SignatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureInfo proto.InternalMessageInfo

func (m *SignatureInfo) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *SignatureInfo) GetSignatures() map[string][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// represent the pending signature counter stored by node for multi-signature transaction
type PendingSignature struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	AccountAddress       string   `protobuf:"bytes,2,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	BlockHeight          uint32   `protobuf:"varint,4,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Latest               bool     `protobuf:"varint,5,opt,name=Latest,proto3" json:"Latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingSignature) Reset()         { *m = PendingSignature{} }
func (m *PendingSignature) String() string { return proto.CompactTextString(m) }
func (*PendingSignature) ProtoMessage()    {}
func (*PendingSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{2}
}

func (m *PendingSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingSignature.Unmarshal(m, b)
}
func (m *PendingSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingSignature.Marshal(b, m, deterministic)
}
func (m *PendingSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingSignature.Merge(m, src)
}
func (m *PendingSignature) XXX_Size() int {
	return xxx_messageInfo_PendingSignature.Size(m)
}
func (m *PendingSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingSignature.DiscardUnknown(m)
}

var xxx_messageInfo_PendingSignature proto.InternalMessageInfo

func (m *PendingSignature) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *PendingSignature) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *PendingSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PendingSignature) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PendingSignature) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

// represent transaction inside multisig body
type PendingTransaction struct {
	SenderAddress        string                   `protobuf:"bytes,1,opt,name=SenderAddress,proto3" json:"SenderAddress,omitempty"`
	TransactionHash      []byte                   `protobuf:"bytes,2,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	TransactionBytes     []byte                   `protobuf:"bytes,3,opt,name=TransactionBytes,proto3" json:"TransactionBytes,omitempty"`
	Status               PendingTransactionStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=model.PendingTransactionStatus" json:"Status,omitempty"`
	BlockHeight          uint32                   `protobuf:"varint,5,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Latest               bool                     `protobuf:"varint,6,opt,name=Latest,proto3" json:"Latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PendingTransaction) Reset()         { *m = PendingTransaction{} }
func (m *PendingTransaction) String() string { return proto.CompactTextString(m) }
func (*PendingTransaction) ProtoMessage()    {}
func (*PendingTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{3}
}

func (m *PendingTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingTransaction.Unmarshal(m, b)
}
func (m *PendingTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingTransaction.Marshal(b, m, deterministic)
}
func (m *PendingTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingTransaction.Merge(m, src)
}
func (m *PendingTransaction) XXX_Size() int {
	return xxx_messageInfo_PendingTransaction.Size(m)
}
func (m *PendingTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_PendingTransaction proto.InternalMessageInfo

func (m *PendingTransaction) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *PendingTransaction) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *PendingTransaction) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

func (m *PendingTransaction) GetStatus() PendingTransactionStatus {
	if m != nil {
		return m.Status
	}
	return PendingTransactionStatus_PendingTransactionPending
}

func (m *PendingTransaction) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PendingTransaction) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

type GetPendingTransactionByAddressRequest struct {
	SenderAddress        string                   `protobuf:"bytes,1,opt,name=SenderAddress,proto3" json:"SenderAddress,omitempty"`
	Status               PendingTransactionStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=model.PendingTransactionStatus" json:"Status,omitempty"`
	Pagination           *Pagination              `protobuf:"bytes,3,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetPendingTransactionByAddressRequest) Reset()         { *m = GetPendingTransactionByAddressRequest{} }
func (m *GetPendingTransactionByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetPendingTransactionByAddressRequest) ProtoMessage()    {}
func (*GetPendingTransactionByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{4}
}

func (m *GetPendingTransactionByAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPendingTransactionByAddressRequest.Unmarshal(m, b)
}
func (m *GetPendingTransactionByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPendingTransactionByAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetPendingTransactionByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPendingTransactionByAddressRequest.Merge(m, src)
}
func (m *GetPendingTransactionByAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetPendingTransactionByAddressRequest.Size(m)
}
func (m *GetPendingTransactionByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPendingTransactionByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPendingTransactionByAddressRequest proto.InternalMessageInfo

func (m *GetPendingTransactionByAddressRequest) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *GetPendingTransactionByAddressRequest) GetStatus() PendingTransactionStatus {
	if m != nil {
		return m.Status
	}
	return PendingTransactionStatus_PendingTransactionPending
}

func (m *GetPendingTransactionByAddressRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetPendingTransactionByAddressResponse struct {
	// Number of item in current page
	Count uint32 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	// Starting page
	Page uint32 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	// content of the request
	PendingTransactions  []*PendingTransaction `protobuf:"bytes,3,rep,name=PendingTransactions,proto3" json:"PendingTransactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetPendingTransactionByAddressResponse) Reset() {
	*m = GetPendingTransactionByAddressResponse{}
}
func (m *GetPendingTransactionByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetPendingTransactionByAddressResponse) ProtoMessage()    {}
func (*GetPendingTransactionByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{5}
}

func (m *GetPendingTransactionByAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPendingTransactionByAddressResponse.Unmarshal(m, b)
}
func (m *GetPendingTransactionByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPendingTransactionByAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetPendingTransactionByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPendingTransactionByAddressResponse.Merge(m, src)
}
func (m *GetPendingTransactionByAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetPendingTransactionByAddressResponse.Size(m)
}
func (m *GetPendingTransactionByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPendingTransactionByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPendingTransactionByAddressResponse proto.InternalMessageInfo

func (m *GetPendingTransactionByAddressResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetPendingTransactionByAddressResponse) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetPendingTransactionByAddressResponse) GetPendingTransactions() []*PendingTransaction {
	if m != nil {
		return m.PendingTransactions
	}
	return nil
}

type GetPendingTransactionDetailByTransactionHashRequest struct {
	// hex of transaction hash
	TransactionHashHex   string   `protobuf:"bytes,1,opt,name=TransactionHashHex,proto3" json:"TransactionHashHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPendingTransactionDetailByTransactionHashRequest) Reset() {
	*m = GetPendingTransactionDetailByTransactionHashRequest{}
}
func (m *GetPendingTransactionDetailByTransactionHashRequest) String() string {
	return proto.CompactTextString(m)
}
func (*GetPendingTransactionDetailByTransactionHashRequest) ProtoMessage() {}
func (*GetPendingTransactionDetailByTransactionHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{6}
}

func (m *GetPendingTransactionDetailByTransactionHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPendingTransactionDetailByTransactionHashRequest.Unmarshal(m, b)
}
func (m *GetPendingTransactionDetailByTransactionHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPendingTransactionDetailByTransactionHashRequest.Marshal(b, m, deterministic)
}
func (m *GetPendingTransactionDetailByTransactionHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPendingTransactionDetailByTransactionHashRequest.Merge(m, src)
}
func (m *GetPendingTransactionDetailByTransactionHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetPendingTransactionDetailByTransactionHashRequest.Size(m)
}
func (m *GetPendingTransactionDetailByTransactionHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPendingTransactionDetailByTransactionHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPendingTransactionDetailByTransactionHashRequest proto.InternalMessageInfo

func (m *GetPendingTransactionDetailByTransactionHashRequest) GetTransactionHashHex() string {
	if m != nil {
		return m.TransactionHashHex
	}
	return ""
}

type GetPendingTransactionDetailByTransactionHashResponse struct {
	PendingTransaction   *PendingTransaction `protobuf:"bytes,1,opt,name=PendingTransaction,proto3" json:"PendingTransaction,omitempty"`
	SignatureInfo        *SignatureInfo      `protobuf:"bytes,2,opt,name=SignatureInfo,proto3" json:"SignatureInfo,omitempty"`
	MultiSignatureInfo   *MultiSignatureInfo `protobuf:"bytes,3,opt,name=MultiSignatureInfo,proto3" json:"MultiSignatureInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetPendingTransactionDetailByTransactionHashResponse) Reset() {
	*m = GetPendingTransactionDetailByTransactionHashResponse{}
}
func (m *GetPendingTransactionDetailByTransactionHashResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetPendingTransactionDetailByTransactionHashResponse) ProtoMessage() {}
func (*GetPendingTransactionDetailByTransactionHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_136af44c597c17ae, []int{7}
}

func (m *GetPendingTransactionDetailByTransactionHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPendingTransactionDetailByTransactionHashResponse.Unmarshal(m, b)
}
func (m *GetPendingTransactionDetailByTransactionHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPendingTransactionDetailByTransactionHashResponse.Marshal(b, m, deterministic)
}
func (m *GetPendingTransactionDetailByTransactionHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPendingTransactionDetailByTransactionHashResponse.Merge(m, src)
}
func (m *GetPendingTransactionDetailByTransactionHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetPendingTransactionDetailByTransactionHashResponse.Size(m)
}
func (m *GetPendingTransactionDetailByTransactionHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPendingTransactionDetailByTransactionHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPendingTransactionDetailByTransactionHashResponse proto.InternalMessageInfo

func (m *GetPendingTransactionDetailByTransactionHashResponse) GetPendingTransaction() *PendingTransaction {
	if m != nil {
		return m.PendingTransaction
	}
	return nil
}

func (m *GetPendingTransactionDetailByTransactionHashResponse) GetSignatureInfo() *SignatureInfo {
	if m != nil {
		return m.SignatureInfo
	}
	return nil
}

func (m *GetPendingTransactionDetailByTransactionHashResponse) GetMultiSignatureInfo() *MultiSignatureInfo {
	if m != nil {
		return m.MultiSignatureInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.PendingTransactionStatus", PendingTransactionStatus_name, PendingTransactionStatus_value)
	proto.RegisterType((*MultiSignatureInfo)(nil), "model.MultiSignatureInfo")
	proto.RegisterType((*SignatureInfo)(nil), "model.SignatureInfo")
	proto.RegisterMapType((map[string][]byte)(nil), "model.SignatureInfo.SignaturesEntry")
	proto.RegisterType((*PendingSignature)(nil), "model.PendingSignature")
	proto.RegisterType((*PendingTransaction)(nil), "model.PendingTransaction")
	proto.RegisterType((*GetPendingTransactionByAddressRequest)(nil), "model.GetPendingTransactionByAddressRequest")
	proto.RegisterType((*GetPendingTransactionByAddressResponse)(nil), "model.GetPendingTransactionByAddressResponse")
	proto.RegisterType((*GetPendingTransactionDetailByTransactionHashRequest)(nil), "model.GetPendingTransactionDetailByTransactionHashRequest")
	proto.RegisterType((*GetPendingTransactionDetailByTransactionHashResponse)(nil), "model.GetPendingTransactionDetailByTransactionHashResponse")
}

func init() { proto.RegisterFile("model/multiSignature.proto", fileDescriptor_136af44c597c17ae) }

var fileDescriptor_136af44c597c17ae = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xc6, 0x6e, 0xa2, 0x2f, 0x37, 0x4d, 0xeb, 0x0e, 0x55, 0xe5, 0x46, 0xfc, 0x58, 0x51,
	0xa9, 0xac, 0x0a, 0x12, 0x48, 0x91, 0x40, 0x95, 0x58, 0x34, 0xb4, 0xa2, 0x15, 0xb4, 0x54, 0x53,
	0x56, 0xec, 0x5c, 0x7b, 0x70, 0xad, 0xc6, 0x33, 0xc1, 0x33, 0x46, 0x0d, 0x5b, 0x36, 0x3c, 0x00,
	0x7b, 0x9e, 0x03, 0x09, 0xf1, 0x28, 0x3c, 0x0b, 0xca, 0x8c, 0xf3, 0x67, 0xbb, 0x85, 0x8a, 0x4d,
	0xe4, 0x39, 0xe7, 0xce, 0xbd, 0xf7, 0x1c, 0x5f, 0xdf, 0x40, 0x33, 0xe6, 0x01, 0xed, 0x77, 0xe2,
	0xb4, 0x2f, 0xa3, 0xd3, 0x28, 0x64, 0x9e, 0x4c, 0x13, 0xda, 0x1e, 0x24, 0x5c, 0x72, 0x5c, 0x51,
	0x5c, 0x73, 0x4d, 0x87, 0x0c, 0xbc, 0x30, 0x62, 0x9e, 0x8c, 0x38, 0xd3, 0x74, 0xeb, 0x17, 0x02,
	0x7c, 0x34, 0x77, 0xef, 0x90, 0xbd, 0xe7, 0xf8, 0x01, 0xac, 0x1c, 0x45, 0x2c, 0x8a, 0xd3, 0x78,
	0x82, 0x0b, 0x1b, 0x39, 0xc8, 0x6d, 0x90, 0x22, 0x81, 0x6d, 0xa8, 0x1c, 0x73, 0xe6, 0x53, 0xdb,
	0x70, 0x90, 0x6b, 0xf6, 0x8c, 0x47, 0x88, 0x68, 0x00, 0xdf, 0x86, 0xda, 0x6e, 0x10, 0x24, 0x54,
	0x08, 0x2a, 0x6c, 0xd3, 0x31, 0xdd, 0x1a, 0x99, 0x02, 0xd8, 0x85, 0x65, 0x55, 0x5b, 0x44, 0x61,
	0x06, 0xda, 0x0b, 0x0e, 0x72, 0x6b, 0x24, 0x0f, 0x63, 0x07, 0xea, 0xbd, 0x3e, 0xf7, 0x2f, 0x0e,
	0x68, 0x14, 0x9e, 0x4b, 0xbb, 0xa2, 0x3a, 0x99, 0x85, 0xf0, 0x1a, 0x54, 0x5f, 0x7b, 0x92, 0x0a,
	0x69, 0x57, 0x1d, 0xe4, 0xfe, 0x4f, 0xb2, 0x53, 0xeb, 0x27, 0x82, 0xc6, 0xbc, 0x36, 0x17, 0x96,
	0xdf, 0x26, 0x1e, 0x13, 0x9e, 0x3f, 0xf2, 0xe1, 0xc0, 0x13, 0xe7, 0x4a, 0xd9, 0x22, 0xc9, 0xc3,
	0x78, 0x0f, 0x60, 0x46, 0xbe, 0xe1, 0x98, 0x6e, 0xbd, 0xbb, 0xd1, 0x56, 0x4e, 0xb6, 0xe7, 0x72,
	0x4e, 0x4f, 0x62, 0x9f, 0xc9, 0x64, 0x48, 0x66, 0xee, 0x35, 0x9f, 0xc3, 0x72, 0x8e, 0xc6, 0x16,
	0x98, 0x17, 0x74, 0xa8, 0xca, 0xd6, 0xc8, 0xe8, 0x11, 0xaf, 0x42, 0xe5, 0xa3, 0xd7, 0x4f, 0xb5,
	0x85, 0x8b, 0x44, 0x1f, 0x76, 0x8c, 0x67, 0xa8, 0xf5, 0x03, 0x81, 0x75, 0x42, 0x59, 0x10, 0xb1,
	0x70, 0x92, 0xe6, 0x06, 0x1a, 0x36, 0x61, 0x69, 0xd7, 0xf7, 0x79, 0xca, 0xe4, 0xd8, 0x62, 0x43,
	0x55, 0xcd, 0xa1, 0xa3, 0x37, 0x35, 0x49, 0x6f, 0x9b, 0x2a, 0xd7, 0x14, 0xc8, 0xfb, 0xbf, 0x70,
	0x9d, 0xff, 0x95, 0x39, 0xff, 0x3f, 0x1b, 0x80, 0xb3, 0xf6, 0x67, 0x5a, 0xc3, 0x1b, 0xd0, 0x38,
	0xa5, 0x2c, 0xa0, 0xc9, 0xb8, 0x2b, 0xed, 0xc5, 0x3c, 0x58, 0x26, 0xd3, 0x28, 0x97, 0xb9, 0x05,
	0xd6, 0x0c, 0xd4, 0x1b, 0x4a, 0x35, 0x6f, 0xa3, 0xd0, 0x02, 0x8e, 0x9f, 0x42, 0xf5, 0x54, 0x7a,
	0x32, 0xd5, 0xd3, 0xb6, 0xd4, 0xbd, 0x97, 0xbd, 0xd2, 0x62, 0x9b, 0x3a, 0x8c, 0x64, 0xe1, 0xff,
	0x30, 0x85, 0xdf, 0x11, 0xdc, 0x7f, 0x49, 0x65, 0xb1, 0x42, 0x6f, 0x98, 0x69, 0x25, 0xf4, 0x43,
	0x4a, 0x85, 0xfc, 0x4b, 0x63, 0xa6, 0x12, 0x8c, 0x9b, 0x49, 0x78, 0x0c, 0x70, 0x32, 0xd9, 0x01,
	0xca, 0xa1, 0x7a, 0x77, 0x65, 0x7c, 0x79, 0x42, 0x90, 0x99, 0xa0, 0xd6, 0x37, 0x04, 0x9b, 0x7f,
	0xea, 0x5d, 0x0c, 0x38, 0x13, 0x74, 0x34, 0xc5, 0x2f, 0x46, 0x43, 0x95, 0xad, 0x0a, 0x7d, 0xc0,
	0x18, 0x16, 0x4e, 0xbc, 0x50, 0x8f, 0x76, 0x83, 0xa8, 0x67, 0xfc, 0x0a, 0x6e, 0x15, 0x13, 0xea,
	0x15, 0x51, 0xef, 0xae, 0x5f, 0xa9, 0x86, 0x94, 0xdd, 0x6a, 0x51, 0xd8, 0x2e, 0x6d, 0x70, 0x8f,
	0x4a, 0x2f, 0xea, 0xf7, 0x86, 0xb9, 0x61, 0x19, 0x5b, 0xdd, 0x06, 0x9c, 0x63, 0x0e, 0xe8, 0x65,
	0xe6, 0x77, 0x09, 0xd3, 0xfa, 0x62, 0xc0, 0x93, 0x9b, 0xd5, 0xc9, 0x6c, 0x39, 0x2c, 0xfb, 0x04,
	0x54, 0xa1, 0x6b, 0xb5, 0x96, 0x7d, 0x37, 0x3b, 0xb9, 0x6d, 0xa6, 0x4c, 0xad, 0x77, 0x57, 0xcb,
	0xb6, 0x12, 0xc9, 0x2d, 0xbe, 0xc3, 0xb2, 0x55, 0x9f, 0xcd, 0xc0, 0xb8, 0x8d, 0x62, 0x00, 0x29,
	0xb9, 0xb4, 0xf5, 0x15, 0x81, 0x7d, 0xd5, 0xac, 0xe1, 0x3b, 0xb0, 0x5e, 0xe4, 0x32, 0xc4, 0xfa,
	0x0f, 0xdf, 0x85, 0x66, 0x91, 0xde, 0xbf, 0xa4, 0x7e, 0x2a, 0x69, 0x60, 0x21, 0xdc, 0x84, 0xb5,
	0x22, 0x7f, 0xcc, 0xdf, 0x0c, 0x2c, 0xa3, 0x3c, 0xf5, 0xfe, 0xe5, 0x20, 0x4a, 0x68, 0x60, 0x99,
	0xbd, 0xad, 0x77, 0x6e, 0x18, 0xc9, 0xf3, 0xf4, 0xac, 0xed, 0xf3, 0xb8, 0xf3, 0x89, 0xf3, 0x33,
	0x5f, 0xff, 0x3e, 0xf4, 0x79, 0x42, 0x3b, 0x3e, 0x8f, 0x63, 0xce, 0x3a, 0x4a, 0xe9, 0x59, 0x55,
	0xfd, 0x01, 0x6e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x10, 0xb1, 0xa5, 0x76, 0x3d, 0x07, 0x00,
	0x00,
}
