// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/node.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NodeInfo represent the node information data structure
type Node struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SharedAddress        string   `protobuf:"bytes,2,opt,name=SharedAddress,proto3" json:"SharedAddress,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=Port,proto3" json:"Port,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=Version,proto3" json:"Version,omitempty"`
	CodeName             string   `protobuf:"bytes,6,opt,name=CodeName,proto3" json:"CodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd0ed838ddec1c4, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Node) GetSharedAddress() string {
	if m != nil {
		return m.SharedAddress
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Node) GetCodeName() string {
	if m != nil {
		return m.CodeName
	}
	return ""
}

type NodeKey struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Seed                 string   `protobuf:"bytes,3,opt,name=Seed,proto3" json:"Seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeKey) Reset()         { *m = NodeKey{} }
func (m *NodeKey) String() string { return proto.CompactTextString(m) }
func (*NodeKey) ProtoMessage()    {}
func (*NodeKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd0ed838ddec1c4, []int{1}
}

func (m *NodeKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeKey.Unmarshal(m, b)
}
func (m *NodeKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeKey.Marshal(b, m, deterministic)
}
func (m *NodeKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeKey.Merge(m, src)
}
func (m *NodeKey) XXX_Size() int {
	return xxx_messageInfo_NodeKey.Size(m)
}
func (m *NodeKey) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeKey.DiscardUnknown(m)
}

var xxx_messageInfo_NodeKey proto.InternalMessageInfo

func (m *NodeKey) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NodeKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *NodeKey) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

type GenerateNodeKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateNodeKeyRequest) Reset()         { *m = GenerateNodeKeyRequest{} }
func (m *GenerateNodeKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateNodeKeyRequest) ProtoMessage()    {}
func (*GenerateNodeKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd0ed838ddec1c4, []int{2}
}

func (m *GenerateNodeKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateNodeKeyRequest.Unmarshal(m, b)
}
func (m *GenerateNodeKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateNodeKeyRequest.Marshal(b, m, deterministic)
}
func (m *GenerateNodeKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateNodeKeyRequest.Merge(m, src)
}
func (m *GenerateNodeKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateNodeKeyRequest.Size(m)
}
func (m *GenerateNodeKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateNodeKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateNodeKeyRequest proto.InternalMessageInfo

type GenerateNodeKeyResponse struct {
	NodePublicKey        []byte   `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateNodeKeyResponse) Reset()         { *m = GenerateNodeKeyResponse{} }
func (m *GenerateNodeKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateNodeKeyResponse) ProtoMessage()    {}
func (*GenerateNodeKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd0ed838ddec1c4, []int{3}
}

func (m *GenerateNodeKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateNodeKeyResponse.Unmarshal(m, b)
}
func (m *GenerateNodeKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateNodeKeyResponse.Marshal(b, m, deterministic)
}
func (m *GenerateNodeKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateNodeKeyResponse.Merge(m, src)
}
func (m *GenerateNodeKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateNodeKeyResponse.Size(m)
}
func (m *GenerateNodeKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateNodeKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateNodeKeyResponse proto.InternalMessageInfo

func (m *GenerateNodeKeyResponse) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "model.Node")
	proto.RegisterType((*NodeKey)(nil), "model.NodeKey")
	proto.RegisterType((*GenerateNodeKeyRequest)(nil), "model.GenerateNodeKeyRequest")
	proto.RegisterType((*GenerateNodeKeyResponse)(nil), "model.GenerateNodeKeyResponse")
}

func init() { proto.RegisterFile("model/node.proto", fileDescriptor_2fd0ed838ddec1c4) }

var fileDescriptor_2fd0ed838ddec1c4 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x34, 0x6d, 0xed, 0x60, 0x45, 0xf6, 0xa0, 0x8b, 0x78, 0x08, 0xc1, 0x43, 0x10,
	0x6c, 0x0e, 0x3e, 0x80, 0xa8, 0x05, 0x29, 0x81, 0x52, 0x52, 0xf0, 0xe0, 0x2d, 0xc9, 0x0e, 0x36,
	0xd0, 0xec, 0xd4, 0xdd, 0xcd, 0xa1, 0x3e, 0x8d, 0x8f, 0x2a, 0xbb, 0x4d, 0x5b, 0x4a, 0x2f, 0xcb,
	0xfc, 0xff, 0x3f, 0xec, 0x7c, 0xcc, 0xc0, 0x75, 0x43, 0x12, 0xd7, 0xa9, 0x22, 0x89, 0x93, 0x8d,
	0x26, 0x4b, 0xbc, 0xef, 0x9d, 0xf8, 0x8f, 0x41, 0x38, 0x27, 0x89, 0xfc, 0x0a, 0x82, 0xd9, 0x54,
	0xb0, 0x88, 0x25, 0xbd, 0x3c, 0x98, 0x4d, 0xf9, 0x03, 0x8c, 0x97, 0xab, 0x42, 0xa3, 0x7c, 0x95,
	0x52, 0xa3, 0x31, 0x22, 0x88, 0x58, 0x32, 0xca, 0x4f, 0x4d, 0x2e, 0x60, 0xb8, 0xcf, 0x7b, 0x3e,
	0xdf, 0x4b, 0xce, 0x21, 0x5c, 0x90, 0xb6, 0x22, 0x8c, 0x58, 0x32, 0xce, 0x7d, 0xed, 0xba, 0x3f,
	0x51, 0x9b, 0x9a, 0x94, 0xe8, 0xef, 0xba, 0x3b, 0xc9, 0xef, 0xe0, 0xe2, 0x9d, 0x24, 0xce, 0x8b,
	0x06, 0xc5, 0xc0, 0x47, 0x07, 0x1d, 0x67, 0x30, 0x74, 0x84, 0x19, 0x6e, 0xcf, 0x20, 0xef, 0x61,
	0xb4, 0x68, 0xcb, 0x75, 0x5d, 0x65, 0xb8, 0xf5, 0x80, 0x97, 0xf9, 0xd1, 0x70, 0x08, 0x4b, 0x44,
	0xd9, 0x91, 0xf9, 0x3a, 0x16, 0x70, 0xf3, 0x81, 0x0a, 0x75, 0x61, 0xb1, 0xfb, 0x34, 0xc7, 0x9f,
	0x16, 0x8d, 0x8d, 0x5f, 0xe0, 0xf6, 0x2c, 0x31, 0x1b, 0x52, 0x06, 0xdd, 0x2e, 0x9c, 0x75, 0x1c,
	0xc5, 0xfc, 0xa8, 0x53, 0xf3, 0xed, 0xf1, 0x2b, 0xf9, 0xae, 0xed, 0xaa, 0x2d, 0x27, 0x15, 0x35,
	0xe9, 0x2f, 0x51, 0x59, 0xed, 0xde, 0xa7, 0x8a, 0x34, 0xa6, 0x15, 0x35, 0x0d, 0xa9, 0xd4, 0xaf,
	0xbd, 0x1c, 0xf8, 0x23, 0x3c, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x59, 0x1a, 0xcb, 0x98,
	0x01, 0x00, 0x00,
}
