// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/nodeRegistration.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeRegistrationState int32

const (
	// NodeRegistered 'registred' node status (= 0): a node in node registry with this status is registered
	NodeRegistrationState_NodeRegistered NodeRegistrationState = 0
	// NodeQueued 'queued' node status (= 1): a node in node registry with this status is queued, or 'pending registered'
	NodeRegistrationState_NodeQueued NodeRegistrationState = 1
	// NodeDeleted 'deleted' node status (= 2): a node in node registry with this status is marked as deleted
	NodeRegistrationState_NodeDeleted NodeRegistrationState = 2
)

var NodeRegistrationState_name = map[int32]string{
	0: "NodeRegistered",
	1: "NodeQueued",
	2: "NodeDeleted",
}

var NodeRegistrationState_value = map[string]int32{
	"NodeRegistered": 0,
	"NodeQueued":     1,
	"NodeDeleted":    2,
}

func (x NodeRegistrationState) String() string {
	return proto.EnumName(NodeRegistrationState_name, int32(x))
}

func (NodeRegistrationState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df1af0ec89e31788, []int{0}
}

type NodeRegistration struct {
	NodeID               int64            `protobuf:"varint,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	NodePublicKey        []byte           `protobuf:"bytes,2,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	AccountAddress       string           `protobuf:"bytes,3,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	RegistrationHeight   uint32           `protobuf:"varint,4,opt,name=RegistrationHeight,proto3" json:"RegistrationHeight,omitempty"`
	LockedBalance        int64            `protobuf:"varint,5,opt,name=LockedBalance,proto3" json:"LockedBalance,omitempty"`
	RegistrationStatus   uint32           `protobuf:"varint,6,opt,name=RegistrationStatus,proto3" json:"RegistrationStatus,omitempty"`
	Latest               bool             `protobuf:"varint,7,opt,name=Latest,proto3" json:"Latest,omitempty"`
	Height               uint32           `protobuf:"varint,8,opt,name=Height,proto3" json:"Height,omitempty"`
	NodeAddressInfo      *NodeAddressInfo `protobuf:"bytes,9,opt,name=NodeAddressInfo,proto3" json:"NodeAddressInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NodeRegistration) Reset()         { *m = NodeRegistration{} }
func (m *NodeRegistration) String() string { return proto.CompactTextString(m) }
func (*NodeRegistration) ProtoMessage()    {}
func (*NodeRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1af0ec89e31788, []int{0}
}

func (m *NodeRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegistration.Unmarshal(m, b)
}
func (m *NodeRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegistration.Marshal(b, m, deterministic)
}
func (m *NodeRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegistration.Merge(m, src)
}
func (m *NodeRegistration) XXX_Size() int {
	return xxx_messageInfo_NodeRegistration.Size(m)
}
func (m *NodeRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegistration proto.InternalMessageInfo

func (m *NodeRegistration) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *NodeRegistration) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *NodeRegistration) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *NodeRegistration) GetRegistrationHeight() uint32 {
	if m != nil {
		return m.RegistrationHeight
	}
	return 0
}

func (m *NodeRegistration) GetLockedBalance() int64 {
	if m != nil {
		return m.LockedBalance
	}
	return 0
}

func (m *NodeRegistration) GetRegistrationStatus() uint32 {
	if m != nil {
		return m.RegistrationStatus
	}
	return 0
}

func (m *NodeRegistration) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

func (m *NodeRegistration) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NodeRegistration) GetNodeAddressInfo() *NodeAddressInfo {
	if m != nil {
		return m.NodeAddressInfo
	}
	return nil
}

// GetNodeRegisterRequest create request to get a list of node registry
type GetNodeRegistrationsRequest struct {
	// Fetch Node Registries based on queue status
	//2 : will retrieve node registries that have been deleted
	//1 : will retrieve node registries that still pending
	//0: will retrieve node registries that already registered
	RegistrationStatus uint32 `protobuf:"varint,1,opt,name=RegistrationStatus,proto3" json:"RegistrationStatus,omitempty"`
	// Fetch Node Registries when registration height is greater than or equal to
	MinRegistrationHeight uint32 `protobuf:"varint,2,opt,name=MinRegistrationHeight,proto3" json:"MinRegistrationHeight,omitempty"`
	// Fetch Node Registries when registration height is less than or equal to
	MaxRegistrationHeight uint32 `protobuf:"varint,3,opt,name=MaxRegistrationHeight,proto3" json:"MaxRegistrationHeight,omitempty"`
	// Fetch Node Registries based on Pagination field
	Pagination           *Pagination `protobuf:"bytes,4,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetNodeRegistrationsRequest) Reset()         { *m = GetNodeRegistrationsRequest{} }
func (m *GetNodeRegistrationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRegistrationsRequest) ProtoMessage()    {}
func (*GetNodeRegistrationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1af0ec89e31788, []int{1}
}

func (m *GetNodeRegistrationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRegistrationsRequest.Unmarshal(m, b)
}
func (m *GetNodeRegistrationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRegistrationsRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeRegistrationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRegistrationsRequest.Merge(m, src)
}
func (m *GetNodeRegistrationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRegistrationsRequest.Size(m)
}
func (m *GetNodeRegistrationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRegistrationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRegistrationsRequest proto.InternalMessageInfo

func (m *GetNodeRegistrationsRequest) GetRegistrationStatus() uint32 {
	if m != nil {
		return m.RegistrationStatus
	}
	return 0
}

func (m *GetNodeRegistrationsRequest) GetMinRegistrationHeight() uint32 {
	if m != nil {
		return m.MinRegistrationHeight
	}
	return 0
}

func (m *GetNodeRegistrationsRequest) GetMaxRegistrationHeight() uint32 {
	if m != nil {
		return m.MaxRegistrationHeight
	}
	return 0
}

func (m *GetNodeRegistrationsRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetNodeRegistrationsResponse struct {
	// Number of node registry in total
	Total uint64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	// NodeRegistrations list of NodeRegistration
	NodeRegistrations    []*NodeRegistration `protobuf:"bytes,2,rep,name=NodeRegistrations,proto3" json:"NodeRegistrations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetNodeRegistrationsResponse) Reset()         { *m = GetNodeRegistrationsResponse{} }
func (m *GetNodeRegistrationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeRegistrationsResponse) ProtoMessage()    {}
func (*GetNodeRegistrationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1af0ec89e31788, []int{2}
}

func (m *GetNodeRegistrationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRegistrationsResponse.Unmarshal(m, b)
}
func (m *GetNodeRegistrationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRegistrationsResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeRegistrationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRegistrationsResponse.Merge(m, src)
}
func (m *GetNodeRegistrationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeRegistrationsResponse.Size(m)
}
func (m *GetNodeRegistrationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRegistrationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRegistrationsResponse proto.InternalMessageInfo

func (m *GetNodeRegistrationsResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetNodeRegistrationsResponse) GetNodeRegistrations() []*NodeRegistration {
	if m != nil {
		return m.NodeRegistrations
	}
	return nil
}

// GetNodeRegistrationRequest create request for single node register
type GetNodeRegistrationRequest struct {
	NodePublicKey        []byte   `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	AccountAddress       string   `protobuf:"bytes,2,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	RegistrationHeight   uint32   `protobuf:"varint,3,opt,name=RegistrationHeight,proto3" json:"RegistrationHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRegistrationRequest) Reset()         { *m = GetNodeRegistrationRequest{} }
func (m *GetNodeRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRegistrationRequest) ProtoMessage()    {}
func (*GetNodeRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1af0ec89e31788, []int{3}
}

func (m *GetNodeRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRegistrationRequest.Unmarshal(m, b)
}
func (m *GetNodeRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRegistrationRequest.Merge(m, src)
}
func (m *GetNodeRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRegistrationRequest.Size(m)
}
func (m *GetNodeRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRegistrationRequest proto.InternalMessageInfo

func (m *GetNodeRegistrationRequest) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *GetNodeRegistrationRequest) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *GetNodeRegistrationRequest) GetRegistrationHeight() uint32 {
	if m != nil {
		return m.RegistrationHeight
	}
	return 0
}

type GetNodeRegistrationResponse struct {
	NodeRegistration     *NodeRegistration `protobuf:"bytes,1,opt,name=NodeRegistration,proto3" json:"NodeRegistration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetNodeRegistrationResponse) Reset()         { *m = GetNodeRegistrationResponse{} }
func (m *GetNodeRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeRegistrationResponse) ProtoMessage()    {}
func (*GetNodeRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1af0ec89e31788, []int{4}
}

func (m *GetNodeRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRegistrationResponse.Unmarshal(m, b)
}
func (m *GetNodeRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRegistrationResponse.Merge(m, src)
}
func (m *GetNodeRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeRegistrationResponse.Size(m)
}
func (m *GetNodeRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRegistrationResponse proto.InternalMessageInfo

func (m *GetNodeRegistrationResponse) GetNodeRegistration() *NodeRegistration {
	if m != nil {
		return m.NodeRegistration
	}
	return nil
}

// NodeAdmissionTimestamp represent the timestamp for next node admission
type NodeAdmissionTimestamp struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	BlockHeight          uint32   `protobuf:"varint,2,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Latest               bool     `protobuf:"varint,3,opt,name=Latest,proto3" json:"Latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeAdmissionTimestamp) Reset()         { *m = NodeAdmissionTimestamp{} }
func (m *NodeAdmissionTimestamp) String() string { return proto.CompactTextString(m) }
func (*NodeAdmissionTimestamp) ProtoMessage()    {}
func (*NodeAdmissionTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1af0ec89e31788, []int{5}
}

func (m *NodeAdmissionTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAdmissionTimestamp.Unmarshal(m, b)
}
func (m *NodeAdmissionTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAdmissionTimestamp.Marshal(b, m, deterministic)
}
func (m *NodeAdmissionTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAdmissionTimestamp.Merge(m, src)
}
func (m *NodeAdmissionTimestamp) XXX_Size() int {
	return xxx_messageInfo_NodeAdmissionTimestamp.Size(m)
}
func (m *NodeAdmissionTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAdmissionTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAdmissionTimestamp proto.InternalMessageInfo

func (m *NodeAdmissionTimestamp) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NodeAdmissionTimestamp) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *NodeAdmissionTimestamp) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

func init() {
	proto.RegisterEnum("model.NodeRegistrationState", NodeRegistrationState_name, NodeRegistrationState_value)
	proto.RegisterType((*NodeRegistration)(nil), "model.NodeRegistration")
	proto.RegisterType((*GetNodeRegistrationsRequest)(nil), "model.GetNodeRegistrationsRequest")
	proto.RegisterType((*GetNodeRegistrationsResponse)(nil), "model.GetNodeRegistrationsResponse")
	proto.RegisterType((*GetNodeRegistrationRequest)(nil), "model.GetNodeRegistrationRequest")
	proto.RegisterType((*GetNodeRegistrationResponse)(nil), "model.GetNodeRegistrationResponse")
	proto.RegisterType((*NodeAdmissionTimestamp)(nil), "model.NodeAdmissionTimestamp")
}

func init() { proto.RegisterFile("model/nodeRegistration.proto", fileDescriptor_df1af0ec89e31788) }

var fileDescriptor_df1af0ec89e31788 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0xfd, 0x9c, 0xac, 0xfd, 0xd6, 0x5b, 0xda, 0x75, 0x96, 0x56, 0xa2, 0x6e, 0x0f, 0x51, 0x84,
	0x50, 0x34, 0x89, 0x16, 0x0a, 0x3f, 0x80, 0x95, 0x21, 0x98, 0x28, 0xd3, 0x08, 0x7b, 0xe2, 0x2d,
	0x4d, 0x2e, 0x9d, 0xb5, 0xc4, 0x2e, 0xb5, 0x23, 0x01, 0x2f, 0xfc, 0x0f, 0x7e, 0x23, 0x3f, 0x80,
	0x47, 0x14, 0x27, 0xb4, 0x6e, 0x92, 0x21, 0x78, 0xa9, 0xea, 0x73, 0x7c, 0xec, 0x7b, 0x8f, 0xcf,
	0x0d, 0x9c, 0xa4, 0x22, 0xc6, 0x64, 0xc2, 0x45, 0x8c, 0x01, 0x2e, 0x99, 0x54, 0xeb, 0x50, 0x31,
	0xc1, 0xc7, 0xab, 0xb5, 0x50, 0x82, 0xb6, 0x34, 0x3b, 0x1a, 0x16, 0x9b, 0x56, 0xe1, 0x92, 0x71,
	0x83, 0x1e, 0x1d, 0x6f, 0xc5, 0x67, 0x71, 0xbc, 0x46, 0x29, 0x2f, 0xf8, 0x47, 0x51, 0x90, 0xde,
	0x4f, 0x0b, 0x06, 0x97, 0x95, 0x63, 0xe9, 0x08, 0xda, 0x39, 0x76, 0x71, 0xee, 0x10, 0x97, 0xf8,
	0xf6, 0xcc, 0x7a, 0x4c, 0x82, 0x12, 0xa1, 0x0f, 0xa0, 0x97, 0xff, 0xbb, 0xca, 0x16, 0x09, 0x8b,
	0xde, 0xe0, 0x17, 0xc7, 0x72, 0x89, 0x7f, 0x2f, 0xd8, 0x05, 0xe9, 0x43, 0xe8, 0x9f, 0x45, 0x91,
	0xc8, 0xb8, 0x2a, 0xaf, 0x74, 0x6c, 0x97, 0xf8, 0x9d, 0xa0, 0x82, 0xd2, 0x31, 0x50, 0xf3, 0xe6,
	0xd7, 0xc8, 0x96, 0x37, 0xca, 0xd9, 0x73, 0x89, 0xdf, 0x0b, 0x1a, 0x18, 0xea, 0x43, 0x6f, 0x2e,
	0xa2, 0x5b, 0x8c, 0x67, 0x61, 0x12, 0xf2, 0x08, 0x9d, 0xd6, 0xa6, 0xc0, 0x5d, 0xa2, 0x7a, 0xf2,
	0x7b, 0x15, 0xaa, 0x4c, 0x3a, 0xed, 0xfa, 0xc9, 0x05, 0x43, 0x87, 0xd0, 0x9e, 0x87, 0x0a, 0xa5,
	0x72, 0xfe, 0x77, 0x89, 0xbf, 0x1f, 0x94, 0xab, 0x1c, 0x2f, 0xab, 0xda, 0xd7, 0xda, 0x72, 0x45,
	0x9f, 0xc3, 0xc1, 0xe5, 0xae, 0xa3, 0x4e, 0xc7, 0x25, 0x7e, 0x77, 0x3a, 0x1c, 0x6b, 0xbf, 0xc7,
	0x15, 0x36, 0xa8, 0x6e, 0xf7, 0x7e, 0x10, 0x38, 0x7e, 0x85, 0xaa, 0xea, 0xbe, 0x0c, 0xf0, 0x53,
	0x96, 0xdf, 0xdc, 0xdc, 0x01, 0xb9, 0xb3, 0x83, 0x67, 0x70, 0xf4, 0x96, 0xf1, 0x06, 0x3b, 0x2d,
	0x2d, 0x69, 0x26, 0xb5, 0x2a, 0xfc, 0xdc, 0xa0, 0xb2, 0x4b, 0x55, 0x13, 0x49, 0x9f, 0x00, 0x5c,
	0x6d, 0x72, 0xa6, 0xdf, 0xab, 0x3b, 0x3d, 0x2c, 0x1b, 0xdf, 0x12, 0x81, 0xb1, 0xc9, 0xfb, 0x06,
	0x27, 0xcd, 0xdd, 0xca, 0x95, 0xe0, 0x12, 0xa9, 0x03, 0xad, 0x6b, 0xa1, 0xc2, 0x44, 0x77, 0xb8,
	0xa7, 0x9f, 0xb4, 0x00, 0xe8, 0x4b, 0x38, 0xac, 0xc9, 0x1c, 0xcb, 0xb5, 0xfd, 0xee, 0xf4, 0xbe,
	0x61, 0xb6, 0xc9, 0x07, 0x75, 0x85, 0xf7, 0x9d, 0xc0, 0xa8, 0xa1, 0x82, 0xdf, 0x76, 0xd7, 0x82,
	0x4d, 0xfe, 0x2e, 0xd8, 0xd6, 0x3f, 0x04, 0xdb, 0xbe, 0x2b, 0xd8, 0xde, 0xa2, 0x31, 0x0b, 0x1b,
	0x73, 0x5e, 0xd4, 0xa7, 0x54, 0xd7, 0xf7, 0x07, 0x07, 0x6a, 0x02, 0x4f, 0xc1, 0xb0, 0xc8, 0x60,
	0xca, 0xa4, 0x64, 0x82, 0x5f, 0xb3, 0x14, 0xa5, 0x0a, 0xd3, 0x15, 0x75, 0xa1, 0xb3, 0x59, 0x18,
	0x33, 0xdf, 0x31, 0x77, 0x74, 0x67, 0x89, 0x88, 0x6e, 0x77, 0x22, 0x65, 0x42, 0xc6, 0x00, 0xd9,
	0xe6, 0x00, 0x9d, 0xce, 0xe1, 0xa8, 0x5a, 0x49, 0x1e, 0x58, 0xa4, 0x14, 0xfa, 0x5b, 0x02, 0xd7,
	0x18, 0x0f, 0xfe, 0xa3, 0x7d, 0x80, 0x1c, 0x7b, 0x97, 0x61, 0x86, 0xf1, 0x80, 0xd0, 0x03, 0xe8,
	0xe6, 0xeb, 0x73, 0x4c, 0x50, 0x61, 0x3c, 0xb0, 0x66, 0xa7, 0x1f, 0xfc, 0x25, 0x53, 0x37, 0xd9,
	0x62, 0x1c, 0x89, 0x74, 0xf2, 0x55, 0x88, 0x45, 0x54, 0xfc, 0x3e, 0x8a, 0xc4, 0x1a, 0x27, 0x91,
	0x48, 0x53, 0xc1, 0x27, 0xda, 0x92, 0x45, 0x5b, 0x7f, 0xe2, 0x9e, 0xfe, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x31, 0xc2, 0x4b, 0x3e, 0x05, 0x00, 0x00,
}
