// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/participationScore.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParticipationScore struct {
	NodeID               int64    `protobuf:"varint,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Score                int64    `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`
	Latest               bool     `protobuf:"varint,3,opt,name=Latest,proto3" json:"Latest,omitempty"`
	Height               uint32   `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipationScore) Reset()         { *m = ParticipationScore{} }
func (m *ParticipationScore) String() string { return proto.CompactTextString(m) }
func (*ParticipationScore) ProtoMessage()    {}
func (*ParticipationScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eacd5198105d193, []int{0}
}

func (m *ParticipationScore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipationScore.Unmarshal(m, b)
}
func (m *ParticipationScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipationScore.Marshal(b, m, deterministic)
}
func (m *ParticipationScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipationScore.Merge(m, src)
}
func (m *ParticipationScore) XXX_Size() int {
	return xxx_messageInfo_ParticipationScore.Size(m)
}
func (m *ParticipationScore) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipationScore.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipationScore proto.InternalMessageInfo

func (m *ParticipationScore) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *ParticipationScore) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ParticipationScore) GetLatest() bool {
	if m != nil {
		return m.Latest
	}
	return false
}

func (m *ParticipationScore) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*ParticipationScore)(nil), "model.ParticipationScore")
}

func init() { proto.RegisterFile("model/participationScore.proto", fileDescriptor_4eacd5198105d193) }

var fileDescriptor_4eacd5198105d193 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2f, 0x48, 0x2c, 0x2a, 0xc9, 0x4c, 0xce, 0x2c, 0x48, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b,
	0x4e, 0xce, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0xcb, 0x2b, 0x55,
	0x71, 0x09, 0x05, 0x60, 0x28, 0x11, 0x92, 0xe2, 0x62, 0xf3, 0xcb, 0x4f, 0x49, 0xf5, 0x74, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x76, 0x62, 0x32, 0x60, 0x0c, 0x82, 0x8a, 0x08, 0x49, 0x70, 0xb1,
	0x82, 0x15, 0x49, 0x30, 0xc1, 0xa5, 0x20, 0x02, 0x42, 0x62, 0x5c, 0x6c, 0x3e, 0x89, 0x25, 0xa9,
	0xc5, 0x25, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x50, 0x1e, 0x48, 0xdc, 0x23, 0x35, 0x33,
	0x3d, 0xa3, 0x44, 0x82, 0x45, 0x81, 0x51, 0x83, 0x37, 0x08, 0xca, 0x73, 0xd2, 0x8a, 0xd2, 0x48,
	0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xaf, 0xca, 0xcf, 0x4f, 0x4a, 0x86,
	0x90, 0xba, 0x20, 0xe3, 0xf4, 0x93, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0xf4, 0xc1, 0xee, 0x4c, 0x62,
	0x03, 0xbb, 0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x14, 0x36, 0xd2, 0xd5, 0xd7, 0x00, 0x00,
	0x00,
}
