// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/receipt.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Receipt is a pure receipt that was generated by others
type Receipt struct {
	SenderPublicKey      []byte   `protobuf:"bytes,1,opt,name=SenderPublicKey,proto3" json:"SenderPublicKey,omitempty"`
	RecipientPublicKey   []byte   `protobuf:"bytes,2,opt,name=RecipientPublicKey,proto3" json:"RecipientPublicKey,omitempty"`
	DatumType            uint32   `protobuf:"varint,3,opt,name=DatumType,proto3" json:"DatumType,omitempty"`
	DatumHash            []byte   `protobuf:"bytes,4,opt,name=DatumHash,proto3" json:"DatumHash,omitempty"`
	ReferenceBlockHeight uint32   `protobuf:"varint,5,opt,name=ReferenceBlockHeight,proto3" json:"ReferenceBlockHeight,omitempty"`
	ReferenceBlockHash   []byte   `protobuf:"bytes,6,opt,name=ReferenceBlockHash,proto3" json:"ReferenceBlockHash,omitempty"`
	RMRLinked            []byte   `protobuf:"bytes,7,opt,name=RMRLinked,proto3" json:"RMRLinked,omitempty"`
	RecipientSignature   []byte   `protobuf:"bytes,8,opt,name=RecipientSignature,proto3" json:"RecipientSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9bd5eefeeea3e5, []int{0}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetSenderPublicKey() []byte {
	if m != nil {
		return m.SenderPublicKey
	}
	return nil
}

func (m *Receipt) GetRecipientPublicKey() []byte {
	if m != nil {
		return m.RecipientPublicKey
	}
	return nil
}

func (m *Receipt) GetDatumType() uint32 {
	if m != nil {
		return m.DatumType
	}
	return 0
}

func (m *Receipt) GetDatumHash() []byte {
	if m != nil {
		return m.DatumHash
	}
	return nil
}

func (m *Receipt) GetReferenceBlockHeight() uint32 {
	if m != nil {
		return m.ReferenceBlockHeight
	}
	return 0
}

func (m *Receipt) GetReferenceBlockHash() []byte {
	if m != nil {
		return m.ReferenceBlockHash
	}
	return nil
}

func (m *Receipt) GetRMRLinked() []byte {
	if m != nil {
		return m.RMRLinked
	}
	return nil
}

func (m *Receipt) GetRecipientSignature() []byte {
	if m != nil {
		return m.RecipientSignature
	}
	return nil
}

func init() {
	proto.RegisterType((*Receipt)(nil), "model.Receipt")
}

func init() { proto.RegisterFile("model/receipt.proto", fileDescriptor_cb9bd5eefeeea3e5) }

var fileDescriptor_cb9bd5eefeeea3e5 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xe9, 0x74, 0x9b, 0x06, 0x45, 0x88, 0x1e, 0x72, 0xf0, 0x30, 0x3c, 0x15, 0xc1, 0x16,
	0xf4, 0x1f, 0x0c, 0x0f, 0x03, 0x15, 0x24, 0xf3, 0xe4, 0xad, 0x4d, 0x5f, 0xdb, 0xb0, 0x26, 0x5f,
	0x89, 0xe9, 0x61, 0xfe, 0x4b, 0xff, 0x91, 0x2c, 0xc5, 0x96, 0x95, 0x5e, 0x72, 0x78, 0x9e, 0x8f,
	0x97, 0xf7, 0xcb, 0xc7, 0xae, 0x0d, 0x15, 0xa8, 0x53, 0x07, 0x05, 0xdd, 0xf8, 0xa4, 0x71, 0xe4,
	0x89, 0xcf, 0x03, 0xbc, 0xfb, 0x9d, 0xb1, 0xa5, 0xec, 0x04, 0x8f, 0xd9, 0xd5, 0x16, 0xb6, 0x80,
	0x7b, 0x6f, 0xf3, 0x5a, 0xab, 0x17, 0xec, 0x45, 0xb4, 0x8a, 0xe2, 0x0b, 0x39, 0xc6, 0x3c, 0x61,
	0x5c, 0x42, 0xe9, 0x46, 0xc3, 0xfa, 0x61, 0x78, 0x16, 0x86, 0x27, 0x0c, 0xbf, 0x65, 0xe7, 0xcf,
	0x99, 0x6f, 0xcd, 0xc7, 0xbe, 0x81, 0x38, 0x59, 0x45, 0xf1, 0xa5, 0x1c, 0x40, 0x6f, 0x37, 0xd9,
	0x77, 0x25, 0x4e, 0x43, 0xc8, 0x00, 0xf8, 0x23, 0xbb, 0x91, 0xf8, 0x82, 0x83, 0x55, 0x58, 0xd7,
	0xa4, 0x76, 0x1b, 0xe8, 0xb2, 0xf2, 0x62, 0x1e, 0x62, 0x26, 0x5d, 0xd7, 0xef, 0x88, 0x1f, 0xa2,
	0x17, 0xff, 0xfd, 0xc6, 0xe6, 0xd0, 0x40, 0xbe, 0xc9, 0x57, 0x6d, 0x77, 0x28, 0xc4, 0xb2, 0x6b,
	0xd0, 0x83, 0xa3, 0x6d, 0xb7, 0xba, 0xb4, 0x99, 0x6f, 0x1d, 0xc4, 0xd9, 0x68, 0xdb, 0xde, 0xac,
	0xef, 0x3f, 0xe3, 0x52, 0xfb, 0xaa, 0xcd, 0x13, 0x45, 0x26, 0xfd, 0x21, 0xca, 0x55, 0xf7, 0x3e,
	0x28, 0x72, 0x48, 0x15, 0x19, 0x43, 0x36, 0x0d, 0xff, 0x9f, 0x2f, 0xc2, 0x35, 0x9e, 0xfe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x18, 0xb5, 0x90, 0xa4, 0x01, 0x00, 0x00,
}
