// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/smith.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SmithingStatuses used to show statuses of node in smithing process
type SmithingStatuses int32

const (
	SmithingStatuses_Smithing     SmithingStatuses = 0
	SmithingStatuses_NotSmithing  SmithingStatuses = 1
	SmithingStatuses_StopSmithing SmithingStatuses = 2
)

var SmithingStatuses_name = map[int32]string{
	0: "Smithing",
	1: "NotSmithing",
	2: "StopSmithing",
}

var SmithingStatuses_value = map[string]int32{
	"Smithing":     0,
	"NotSmithing":  1,
	"StopSmithing": 2,
}

func (x SmithingStatuses) String() string {
	return proto.EnumName(SmithingStatuses_name, int32(x))
}

func (SmithingStatuses) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aa53f6be5184f675, []int{0}
}

type GetSmithingStatusResponse struct {
	SmithingStatus       SmithingStatuses `protobuf:"varint,1,opt,name=SmithingStatus,proto3,enum=model.SmithingStatuses" json:"SmithingStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetSmithingStatusResponse) Reset()         { *m = GetSmithingStatusResponse{} }
func (m *GetSmithingStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetSmithingStatusResponse) ProtoMessage()    {}
func (*GetSmithingStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa53f6be5184f675, []int{0}
}

func (m *GetSmithingStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSmithingStatusResponse.Unmarshal(m, b)
}
func (m *GetSmithingStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSmithingStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetSmithingStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSmithingStatusResponse.Merge(m, src)
}
func (m *GetSmithingStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetSmithingStatusResponse.Size(m)
}
func (m *GetSmithingStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSmithingStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSmithingStatusResponse proto.InternalMessageInfo

func (m *GetSmithingStatusResponse) GetSmithingStatus() SmithingStatuses {
	if m != nil {
		return m.SmithingStatus
	}
	return SmithingStatuses_Smithing
}

func init() {
	proto.RegisterEnum("model.SmithingStatuses", SmithingStatuses_name, SmithingStatuses_value)
	proto.RegisterType((*GetSmithingStatusResponse)(nil), "model.GetSmithingStatusResponse")
}

func init() { proto.RegisterFile("model/smith.proto", fileDescriptor_aa53f6be5184f675) }

var fileDescriptor_aa53f6be5184f675 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2f, 0xce, 0xcd, 0x2c, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x0b, 0x29, 0xc5, 0x70, 0x49, 0xba, 0xa7, 0x96, 0x04, 0x83, 0x24, 0x32, 0xf3, 0xd2, 0x83, 0x4b,
	0x12, 0x4b, 0x4a, 0x8b, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xec, 0xb9, 0xf8,
	0x50, 0x65, 0x24, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xc4, 0xf5, 0xc0, 0x9a, 0xf5, 0x50, 0x25,
	0x53, 0x8b, 0x83, 0xd0, 0x94, 0x6b, 0x39, 0x73, 0x09, 0xa0, 0xab, 0x11, 0xe2, 0xe1, 0xe2, 0x80,
	0x89, 0x09, 0x30, 0x08, 0xf1, 0x73, 0x71, 0xfb, 0xe5, 0xc3, 0xed, 0x17, 0x60, 0x14, 0x12, 0xe0,
	0xe2, 0x09, 0x2e, 0xc9, 0x2f, 0x80, 0x8b, 0x30, 0x39, 0x69, 0x45, 0x69, 0xa4, 0x67, 0x96, 0x64,
	0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x57, 0xe5, 0xe7, 0x27, 0x25, 0x43, 0x48, 0xdd, 0xe4,
	0xfc, 0xa2, 0x54, 0xfd, 0xe4, 0xfc, 0xdc, 0xdc, 0xfc, 0x3c, 0x7d, 0xb0, 0x8b, 0x92, 0xd8, 0xc0,
	0x9e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x90, 0x33, 0xe2, 0xff, 0xf1, 0x00, 0x00, 0x00,
}
