// ZooBC Copyright (C) 2020 Quasisoft Limited - Hong Kong
// This file is part of ZooBC <https://github.com/zoobc/zoobc-core>
//
// ZooBC is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// ZooBC is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with ZooBC.  If not, see <http://www.gnu.org/licenses/>.
//
// Additional Permission Under GNU GPL Version 3 section 7.
// As the special exception permitted under Section 7b, c and e,
// in respect with the Author’s copyright, please refer to this section:
//
// 1. You are free to convey this Program according to GNU GPL Version 3,
//     as long as you respect and comply with the Author’s copyright by
//     showing in its user interface an Appropriate Notice that the derivate
//     program and its source code are “powered by ZooBC”.
//     This is an acknowledgement for the copyright holder, ZooBC,
//     as the implementation of appreciation of the exclusive right of the
//     creator and to avoid any circumvention on the rights under trademark
//     law for use of some trade names, trademarks, or service marks.
//
// 2. Complying to the GNU GPL Version 3, you may distribute
//     the program without any permission from the Author.
//     However a prior notification to the authors will be appreciated.
//
// ZooBC is architected by Roberto Capodieci & Barton Johnston
//             contact us at roberto.capodieci[at]blockchainzoo.com
//             and barton.johnston[at]blockchainzoo.com
//
// Core developers that contributed to the current implementation of the
// software are:
//             Ahmad Ali Abdilah ahmad.abdilah[at]blockchainzoo.com
//             Allan Bintoro allan.bintoro[at]blockchainzoo.com
//             Andy Herman
//             Gede Sukra
//             Ketut Ariasa
//             Nawi Kartini nawi.kartini[at]blockchainzoo.com
//             Stefano Galassi stefano.galassi[at]blockchainzoo.com
//
// IMPORTANT: The above copyright notice and this permission notice
// shall be included in all copies or substantial portions of the Software.
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/snapshot.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SnapshotFileInfo model to pass data between snapshot and spineBlockManifest interfaces
type SnapshotFileInfo struct {
	SnapshotFileHash           []byte                 `protobuf:"bytes,1,opt,name=SnapshotFileHash,proto3" json:"SnapshotFileHash,omitempty"`
	Height                     uint32                 `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	ProcessExpirationTimestamp int64                  `protobuf:"varint,3,opt,name=ProcessExpirationTimestamp,proto3" json:"ProcessExpirationTimestamp,omitempty"`
	ChainType                  int32                  `protobuf:"varint,4,opt,name=ChainType,proto3" json:"ChainType,omitempty"`
	SpineBlockManifestType     SpineBlockManifestType `protobuf:"varint,5,opt,name=SpineBlockManifestType,proto3,enum=model.SpineBlockManifestType" json:"SpineBlockManifestType,omitempty"`
	FileChunksHashes           [][]byte               `protobuf:"bytes,6,rep,name=FileChunksHashes,proto3" json:"FileChunksHashes,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}               `json:"-"`
	XXX_unrecognized           []byte                 `json:"-"`
	XXX_sizecache              int32                  `json:"-"`
}

func (m *SnapshotFileInfo) Reset()         { *m = SnapshotFileInfo{} }
func (m *SnapshotFileInfo) String() string { return proto.CompactTextString(m) }
func (*SnapshotFileInfo) ProtoMessage()    {}
func (*SnapshotFileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9d8140a8c06fc6, []int{0}
}

func (m *SnapshotFileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotFileInfo.Unmarshal(m, b)
}
func (m *SnapshotFileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotFileInfo.Marshal(b, m, deterministic)
}
func (m *SnapshotFileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotFileInfo.Merge(m, src)
}
func (m *SnapshotFileInfo) XXX_Size() int {
	return xxx_messageInfo_SnapshotFileInfo.Size(m)
}
func (m *SnapshotFileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotFileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotFileInfo proto.InternalMessageInfo

func (m *SnapshotFileInfo) GetSnapshotFileHash() []byte {
	if m != nil {
		return m.SnapshotFileHash
	}
	return nil
}

func (m *SnapshotFileInfo) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SnapshotFileInfo) GetProcessExpirationTimestamp() int64 {
	if m != nil {
		return m.ProcessExpirationTimestamp
	}
	return 0
}

func (m *SnapshotFileInfo) GetChainType() int32 {
	if m != nil {
		return m.ChainType
	}
	return 0
}

func (m *SnapshotFileInfo) GetSpineBlockManifestType() SpineBlockManifestType {
	if m != nil {
		return m.SpineBlockManifestType
	}
	return SpineBlockManifestType_Snapshot
}

func (m *SnapshotFileInfo) GetFileChunksHashes() [][]byte {
	if m != nil {
		return m.FileChunksHashes
	}
	return nil
}

// SnapshotPayload snapshot data
type SnapshotPayload struct {
	Blocks                     []*Block                     `protobuf:"bytes,1,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	AccountBalances            []*AccountBalance            `protobuf:"bytes,2,rep,name=AccountBalances,proto3" json:"AccountBalances,omitempty"`
	NodeRegistrations          []*NodeRegistration          `protobuf:"bytes,3,rep,name=NodeRegistrations,proto3" json:"NodeRegistrations,omitempty"`
	AccountDatasets            []*AccountDataset            `protobuf:"bytes,4,rep,name=AccountDatasets,proto3" json:"AccountDatasets,omitempty"`
	ParticipationScores        []*ParticipationScore        `protobuf:"bytes,5,rep,name=ParticipationScores,proto3" json:"ParticipationScores,omitempty"`
	PublishedReceipts          []*PublishedReceipt          `protobuf:"bytes,6,rep,name=PublishedReceipts,proto3" json:"PublishedReceipts,omitempty"`
	EscrowTransactions         []*Escrow                    `protobuf:"bytes,7,rep,name=EscrowTransactions,proto3" json:"EscrowTransactions,omitempty"`
	PendingTransactions        []*PendingTransaction        `protobuf:"bytes,8,rep,name=PendingTransactions,proto3" json:"PendingTransactions,omitempty"`
	PendingSignatures          []*PendingSignature          `protobuf:"bytes,9,rep,name=PendingSignatures,proto3" json:"PendingSignatures,omitempty"`
	MultiSignatureInfos        []*MultiSignatureInfo        `protobuf:"bytes,10,rep,name=MultiSignatureInfos,proto3" json:"MultiSignatureInfos,omitempty"`
	SkippedBlocksmiths         []*SkippedBlocksmith         `protobuf:"bytes,11,rep,name=SkippedBlocksmiths,proto3" json:"SkippedBlocksmiths,omitempty"`
	FeeScale                   []*FeeScale                  `protobuf:"bytes,12,rep,name=FeeScale,proto3" json:"FeeScale,omitempty"`
	FeeVoteCommitmentVote      []*FeeVoteCommitmentVote     `protobuf:"bytes,13,rep,name=FeeVoteCommitmentVote,proto3" json:"FeeVoteCommitmentVote,omitempty"`
	FeeVoteRevealVote          []*FeeVoteRevealVote         `protobuf:"bytes,14,rep,name=FeeVoteRevealVote,proto3" json:"FeeVoteRevealVote,omitempty"`
	LiquidPayment              []*LiquidPayment             `protobuf:"bytes,15,rep,name=LiquidPayment,proto3" json:"LiquidPayment,omitempty"`
	NodeAdmissionTimestamp     []*NodeAdmissionTimestamp    `protobuf:"bytes,16,rep,name=NodeAdmissionTimestamp,proto3" json:"NodeAdmissionTimestamp,omitempty"`
	MultiSignatureParticipants []*MultiSignatureParticipant `protobuf:"bytes,17,rep,name=MultiSignatureParticipants,proto3" json:"MultiSignatureParticipants,omitempty"`
	AtomicTransaction          []*Atomic                    `protobuf:"bytes,18,rep,name=AtomicTransaction,proto3" json:"AtomicTransaction,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                     `json:"-"`
	XXX_unrecognized           []byte                       `json:"-"`
	XXX_sizecache              int32                        `json:"-"`
}

func (m *SnapshotPayload) Reset()         { *m = SnapshotPayload{} }
func (m *SnapshotPayload) String() string { return proto.CompactTextString(m) }
func (*SnapshotPayload) ProtoMessage()    {}
func (*SnapshotPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9d8140a8c06fc6, []int{1}
}

func (m *SnapshotPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotPayload.Unmarshal(m, b)
}
func (m *SnapshotPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotPayload.Marshal(b, m, deterministic)
}
func (m *SnapshotPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotPayload.Merge(m, src)
}
func (m *SnapshotPayload) XXX_Size() int {
	return xxx_messageInfo_SnapshotPayload.Size(m)
}
func (m *SnapshotPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotPayload proto.InternalMessageInfo

func (m *SnapshotPayload) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *SnapshotPayload) GetAccountBalances() []*AccountBalance {
	if m != nil {
		return m.AccountBalances
	}
	return nil
}

func (m *SnapshotPayload) GetNodeRegistrations() []*NodeRegistration {
	if m != nil {
		return m.NodeRegistrations
	}
	return nil
}

func (m *SnapshotPayload) GetAccountDatasets() []*AccountDataset {
	if m != nil {
		return m.AccountDatasets
	}
	return nil
}

func (m *SnapshotPayload) GetParticipationScores() []*ParticipationScore {
	if m != nil {
		return m.ParticipationScores
	}
	return nil
}

func (m *SnapshotPayload) GetPublishedReceipts() []*PublishedReceipt {
	if m != nil {
		return m.PublishedReceipts
	}
	return nil
}

func (m *SnapshotPayload) GetEscrowTransactions() []*Escrow {
	if m != nil {
		return m.EscrowTransactions
	}
	return nil
}

func (m *SnapshotPayload) GetPendingTransactions() []*PendingTransaction {
	if m != nil {
		return m.PendingTransactions
	}
	return nil
}

func (m *SnapshotPayload) GetPendingSignatures() []*PendingSignature {
	if m != nil {
		return m.PendingSignatures
	}
	return nil
}

func (m *SnapshotPayload) GetMultiSignatureInfos() []*MultiSignatureInfo {
	if m != nil {
		return m.MultiSignatureInfos
	}
	return nil
}

func (m *SnapshotPayload) GetSkippedBlocksmiths() []*SkippedBlocksmith {
	if m != nil {
		return m.SkippedBlocksmiths
	}
	return nil
}

func (m *SnapshotPayload) GetFeeScale() []*FeeScale {
	if m != nil {
		return m.FeeScale
	}
	return nil
}

func (m *SnapshotPayload) GetFeeVoteCommitmentVote() []*FeeVoteCommitmentVote {
	if m != nil {
		return m.FeeVoteCommitmentVote
	}
	return nil
}

func (m *SnapshotPayload) GetFeeVoteRevealVote() []*FeeVoteRevealVote {
	if m != nil {
		return m.FeeVoteRevealVote
	}
	return nil
}

func (m *SnapshotPayload) GetLiquidPayment() []*LiquidPayment {
	if m != nil {
		return m.LiquidPayment
	}
	return nil
}

func (m *SnapshotPayload) GetNodeAdmissionTimestamp() []*NodeAdmissionTimestamp {
	if m != nil {
		return m.NodeAdmissionTimestamp
	}
	return nil
}

func (m *SnapshotPayload) GetMultiSignatureParticipants() []*MultiSignatureParticipant {
	if m != nil {
		return m.MultiSignatureParticipants
	}
	return nil
}

func (m *SnapshotPayload) GetAtomicTransaction() []*Atomic {
	if m != nil {
		return m.AtomicTransaction
	}
	return nil
}

func init() {
	proto.RegisterType((*SnapshotFileInfo)(nil), "model.SnapshotFileInfo")
	proto.RegisterType((*SnapshotPayload)(nil), "model.SnapshotPayload")
}

func init() { proto.RegisterFile("model/snapshot.proto", fileDescriptor_5d9d8140a8c06fc6) }

var fileDescriptor_5d9d8140a8c06fc6 = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5d, 0x4f, 0xdb, 0x3a,
	0x18, 0x56, 0x29, 0xed, 0x01, 0x43, 0x29, 0x35, 0x1f, 0xc7, 0x54, 0x70, 0x14, 0xa1, 0x73, 0x51,
	0x71, 0x74, 0x5a, 0x89, 0xdd, 0x6d, 0xda, 0x26, 0x60, 0x54, 0x4c, 0x1b, 0x53, 0xe5, 0xb2, 0x5d,
	0xec, 0x6a, 0xae, 0x63, 0x1a, 0x8b, 0xc4, 0xce, 0x6a, 0x77, 0x1b, 0xfb, 0x63, 0xfb, 0x6d, 0xbb,
	0x9b, 0x62, 0x3b, 0xa5, 0x4e, 0x02, 0x37, 0x91, 0xf2, 0x3e, 0x1f, 0xf1, 0x63, 0xfb, 0x7d, 0x03,
	0x76, 0x13, 0x19, 0xb2, 0x78, 0xa0, 0x04, 0x49, 0x55, 0x24, 0x75, 0x3f, 0x9d, 0x49, 0x2d, 0x61,
	0xc3, 0x54, 0xbb, 0xff, 0x38, 0x30, 0xe5, 0x82, 0x9d, 0xc7, 0x92, 0xde, 0x5d, 0x13, 0xc1, 0x6f,
	0x99, 0x72, 0xb4, 0x6e, 0xd7, 0xe2, 0x84, 0x52, 0x39, 0x17, 0xfa, 0x9c, 0xc4, 0x44, 0x50, 0xe6,
	0xb0, 0x43, 0x8b, 0x09, 0x19, 0x32, 0xcc, 0xa6, 0x5c, 0xe9, 0x19, 0xd1, 0x5c, 0x8a, 0x4a, 0xe5,
	0x1b, 0xa2, 0x89, 0x62, 0xb9, 0xab, 0xfb, 0x6a, 0x4a, 0x66, 0x9a, 0x53, 0x9e, 0x1a, 0xd9, 0x98,
	0xca, 0x59, 0xc1, 0x39, 0x9d, 0x4f, 0x62, 0xae, 0x22, 0x16, 0x62, 0x46, 0x19, 0x4f, 0x73, 0x35,
	0xb4, 0x28, 0x53, 0x74, 0x26, 0xbf, 0xfb, 0x5f, 0x4b, 0xe6, 0xb1, 0xe6, 0x63, 0x3e, 0x15, 0x44,
	0xcf, 0x17, 0x6e, 0x1d, 0x8b, 0x4d, 0xb2, 0x78, 0xae, 0x74, 0xe4, 0x62, 0xdf, 0xf1, 0x34, 0x65,
	0xa1, 0x09, 0xae, 0x12, 0xae, 0x23, 0x07, 0xbb, 0x2d, 0xbb, 0x65, 0x6c, 0x4c, 0x49, 0x9c, 0xfb,
	0xec, 0x2c, 0xaa, 0x9f, 0xa4, 0xce, 0x8b, 0x07, 0xb6, 0x18, 0xf3, 0xaf, 0x73, 0x1e, 0x8e, 0xc8,
	0x7d, 0xc2, 0x44, 0x61, 0x9d, 0x44, 0xcb, 0x84, 0x53, 0x5b, 0x3b, 0xfe, 0xb5, 0x02, 0xb6, 0xc7,
	0xee, 0x24, 0x86, 0x3c, 0x66, 0x6f, 0xc5, 0xad, 0x84, 0x27, 0x7e, 0xed, 0x8a, 0xa8, 0x08, 0xd5,
	0x82, 0x5a, 0x6f, 0x13, 0x97, 0xea, 0x70, 0x1f, 0x34, 0xaf, 0x18, 0x9f, 0x46, 0x1a, 0xad, 0x04,
	0xb5, 0x5e, 0x0b, 0xbb, 0x37, 0xf8, 0x0a, 0x74, 0x47, 0x33, 0x49, 0x99, 0x52, 0x97, 0x3f, 0x52,
	0x6e, 0x4f, 0xe2, 0x86, 0x27, 0x4c, 0x69, 0x92, 0xa4, 0xa8, 0x1e, 0xd4, 0x7a, 0x75, 0xfc, 0x04,
	0x03, 0x1e, 0x82, 0xf5, 0x8b, 0x88, 0x70, 0x71, 0x73, 0x9f, 0x32, 0xb4, 0x1a, 0xd4, 0x7a, 0x0d,
	0xfc, 0x50, 0x80, 0x1f, 0xc1, 0xfe, 0xb8, 0x74, 0x45, 0x0c, 0xb5, 0x11, 0xd4, 0x7a, 0x5b, 0xa7,
	0x47, 0x7d, 0x93, 0xb5, 0x5f, 0x4d, 0xc2, 0x8f, 0x88, 0xb3, 0xe0, 0x59, 0xb0, 0x8b, 0x68, 0x2e,
	0xee, 0x54, 0x16, 0x8f, 0x29, 0xd4, 0x0c, 0xea, 0x59, 0xf0, 0x62, 0xfd, 0xf8, 0xf7, 0x3a, 0x68,
	0xe7, 0xbb, 0x31, 0x22, 0xf7, 0xb1, 0x24, 0x21, 0xfc, 0x17, 0x34, 0xed, 0xd9, 0xa1, 0x5a, 0x50,
	0xef, 0x6d, 0x9c, 0x6e, 0xba, 0x65, 0x98, 0x22, 0x76, 0x18, 0x7c, 0x0d, 0xda, 0x67, 0xde, 0xfd,
	0x55, 0x68, 0xc5, 0xd0, 0xf7, 0x1c, 0xdd, 0x47, 0x71, 0x91, 0x0d, 0x2f, 0x41, 0xe7, 0x43, 0xe1,
	0x92, 0x2b, 0x54, 0x37, 0x16, 0x7f, 0x3b, 0x8b, 0x22, 0x8e, 0xcb, 0x8a, 0xa5, 0x75, 0xb8, 0x6e,
	0x50, 0x68, 0xb5, 0x6a, 0x1d, 0x0e, 0xc5, 0x45, 0x36, 0x7c, 0x07, 0x76, 0x46, 0xa5, 0x96, 0x51,
	0xa8, 0x61, 0x4c, 0x0e, 0x9c, 0x49, 0x99, 0x81, 0xab, 0x54, 0x59, 0xa8, 0x51, 0xa1, 0xbf, 0xec,
	0xe6, 0x3f, 0x84, 0x2a, 0xe2, 0xb8, 0xac, 0x80, 0x2f, 0x01, 0xbc, 0x34, 0x8d, 0x78, 0x33, 0x23,
	0x42, 0x11, 0x6a, 0x37, 0xe7, 0x2f, 0xe3, 0xd3, 0x72, 0x3e, 0x96, 0x80, 0x2b, 0x88, 0x26, 0x12,
	0x13, 0x21, 0x17, 0x53, 0x4f, 0xbf, 0xe6, 0x47, 0x2a, 0x31, 0x70, 0x95, 0xca, 0x44, 0xb2, 0xe5,
	0xc5, 0x08, 0x50, 0x68, 0xdd, 0x8f, 0x54, 0xc0, 0x71, 0x59, 0x91, 0xad, 0xe9, 0xda, 0x9b, 0x23,
	0x59, 0x93, 0x2a, 0x04, 0xbc, 0x35, 0x95, 0x19, 0xb8, 0x4a, 0x05, 0xaf, 0x00, 0x1c, 0x17, 0xa7,
	0x8c, 0x42, 0x1b, 0xc6, 0x0b, 0xe5, 0x5d, 0x53, 0x24, 0xe0, 0x0a, 0x0d, 0xfc, 0x0f, 0xac, 0x0d,
	0xdd, 0x40, 0x42, 0x9b, 0x46, 0xdf, 0x76, 0xfa, 0xbc, 0x8c, 0x17, 0x04, 0x88, 0xc1, 0xde, 0xd0,
	0xce, 0xa9, 0x0b, 0x99, 0x24, 0x5c, 0x67, 0x63, 0x29, 0x7b, 0x43, 0x2d, 0xa3, 0x3c, 0x7c, 0x50,
	0x96, 0x39, 0xb8, 0x5a, 0x0a, 0x87, 0xa0, 0xe3, 0x00, 0xcc, 0xbe, 0x31, 0x12, 0x1b, 0xbf, 0x2d,
	0x2f, 0x49, 0x09, 0xc7, 0x65, 0x09, 0x7c, 0x0e, 0x5a, 0xef, 0x97, 0xc7, 0x25, 0x6a, 0x1b, 0x8f,
	0x5d, 0xe7, 0xe1, 0x61, 0xd8, 0xa7, 0x66, 0x83, 0x28, 0x6b, 0xac, 0xb3, 0x30, 0xe1, 0x4a, 0x79,
	0x23, 0x6e, 0xdb, 0x98, 0x1c, 0x2d, 0xf5, 0x63, 0x99, 0x84, 0x1f, 0x11, 0xc3, 0x2f, 0xa0, 0xeb,
	0x1f, 0xde, 0xa2, 0x63, 0x84, 0x56, 0xa8, 0x63, 0xac, 0x83, 0xca, 0x93, 0x5f, 0x22, 0xe2, 0x27,
	0x3c, 0xe0, 0x0b, 0xd0, 0x39, 0x33, 0x3f, 0x82, 0xa5, 0x1b, 0x8b, 0xa0, 0xd7, 0x26, 0x16, 0xc7,
	0x65, 0xde, 0xf9, 0xc9, 0xe7, 0xde, 0x94, 0xeb, 0x68, 0x3e, 0xe9, 0x53, 0x99, 0x0c, 0x7e, 0x4a,
	0x39, 0xa1, 0xf6, 0xf9, 0x7f, 0xd6, 0xcb, 0x03, 0x2a, 0x93, 0x44, 0x8a, 0x81, 0x71, 0x99, 0x34,
	0xcd, 0x8f, 0xe6, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xb1, 0xb3, 0xc3, 0xf7, 0x07,
	0x00, 0x00,
}
