// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/transaction.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Transaction represent the transaction data structure stored in the database
type Transaction struct {
	Version                 uint32 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	ID                      int64  `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	BlockID                 int64  `protobuf:"varint,3,opt,name=BlockID,proto3" json:"BlockID,omitempty"`
	Height                  uint32 `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	SenderAccountAddress    string `protobuf:"bytes,5,opt,name=SenderAccountAddress,proto3" json:"SenderAccountAddress,omitempty"`
	RecipientAccountAddress string `protobuf:"bytes,6,opt,name=RecipientAccountAddress,proto3" json:"RecipientAccountAddress,omitempty"`
	TransactionType         uint32 `protobuf:"varint,7,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	Fee                     int64  `protobuf:"varint,8,opt,name=Fee,proto3" json:"Fee,omitempty"`
	Timestamp               int64  `protobuf:"varint,9,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	TransactionHash         []byte `protobuf:"bytes,10,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	TransactionBodyLength   uint32 `protobuf:"varint,11,opt,name=TransactionBodyLength,proto3" json:"TransactionBodyLength,omitempty"`
	TransactionBodyBytes    []byte `protobuf:"bytes,12,opt,name=TransactionBodyBytes,proto3" json:"TransactionBodyBytes,omitempty"`
	TransactionIndex        uint32 `protobuf:"varint,13,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	// TransactionBody
	//
	// Types that are valid to be assigned to TransactionBody:
	//	*Transaction_EmptyTransactionBody
	//	*Transaction_SendMoneyTransactionBody
	//	*Transaction_NodeRegistrationTransactionBody
	//	*Transaction_UpdateNodeRegistrationTransactionBody
	//	*Transaction_RemoveNodeRegistrationTransactionBody
	//	*Transaction_ClaimNodeRegistrationTransactionBody
	//	*Transaction_SetupAccountDatasetTransactionBody
	//	*Transaction_RemoveAccountDatasetTransactionBody
	TransactionBody      isTransaction_TransactionBody `protobuf_oneof:"TransactionBody"`
	Signature            []byte                        `protobuf:"bytes,22,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Transaction) GetBlockID() int64 {
	if m != nil {
		return m.BlockID
	}
	return 0
}

func (m *Transaction) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Transaction) GetSenderAccountAddress() string {
	if m != nil {
		return m.SenderAccountAddress
	}
	return ""
}

func (m *Transaction) GetRecipientAccountAddress() string {
	if m != nil {
		return m.RecipientAccountAddress
	}
	return ""
}

func (m *Transaction) GetTransactionType() uint32 {
	if m != nil {
		return m.TransactionType
	}
	return 0
}

func (m *Transaction) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *Transaction) GetTransactionBodyLength() uint32 {
	if m != nil {
		return m.TransactionBodyLength
	}
	return 0
}

func (m *Transaction) GetTransactionBodyBytes() []byte {
	if m != nil {
		return m.TransactionBodyBytes
	}
	return nil
}

func (m *Transaction) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

type isTransaction_TransactionBody interface {
	isTransaction_TransactionBody()
}

type Transaction_EmptyTransactionBody struct {
	EmptyTransactionBody *EmptyTransactionBody `protobuf:"bytes,14,opt,name=emptyTransactionBody,proto3,oneof"`
}

type Transaction_SendMoneyTransactionBody struct {
	SendMoneyTransactionBody *SendMoneyTransactionBody `protobuf:"bytes,15,opt,name=sendMoneyTransactionBody,proto3,oneof"`
}

type Transaction_NodeRegistrationTransactionBody struct {
	NodeRegistrationTransactionBody *NodeRegistrationTransactionBody `protobuf:"bytes,16,opt,name=nodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_UpdateNodeRegistrationTransactionBody struct {
	UpdateNodeRegistrationTransactionBody *UpdateNodeRegistrationTransactionBody `protobuf:"bytes,17,opt,name=updateNodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_RemoveNodeRegistrationTransactionBody struct {
	RemoveNodeRegistrationTransactionBody *RemoveNodeRegistrationTransactionBody `protobuf:"bytes,18,opt,name=removeNodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_ClaimNodeRegistrationTransactionBody struct {
	ClaimNodeRegistrationTransactionBody *ClaimNodeRegistrationTransactionBody `protobuf:"bytes,19,opt,name=claimNodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_SetupAccountDatasetTransactionBody struct {
	SetupAccountDatasetTransactionBody *SetupAccountDatasetTransactionBody `protobuf:"bytes,20,opt,name=setupAccountDatasetTransactionBody,proto3,oneof"`
}

type Transaction_RemoveAccountDatasetTransactionBody struct {
	RemoveAccountDatasetTransactionBody *RemoveAccountDatasetTransactionBody `protobuf:"bytes,21,opt,name=removeAccountDatasetTransactionBody,proto3,oneof"`
}

func (*Transaction_EmptyTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_SendMoneyTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_NodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_UpdateNodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_RemoveNodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_ClaimNodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_SetupAccountDatasetTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_RemoveAccountDatasetTransactionBody) isTransaction_TransactionBody() {}

func (m *Transaction) GetTransactionBody() isTransaction_TransactionBody {
	if m != nil {
		return m.TransactionBody
	}
	return nil
}

func (m *Transaction) GetEmptyTransactionBody() *EmptyTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_EmptyTransactionBody); ok {
		return x.EmptyTransactionBody
	}
	return nil
}

func (m *Transaction) GetSendMoneyTransactionBody() *SendMoneyTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_SendMoneyTransactionBody); ok {
		return x.SendMoneyTransactionBody
	}
	return nil
}

func (m *Transaction) GetNodeRegistrationTransactionBody() *NodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_NodeRegistrationTransactionBody); ok {
		return x.NodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetUpdateNodeRegistrationTransactionBody() *UpdateNodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_UpdateNodeRegistrationTransactionBody); ok {
		return x.UpdateNodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetRemoveNodeRegistrationTransactionBody() *RemoveNodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_RemoveNodeRegistrationTransactionBody); ok {
		return x.RemoveNodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetClaimNodeRegistrationTransactionBody() *ClaimNodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_ClaimNodeRegistrationTransactionBody); ok {
		return x.ClaimNodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetSetupAccountDatasetTransactionBody() *SetupAccountDatasetTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_SetupAccountDatasetTransactionBody); ok {
		return x.SetupAccountDatasetTransactionBody
	}
	return nil
}

func (m *Transaction) GetRemoveAccountDatasetTransactionBody() *RemoveAccountDatasetTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_RemoveAccountDatasetTransactionBody); ok {
		return x.RemoveAccountDatasetTransactionBody
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Transaction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Transaction_EmptyTransactionBody)(nil),
		(*Transaction_SendMoneyTransactionBody)(nil),
		(*Transaction_NodeRegistrationTransactionBody)(nil),
		(*Transaction_UpdateNodeRegistrationTransactionBody)(nil),
		(*Transaction_RemoveNodeRegistrationTransactionBody)(nil),
		(*Transaction_ClaimNodeRegistrationTransactionBody)(nil),
		(*Transaction_SetupAccountDatasetTransactionBody)(nil),
		(*Transaction_RemoveAccountDatasetTransactionBody)(nil),
	}
}

type EmptyTransactionBody struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyTransactionBody) Reset()         { *m = EmptyTransactionBody{} }
func (m *EmptyTransactionBody) String() string { return proto.CompactTextString(m) }
func (*EmptyTransactionBody) ProtoMessage()    {}
func (*EmptyTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{1}
}

func (m *EmptyTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyTransactionBody.Unmarshal(m, b)
}
func (m *EmptyTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyTransactionBody.Marshal(b, m, deterministic)
}
func (m *EmptyTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyTransactionBody.Merge(m, src)
}
func (m *EmptyTransactionBody) XXX_Size() int {
	return xxx_messageInfo_EmptyTransactionBody.Size(m)
}
func (m *EmptyTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyTransactionBody proto.InternalMessageInfo

type SendMoneyTransactionBody struct {
	Amount               int64    `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMoneyTransactionBody) Reset()         { *m = SendMoneyTransactionBody{} }
func (m *SendMoneyTransactionBody) String() string { return proto.CompactTextString(m) }
func (*SendMoneyTransactionBody) ProtoMessage()    {}
func (*SendMoneyTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{2}
}

func (m *SendMoneyTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMoneyTransactionBody.Unmarshal(m, b)
}
func (m *SendMoneyTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMoneyTransactionBody.Marshal(b, m, deterministic)
}
func (m *SendMoneyTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMoneyTransactionBody.Merge(m, src)
}
func (m *SendMoneyTransactionBody) XXX_Size() int {
	return xxx_messageInfo_SendMoneyTransactionBody.Size(m)
}
func (m *SendMoneyTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMoneyTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_SendMoneyTransactionBody proto.InternalMessageInfo

func (m *SendMoneyTransactionBody) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type NodeRegistrationTransactionBody struct {
	NodePublicKey  []byte `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	AccountAddress string `protobuf:"bytes,2,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	NodeAddress    string `protobuf:"bytes,3,opt,name=NodeAddress,proto3" json:"NodeAddress,omitempty"`
	// Funds to be locked to register the node
	LockedBalance int64 `protobuf:"varint,4,opt,name=LockedBalance,proto3" json:"LockedBalance,omitempty"`
	// Proof of ownership (message + signature)
	Poown                *ProofOfOwnership `protobuf:"bytes,5,opt,name=Poown,proto3" json:"Poown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeRegistrationTransactionBody) Reset()         { *m = NodeRegistrationTransactionBody{} }
func (m *NodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*NodeRegistrationTransactionBody) ProtoMessage()    {}
func (*NodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{3}
}

func (m *NodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *NodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *NodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegistrationTransactionBody.Merge(m, src)
}
func (m *NodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_NodeRegistrationTransactionBody.Size(m)
}
func (m *NodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *NodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *NodeRegistrationTransactionBody) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *NodeRegistrationTransactionBody) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *NodeRegistrationTransactionBody) GetLockedBalance() int64 {
	if m != nil {
		return m.LockedBalance
	}
	return 0
}

func (m *NodeRegistrationTransactionBody) GetPoown() *ProofOfOwnership {
	if m != nil {
		return m.Poown
	}
	return nil
}

type UpdateNodeRegistrationTransactionBody struct {
	NodePublicKey []byte `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	NodeAddress   string `protobuf:"bytes,2,opt,name=NodeAddress,proto3" json:"NodeAddress,omitempty"`
	// Funds to be locked to register the node
	LockedBalance int64 `protobuf:"varint,3,opt,name=LockedBalance,proto3" json:"LockedBalance,omitempty"`
	// Proof of ownership (message + signature)
	Poown                *ProofOfOwnership `protobuf:"bytes,4,opt,name=Poown,proto3" json:"Poown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateNodeRegistrationTransactionBody) Reset()         { *m = UpdateNodeRegistrationTransactionBody{} }
func (m *UpdateNodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRegistrationTransactionBody) ProtoMessage()    {}
func (*UpdateNodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{4}
}

func (m *UpdateNodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Merge(m, src)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Size(m)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *UpdateNodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *UpdateNodeRegistrationTransactionBody) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *UpdateNodeRegistrationTransactionBody) GetLockedBalance() int64 {
	if m != nil {
		return m.LockedBalance
	}
	return 0
}

func (m *UpdateNodeRegistrationTransactionBody) GetPoown() *ProofOfOwnership {
	if m != nil {
		return m.Poown
	}
	return nil
}

type RemoveNodeRegistrationTransactionBody struct {
	NodePublicKey        []byte   `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeRegistrationTransactionBody) Reset()         { *m = RemoveNodeRegistrationTransactionBody{} }
func (m *RemoveNodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeRegistrationTransactionBody) ProtoMessage()    {}
func (*RemoveNodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{5}
}

func (m *RemoveNodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Merge(m, src)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Size(m)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *RemoveNodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

type SetupAccountDatasetTransactionBody struct {
	// Account Address that set Dataset
	SetterAccountAddress string `protobuf:"bytes,1,opt,name=SetterAccountAddress,proto3" json:"SetterAccountAddress,omitempty"`
	// Account Address that got property of Dataset
	RecipientAccountAddress string `protobuf:"bytes,2,opt,name=RecipientAccountAddress,proto3" json:"RecipientAccountAddress,omitempty"`
	// Property name
	Property string `protobuf:"bytes,3,opt,name=Property,proto3" json:"Property,omitempty"`
	// Value of property
	Value string `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	// How long Dataset will active in second
	MuchTime             uint64   `protobuf:"varint,5,opt,name=MuchTime,proto3" json:"MuchTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupAccountDatasetTransactionBody) Reset()         { *m = SetupAccountDatasetTransactionBody{} }
func (m *SetupAccountDatasetTransactionBody) String() string { return proto.CompactTextString(m) }
func (*SetupAccountDatasetTransactionBody) ProtoMessage()    {}
func (*SetupAccountDatasetTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{6}
}

func (m *SetupAccountDatasetTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupAccountDatasetTransactionBody.Unmarshal(m, b)
}
func (m *SetupAccountDatasetTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupAccountDatasetTransactionBody.Marshal(b, m, deterministic)
}
func (m *SetupAccountDatasetTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupAccountDatasetTransactionBody.Merge(m, src)
}
func (m *SetupAccountDatasetTransactionBody) XXX_Size() int {
	return xxx_messageInfo_SetupAccountDatasetTransactionBody.Size(m)
}
func (m *SetupAccountDatasetTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupAccountDatasetTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_SetupAccountDatasetTransactionBody proto.InternalMessageInfo

func (m *SetupAccountDatasetTransactionBody) GetSetterAccountAddress() string {
	if m != nil {
		return m.SetterAccountAddress
	}
	return ""
}

func (m *SetupAccountDatasetTransactionBody) GetRecipientAccountAddress() string {
	if m != nil {
		return m.RecipientAccountAddress
	}
	return ""
}

func (m *SetupAccountDatasetTransactionBody) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *SetupAccountDatasetTransactionBody) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetupAccountDatasetTransactionBody) GetMuchTime() uint64 {
	if m != nil {
		return m.MuchTime
	}
	return 0
}

type RemoveAccountDatasetTransactionBody struct {
	// Account Address that set Dataset
	SetterAccountAddress string `protobuf:"bytes,1,opt,name=SetterAccountAddress,proto3" json:"SetterAccountAddress,omitempty"`
	// Account Address that got property of Dataset
	RecipientAccountAddress string `protobuf:"bytes,2,opt,name=RecipientAccountAddress,proto3" json:"RecipientAccountAddress,omitempty"`
	// Property name
	Property string `protobuf:"bytes,3,opt,name=Property,proto3" json:"Property,omitempty"`
	// Value of property
	Value                string   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAccountDatasetTransactionBody) Reset()         { *m = RemoveAccountDatasetTransactionBody{} }
func (m *RemoveAccountDatasetTransactionBody) String() string { return proto.CompactTextString(m) }
func (*RemoveAccountDatasetTransactionBody) ProtoMessage()    {}
func (*RemoveAccountDatasetTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{7}
}

func (m *RemoveAccountDatasetTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAccountDatasetTransactionBody.Unmarshal(m, b)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAccountDatasetTransactionBody.Marshal(b, m, deterministic)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAccountDatasetTransactionBody.Merge(m, src)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_Size() int {
	return xxx_messageInfo_RemoveAccountDatasetTransactionBody.Size(m)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAccountDatasetTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAccountDatasetTransactionBody proto.InternalMessageInfo

func (m *RemoveAccountDatasetTransactionBody) GetSetterAccountAddress() string {
	if m != nil {
		return m.SetterAccountAddress
	}
	return ""
}

func (m *RemoveAccountDatasetTransactionBody) GetRecipientAccountAddress() string {
	if m != nil {
		return m.RecipientAccountAddress
	}
	return ""
}

func (m *RemoveAccountDatasetTransactionBody) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *RemoveAccountDatasetTransactionBody) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ClaimNodeRegistrationTransactionBody struct {
	NodePublicKey  []byte `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	AccountAddress string `protobuf:"bytes,2,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	// Proof of ownership (message + signature)
	Poown                *ProofOfOwnership `protobuf:"bytes,3,opt,name=Poown,proto3" json:"Poown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClaimNodeRegistrationTransactionBody) Reset()         { *m = ClaimNodeRegistrationTransactionBody{} }
func (m *ClaimNodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*ClaimNodeRegistrationTransactionBody) ProtoMessage()    {}
func (*ClaimNodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{8}
}

func (m *ClaimNodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Merge(m, src)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Size(m)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimNodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimNodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *ClaimNodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *ClaimNodeRegistrationTransactionBody) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *ClaimNodeRegistrationTransactionBody) GetPoown() *ProofOfOwnership {
	if m != nil {
		return m.Poown
	}
	return nil
}

// GetTransactionRequest return model.Transaction
type GetTransactionRequest struct {
	// Fetch Transaction by its ID
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{9}
}

func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(m, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

// GetTransactions return GetTransactionsResponse
type GetTransactionsRequest struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	AccountAddress       string   `protobuf:"bytes,3,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionsRequest) Reset()         { *m = GetTransactionsRequest{} }
func (m *GetTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsRequest) ProtoMessage()    {}
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{10}
}

func (m *GetTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsRequest.Unmarshal(m, b)
}
func (m *GetTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsRequest.Merge(m, src)
}
func (m *GetTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsRequest.Size(m)
}
func (m *GetTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsRequest proto.InternalMessageInfo

func (m *GetTransactionsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTransactionsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetTransactionsRequest) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

type GetTransactionsResponse struct {
	// Number of transactions in total
	Total uint64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	// Transaction transactions returned
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTransactionsResponse) Reset()         { *m = GetTransactionsResponse{} }
func (m *GetTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsResponse) ProtoMessage()    {}
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{11}
}

func (m *GetTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsResponse.Unmarshal(m, b)
}
func (m *GetTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsResponse.Merge(m, src)
}
func (m *GetTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsResponse.Size(m)
}
func (m *GetTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsResponse proto.InternalMessageInfo

func (m *GetTransactionsResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetTransactionsResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// PostTransactionRequest return PostTransactionResponse
type PostTransactionRequest struct {
	// Signed transaction bytes
	TransactionBytes     []byte   `protobuf:"bytes,1,opt,name=TransactionBytes,proto3" json:"TransactionBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostTransactionRequest) Reset()         { *m = PostTransactionRequest{} }
func (m *PostTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*PostTransactionRequest) ProtoMessage()    {}
func (*PostTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{12}
}

func (m *PostTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTransactionRequest.Unmarshal(m, b)
}
func (m *PostTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTransactionRequest.Marshal(b, m, deterministic)
}
func (m *PostTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTransactionRequest.Merge(m, src)
}
func (m *PostTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_PostTransactionRequest.Size(m)
}
func (m *PostTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostTransactionRequest proto.InternalMessageInfo

func (m *PostTransactionRequest) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

type PostTransactionResponse struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PostTransactionResponse) Reset()         { *m = PostTransactionResponse{} }
func (m *PostTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*PostTransactionResponse) ProtoMessage()    {}
func (*PostTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{13}
}

func (m *PostTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTransactionResponse.Unmarshal(m, b)
}
func (m *PostTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTransactionResponse.Marshal(b, m, deterministic)
}
func (m *PostTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTransactionResponse.Merge(m, src)
}
func (m *PostTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_PostTransactionResponse.Size(m)
}
func (m *PostTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostTransactionResponse proto.InternalMessageInfo

func (m *PostTransactionResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

// SendTransactionRequest request in p2pCommunication service
type SendTransactionRequest struct {
	TransactionBytes     []byte   `protobuf:"bytes,1,opt,name=TransactionBytes,proto3" json:"TransactionBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{14}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "model.Transaction")
	proto.RegisterType((*EmptyTransactionBody)(nil), "model.EmptyTransactionBody")
	proto.RegisterType((*SendMoneyTransactionBody)(nil), "model.SendMoneyTransactionBody")
	proto.RegisterType((*NodeRegistrationTransactionBody)(nil), "model.NodeRegistrationTransactionBody")
	proto.RegisterType((*UpdateNodeRegistrationTransactionBody)(nil), "model.UpdateNodeRegistrationTransactionBody")
	proto.RegisterType((*RemoveNodeRegistrationTransactionBody)(nil), "model.RemoveNodeRegistrationTransactionBody")
	proto.RegisterType((*SetupAccountDatasetTransactionBody)(nil), "model.SetupAccountDatasetTransactionBody")
	proto.RegisterType((*RemoveAccountDatasetTransactionBody)(nil), "model.RemoveAccountDatasetTransactionBody")
	proto.RegisterType((*ClaimNodeRegistrationTransactionBody)(nil), "model.ClaimNodeRegistrationTransactionBody")
	proto.RegisterType((*GetTransactionRequest)(nil), "model.GetTransactionRequest")
	proto.RegisterType((*GetTransactionsRequest)(nil), "model.GetTransactionsRequest")
	proto.RegisterType((*GetTransactionsResponse)(nil), "model.GetTransactionsResponse")
	proto.RegisterType((*PostTransactionRequest)(nil), "model.PostTransactionRequest")
	proto.RegisterType((*PostTransactionResponse)(nil), "model.PostTransactionResponse")
	proto.RegisterType((*SendTransactionRequest)(nil), "model.SendTransactionRequest")
}

func init() { proto.RegisterFile("model/transaction.proto", fileDescriptor_8333001f09b34082) }

var fileDescriptor_8333001f09b34082 = []byte{
	// 962 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x8f, 0x93, 0xa6, 0x7f, 0x26, 0xcd, 0xfd, 0x59, 0xd2, 0x64, 0x55, 0x2a, 0x1a, 0xf9, 0xda,
	0x93, 0xe9, 0x71, 0x2d, 0x2a, 0xa7, 0x13, 0xaf, 0x0d, 0x01, 0x52, 0xd1, 0xd2, 0xb0, 0x2d, 0xf7,
	0x80, 0xc4, 0x83, 0x6b, 0xcf, 0x25, 0xa6, 0xb1, 0xd7, 0xd8, 0x6b, 0x8e, 0x80, 0x84, 0x84, 0xc4,
	0x37, 0xe1, 0xb3, 0x20, 0xf1, 0x41, 0x90, 0x90, 0xf8, 0x14, 0xc8, 0x6b, 0x27, 0x8d, 0x1d, 0xb7,
	0x5e, 0x09, 0x1e, 0xee, 0xa5, 0xea, 0xfe, 0x66, 0xe6, 0x37, 0xbf, 0x59, 0xcf, 0xee, 0x6c, 0xa0,
	0xe3, 0x72, 0x1b, 0x27, 0x47, 0x22, 0x30, 0xbd, 0xd0, 0xb4, 0x84, 0xc3, 0xbd, 0x43, 0x3f, 0xe0,
	0x82, 0x93, 0xba, 0x34, 0x6c, 0xef, 0x24, 0x76, 0x3f, 0xe0, 0xfc, 0xf5, 0xc5, 0xeb, 0x8b, 0x37,
	0x1e, 0x06, 0xe1, 0xd8, 0xf1, 0x13, 0x27, 0xfd, 0xef, 0x06, 0x34, 0xae, 0x6e, 0x43, 0x09, 0x85,
	0xb5, 0x57, 0x18, 0x84, 0x0e, 0xf7, 0xa8, 0xd6, 0xd5, 0x8c, 0x26, 0x9b, 0x2d, 0x09, 0x81, 0xea,
	0x69, 0x9f, 0x56, 0xbb, 0x9a, 0x51, 0xeb, 0x55, 0x3f, 0xd4, 0x58, 0xf5, 0xb4, 0x4f, 0x76, 0x60,
	0xad, 0x37, 0xe1, 0xd6, 0xcd, 0x69, 0x9f, 0xd6, 0xe6, 0x86, 0x19, 0x44, 0xda, 0xb0, 0x3a, 0x40,
	0x67, 0x34, 0x16, 0x74, 0x45, 0x52, 0xa5, 0x2b, 0x72, 0x0c, 0xad, 0x4b, 0xf4, 0x6c, 0x0c, 0x4e,
	0x2c, 0x8b, 0x47, 0x9e, 0x38, 0xb1, 0xed, 0x00, 0xc3, 0x90, 0xd6, 0xbb, 0x9a, 0xb1, 0xc1, 0x0a,
	0x6d, 0xe4, 0x63, 0xe8, 0x30, 0xb4, 0x1c, 0xdf, 0x41, 0x4f, 0xe4, 0xc2, 0x56, 0x65, 0xd8, 0x5d,
	0x66, 0x62, 0xc0, 0xc3, 0x85, 0x02, 0xaf, 0xa6, 0x3e, 0xd2, 0x35, 0x29, 0x27, 0x0f, 0x93, 0x16,
	0xd4, 0x3e, 0x43, 0xa4, 0xeb, 0xf3, 0x4a, 0xe2, 0x25, 0xe9, 0xc2, 0xc6, 0x95, 0xe3, 0x62, 0x28,
	0x4c, 0xd7, 0xa7, 0x1b, 0x73, 0xdb, 0x2d, 0x98, 0xcb, 0x30, 0x30, 0xc3, 0x31, 0x85, 0xae, 0x66,
	0x6c, 0xb2, 0x3c, 0x4c, 0x5e, 0xc0, 0xd6, 0x02, 0xd4, 0xe3, 0xf6, 0xf4, 0x0c, 0xbd, 0x91, 0x18,
	0xd3, 0x86, 0x54, 0x54, 0x6c, 0x8c, 0xf7, 0x2b, 0x67, 0xe8, 0x4d, 0x05, 0x86, 0x74, 0x53, 0x26,
	0x29, 0xb4, 0x91, 0x03, 0x78, 0xb4, 0x80, 0x9f, 0x7a, 0x36, 0xfe, 0x48, 0x9b, 0x32, 0xc9, 0x12,
	0x4e, 0xbe, 0x82, 0x16, 0xba, 0xbe, 0x98, 0xe6, 0x88, 0xe8, 0x83, 0xae, 0x66, 0x34, 0x8e, 0xdf,
	0x3d, 0x94, 0x0d, 0x74, 0xf8, 0x69, 0x81, 0xcb, 0xa0, 0xc2, 0x0a, 0x43, 0xc9, 0xb7, 0x40, 0x43,
	0xf4, 0xec, 0x73, 0xee, 0xe1, 0x12, 0xed, 0x43, 0x49, 0xbb, 0x9b, 0xd2, 0x5e, 0xde, 0xe1, 0x36,
	0xa8, 0xb0, 0x3b, 0x29, 0x48, 0x00, 0xbb, 0x1e, 0xb7, 0x91, 0xe1, 0xc8, 0x09, 0x45, 0x60, 0xca,
	0x2f, 0x98, 0xcb, 0xf2, 0x48, 0x66, 0x79, 0x9a, 0x66, 0xf9, 0xf2, 0x7e, 0xef, 0x41, 0x85, 0x95,
	0x11, 0x92, 0xdf, 0x34, 0xd8, 0x8f, 0x7c, 0xdb, 0x14, 0x58, 0x42, 0x46, 0x1f, 0xcb, 0xd4, 0x1f,
	0xa4, 0xa9, 0xbf, 0x56, 0x89, 0x19, 0x54, 0x98, 0x1a, 0xb9, 0x94, 0x11, 0xa0, 0xcb, 0x7f, 0x28,
	0x95, 0x41, 0x32, 0x32, 0x98, 0x4a, 0x4c, 0x2c, 0x43, 0x89, 0x9c, 0xfc, 0xaa, 0xc1, 0x9e, 0x35,
	0x31, 0x1d, 0xb7, 0x4c, 0xc5, 0x3b, 0x52, 0xc5, 0xb3, 0x54, 0xc5, 0x27, 0x0a, 0x21, 0x83, 0x0a,
	0x53, 0xa2, 0x26, 0x3f, 0x83, 0x1e, 0xa2, 0x88, 0xfc, 0xf4, 0xc0, 0xf7, 0x4d, 0x61, 0x86, 0x28,
	0xf2, 0x02, 0x5a, 0x52, 0xc0, 0xfb, 0xf3, 0x76, 0x2b, 0x0b, 0x18, 0x54, 0x98, 0x02, 0x2d, 0xf9,
	0x05, 0x9e, 0x24, 0x3b, 0x75, 0x7f, 0xf6, 0x2d, 0x99, 0xfd, 0x20, 0xf3, 0x11, 0xca, 0xd2, 0xab,
	0x10, 0x93, 0x1d, 0xd8, 0xb8, 0x74, 0x46, 0x9e, 0x29, 0xa2, 0x00, 0x69, 0x5b, 0xde, 0x04, 0xb7,
	0x40, 0xef, 0x71, 0xe6, 0x4a, 0x8a, 0x03, 0xf4, 0x36, 0xb4, 0x8a, 0x8e, 0xb0, 0xfe, 0x12, 0xe8,
	0x5d, 0x67, 0x90, 0x6c, 0xc3, 0xea, 0x89, 0x1b, 0x8b, 0x90, 0xc3, 0x20, 0xb9, 0xf8, 0x52, 0x44,
	0xff, 0x47, 0x83, 0xdd, 0xb2, 0x2f, 0xb4, 0x07, 0xcd, 0xd8, 0x65, 0x18, 0x5d, 0x4f, 0x1c, 0xeb,
	0x0b, 0x9c, 0x4a, 0x9a, 0x4d, 0x96, 0x05, 0xc9, 0x53, 0x78, 0x90, 0xbb, 0xd2, 0xab, 0xf2, 0x4a,
	0xcf, 0xa1, 0xa4, 0x0b, 0x8d, 0x38, 0x70, 0xe6, 0x54, 0x93, 0x4e, 0x8b, 0x10, 0x31, 0xa0, 0x79,
	0xc6, 0xad, 0x1b, 0xb4, 0x7b, 0xe6, 0xc4, 0xf4, 0x2c, 0x94, 0x83, 0x27, 0x91, 0x9d, 0x35, 0x90,
	0xe7, 0x50, 0x1f, 0x72, 0xfe, 0xc6, 0x93, 0x43, 0xa7, 0x71, 0xdc, 0x49, 0x3f, 0xd0, 0x30, 0x37,
	0x25, 0x59, 0xe2, 0xa5, 0xff, 0xa9, 0xc1, 0xbe, 0xd2, 0x41, 0x56, 0x2c, 0x39, 0x57, 0x4a, 0x55,
	0xa1, 0x94, 0x5a, 0x69, 0x29, 0x2b, 0x4a, 0xa5, 0x9c, 0xc3, 0xbe, 0xd2, 0x5d, 0xa0, 0x56, 0x89,
	0xfe, 0x97, 0x06, 0x7a, 0xf9, 0xa1, 0x4a, 0x66, 0xbe, 0x10, 0x4b, 0x33, 0x5f, 0x9b, 0xcd, 0xfc,
	0x65, 0xdb, 0x7d, 0x33, 0xbf, 0x7a, 0xff, 0xcc, 0xdf, 0x86, 0xf5, 0x61, 0xc0, 0x7d, 0x0c, 0xc4,
	0x34, 0x6d, 0x93, 0xf9, 0x9a, 0xb4, 0xa0, 0xfe, 0xca, 0x9c, 0x44, 0x49, 0x6f, 0x6c, 0xb0, 0x64,
	0x41, 0xde, 0x83, 0xf5, 0xf3, 0xc8, 0x1a, 0xc7, 0x43, 0x5d, 0xb6, 0xc4, 0x8a, 0xdc, 0xe9, 0x39,
	0xa6, 0xff, 0xa1, 0xc1, 0x13, 0x85, 0xd3, 0xfb, 0xb6, 0xd7, 0xa9, 0xff, 0xae, 0xc1, 0x9e, 0xca,
	0x25, 0xfc, 0x3f, 0x1f, 0xdd, 0x79, 0x8f, 0xd6, 0x94, 0x7a, 0xf4, 0x19, 0x6c, 0x7d, 0x9e, 0xd9,
	0x5b, 0x86, 0xdf, 0x47, 0x18, 0x8a, 0xf4, 0x11, 0xaa, 0x2d, 0x3e, 0x42, 0xf5, 0xef, 0xa0, 0x9d,
	0x75, 0x0e, 0x67, 0xde, 0x2d, 0xa8, 0x9f, 0x39, 0xae, 0x23, 0xd2, 0xa7, 0x6c, 0xb2, 0x20, 0x04,
	0x56, 0x86, 0xe6, 0x08, 0xa5, 0xd2, 0x26, 0x93, 0xff, 0x17, 0xd4, 0x51, 0x2b, 0xaa, 0x43, 0xbf,
	0x81, 0xce, 0x52, 0xae, 0xd0, 0xe7, 0x5e, 0x88, 0x84, 0x42, 0xfd, 0x8a, 0x0b, 0x73, 0x22, 0x93,
	0x25, 0xed, 0x93, 0x00, 0xe4, 0x25, 0x6c, 0x2e, 0x46, 0xd0, 0x6a, 0xb7, 0x66, 0x34, 0x8e, 0x49,
	0xba, 0x07, 0x8b, 0x55, 0x66, 0xfc, 0xf4, 0x3e, 0xb4, 0x87, 0x3c, 0x2c, 0xda, 0x86, 0xec, 0xeb,
	0x2e, 0x79, 0x0d, 0x26, 0xdf, 0x67, 0x09, 0xd7, 0x2f, 0xa0, 0xb3, 0xc4, 0x92, 0x4a, 0x7e, 0x91,
	0x79, 0xfb, 0x4b, 0x86, 0x62, 0x5d, 0x8b, 0x6e, 0xb1, 0xac, 0x78, 0x60, 0xfc, 0x37, 0x59, 0xbd,
	0x83, 0x6f, 0x8c, 0x91, 0x23, 0xc6, 0xd1, 0xf5, 0xa1, 0xc5, 0xdd, 0xa3, 0x9f, 0x38, 0xbf, 0xb6,
	0x92, 0xbf, 0xcf, 0x2d, 0x1e, 0xe0, 0x91, 0xc5, 0x5d, 0x97, 0x7b, 0x47, 0x52, 0xca, 0xf5, 0xaa,
	0xfc, 0xad, 0xf2, 0xd1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x6f, 0x27, 0x18, 0xeb, 0x0c,
	0x00, 0x00,
}
