// ZooBC Copyright (C) 2020 Quasisoft Limited - Hong Kong
// This file is part of ZooBC <https://github.com/zoobc/zoobc-core>
//
// ZooBC is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// ZooBC is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with ZooBC.  If not, see <http://www.gnu.org/licenses/>.
//
// Additional Permission Under GNU GPL Version 3 section 7.
// As the special exception permitted under Section 7b, c and e,
// in respect with the Author’s copyright, please refer to this section:
//
// 1. You are free to convey this Program according to GNU GPL Version 3,
//     as long as you respect and comply with the Author’s copyright by
//     showing in its user interface an Appropriate Notice that the derivate
//     program and its source code are “powered by ZooBC”.
//     This is an acknowledgement for the copyright holder, ZooBC,
//     as the implementation of appreciation of the exclusive right of the
//     creator and to avoid any circumvention on the rights under trademark
//     law for use of some trade names, trademarks, or service marks.
//
// 2. Complying to the GNU GPL Version 3, you may distribute
//     the program without any permission from the Author.
//     However a prior notification to the authors will be appreciated.
//
// ZooBC is architected by Roberto Capodieci & Barton Johnston
//             contact us at roberto.capodieci[at]blockchainzoo.com
//             and barton.johnston[at]blockchainzoo.com
//
// Core developers that contributed to the current implementation of the
// software are:
//             Ahmad Ali Abdilah ahmad.abdilah[at]blockchainzoo.com
//             Allan Bintoro allan.bintoro[at]blockchainzoo.com
//             Andy Herman
//             Gede Sukra
//             Ketut Ariasa
//             Nawi Kartini nawi.kartini[at]blockchainzoo.com
//             Stefano Galassi stefano.galassi[at]blockchainzoo.com
//
// IMPORTANT: The above copyright notice and this permission notice
// shall be included in all copies or substantial portions of the Software.
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/transaction.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionType int32

const (
	// in bytes: []byte{0,0,0,0}
	TransactionType_EmptyTransaction TransactionType = 0
	// in bytes: []byte{1,0,0,0}
	TransactionType_SendMoneyTransaction TransactionType = 1
	// in bytes: []byte{2,0,0,0}
	TransactionType_NodeRegistrationTransaction TransactionType = 2
	// in bytes: []byte{2,1,0,0}
	TransactionType_UpdateNodeRegistrationTransaction TransactionType = 258
	// in bytes: []byte{2,2,0,0}
	TransactionType_RemoveNodeRegistrationTransaction TransactionType = 514
	// in bytes: []byte{2,3,0,0}
	TransactionType_ClaimNodeRegistrationTransaction TransactionType = 770
	// in bytes: []byte{3,0,0,0}
	TransactionType_SetupAccountDatasetTransaction TransactionType = 3
	// in bytes: []byte{3,1,0,0}
	TransactionType_RemoveAccountDatasetTransaction TransactionType = 259
	// in bytes: []byte{4,0,0,0}
	TransactionType_ApprovalEscrowTransaction TransactionType = 4
	// in bytes: []byte{5,0,0,0}
	TransactionType_MultiSignatureTransaction TransactionType = 5
	// in bytes: []byte{6,0,0,0}
	TransactionType_LiquidPaymentTransaction TransactionType = 6
	// in bytes: []byte{6,1,0,0}
	TransactionType_LiquidPaymentStopTransaction TransactionType = 262
	// in bytes: []byte{7,0,0,0}
	TransactionType_FeeVoteCommitmentVoteTransaction TransactionType = 7
	// in bytes: []byte{7,1,0,0}
	TransactionType_FeeVoteRevealVoteTransaction TransactionType = 263
	// in bytes: []byte{8,0,0,0}
	TransactionType_AtomicTransaction TransactionType = 8
)

var TransactionType_name = map[int32]string{
	0:   "EmptyTransaction",
	1:   "SendMoneyTransaction",
	2:   "NodeRegistrationTransaction",
	258: "UpdateNodeRegistrationTransaction",
	514: "RemoveNodeRegistrationTransaction",
	770: "ClaimNodeRegistrationTransaction",
	3:   "SetupAccountDatasetTransaction",
	259: "RemoveAccountDatasetTransaction",
	4:   "ApprovalEscrowTransaction",
	5:   "MultiSignatureTransaction",
	6:   "LiquidPaymentTransaction",
	262: "LiquidPaymentStopTransaction",
	7:   "FeeVoteCommitmentVoteTransaction",
	263: "FeeVoteRevealVoteTransaction",
	8:   "AtomicTransaction",
}

var TransactionType_value = map[string]int32{
	"EmptyTransaction":                  0,
	"SendMoneyTransaction":              1,
	"NodeRegistrationTransaction":       2,
	"UpdateNodeRegistrationTransaction": 258,
	"RemoveNodeRegistrationTransaction": 514,
	"ClaimNodeRegistrationTransaction":  770,
	"SetupAccountDatasetTransaction":    3,
	"RemoveAccountDatasetTransaction":   259,
	"ApprovalEscrowTransaction":         4,
	"MultiSignatureTransaction":         5,
	"LiquidPaymentTransaction":          6,
	"LiquidPaymentStopTransaction":      262,
	"FeeVoteCommitmentVoteTransaction":  7,
	"FeeVoteRevealVoteTransaction":      263,
	"AtomicTransaction":                 8,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{0}
}

// TransactionChildType transaction child type it will reference to transaction.child_type
type TransactionChildType int32

const (
	TransactionChildType_NoneChild           TransactionChildType = 0
	TransactionChildType_MultiSignatureChild TransactionChildType = 1
	TransactionChildType_AtomicChild         TransactionChildType = 2
)

var TransactionChildType_name = map[int32]string{
	0: "NoneChild",
	1: "MultiSignatureChild",
	2: "AtomicChild",
}

var TransactionChildType_value = map[string]int32{
	"NoneChild":           0,
	"MultiSignatureChild": 1,
	"AtomicChild":         2,
}

func (x TransactionChildType) String() string {
	return proto.EnumName(TransactionChildType_name, int32(x))
}

func (TransactionChildType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{1}
}

// Transaction represent the transaction data structure stored in the database
type Transaction struct {
	Version                 uint32               `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	ID                      int64                `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	BlockID                 int64                `protobuf:"varint,3,opt,name=BlockID,proto3" json:"BlockID,omitempty"`
	Height                  uint32               `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	SenderAccountAddress    []byte               `protobuf:"bytes,5,opt,name=SenderAccountAddress,proto3" json:"SenderAccountAddress,omitempty"`
	RecipientAccountAddress []byte               `protobuf:"bytes,6,opt,name=RecipientAccountAddress,proto3" json:"RecipientAccountAddress,omitempty"`
	TransactionType         uint32               `protobuf:"varint,7,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	Fee                     int64                `protobuf:"varint,8,opt,name=Fee,proto3" json:"Fee,omitempty"`
	Timestamp               int64                `protobuf:"varint,9,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	TransactionHash         []byte               `protobuf:"bytes,10,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	TransactionBodyLength   uint32               `protobuf:"varint,11,opt,name=TransactionBodyLength,proto3" json:"TransactionBodyLength,omitempty"`
	TransactionBodyBytes    []byte               `protobuf:"bytes,12,opt,name=TransactionBodyBytes,proto3" json:"TransactionBodyBytes,omitempty"`
	TransactionIndex        uint32               `protobuf:"varint,13,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	ChildType               TransactionChildType `protobuf:"varint,14,opt,name=ChildType,proto3,enum=model.TransactionChildType" json:"ChildType,omitempty"`
	// transactionbody
	//
	// Types that are valid to be assigned to TransactionBody:
	//	*Transaction_EmptyTransactionBody
	//	*Transaction_SendMoneyTransactionBody
	//	*Transaction_NodeRegistrationTransactionBody
	//	*Transaction_UpdateNodeRegistrationTransactionBody
	//	*Transaction_RemoveNodeRegistrationTransactionBody
	//	*Transaction_ClaimNodeRegistrationTransactionBody
	//	*Transaction_SetupAccountDatasetTransactionBody
	//	*Transaction_RemoveAccountDatasetTransactionBody
	//	*Transaction_ApprovalEscrowTransactionBody
	//	*Transaction_MultiSignatureTransactionBody
	//	*Transaction_FeeVoteCommitTransactionBody
	//	*Transaction_FeeVoteRevealTransactionBody
	//	*Transaction_LiquidPaymentTransactionBody
	//	*Transaction_LiquidPaymentStopTransactionBody
	//	*Transaction_AtomicTransactionBody
	TransactionBody      isTransaction_TransactionBody `protobuf_oneof:"TransactionBody"`
	Signature            []byte                        `protobuf:"bytes,32,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Escrow               *Escrow                       `protobuf:"bytes,33,opt,name=Escrow,proto3" json:"Escrow,omitempty"`
	Message              []byte                        `protobuf:"bytes,34,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Transaction) GetBlockID() int64 {
	if m != nil {
		return m.BlockID
	}
	return 0
}

func (m *Transaction) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Transaction) GetSenderAccountAddress() []byte {
	if m != nil {
		return m.SenderAccountAddress
	}
	return nil
}

func (m *Transaction) GetRecipientAccountAddress() []byte {
	if m != nil {
		return m.RecipientAccountAddress
	}
	return nil
}

func (m *Transaction) GetTransactionType() uint32 {
	if m != nil {
		return m.TransactionType
	}
	return 0
}

func (m *Transaction) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *Transaction) GetTransactionBodyLength() uint32 {
	if m != nil {
		return m.TransactionBodyLength
	}
	return 0
}

func (m *Transaction) GetTransactionBodyBytes() []byte {
	if m != nil {
		return m.TransactionBodyBytes
	}
	return nil
}

func (m *Transaction) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *Transaction) GetChildType() TransactionChildType {
	if m != nil {
		return m.ChildType
	}
	return TransactionChildType_NoneChild
}

type isTransaction_TransactionBody interface {
	isTransaction_TransactionBody()
}

type Transaction_EmptyTransactionBody struct {
	EmptyTransactionBody *EmptyTransactionBody `protobuf:"bytes,17,opt,name=emptyTransactionBody,proto3,oneof"`
}

type Transaction_SendMoneyTransactionBody struct {
	SendMoneyTransactionBody *SendMoneyTransactionBody `protobuf:"bytes,18,opt,name=sendMoneyTransactionBody,proto3,oneof"`
}

type Transaction_NodeRegistrationTransactionBody struct {
	NodeRegistrationTransactionBody *NodeRegistrationTransactionBody `protobuf:"bytes,19,opt,name=nodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_UpdateNodeRegistrationTransactionBody struct {
	UpdateNodeRegistrationTransactionBody *UpdateNodeRegistrationTransactionBody `protobuf:"bytes,20,opt,name=updateNodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_RemoveNodeRegistrationTransactionBody struct {
	RemoveNodeRegistrationTransactionBody *RemoveNodeRegistrationTransactionBody `protobuf:"bytes,21,opt,name=removeNodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_ClaimNodeRegistrationTransactionBody struct {
	ClaimNodeRegistrationTransactionBody *ClaimNodeRegistrationTransactionBody `protobuf:"bytes,22,opt,name=claimNodeRegistrationTransactionBody,proto3,oneof"`
}

type Transaction_SetupAccountDatasetTransactionBody struct {
	SetupAccountDatasetTransactionBody *SetupAccountDatasetTransactionBody `protobuf:"bytes,23,opt,name=setupAccountDatasetTransactionBody,proto3,oneof"`
}

type Transaction_RemoveAccountDatasetTransactionBody struct {
	RemoveAccountDatasetTransactionBody *RemoveAccountDatasetTransactionBody `protobuf:"bytes,24,opt,name=removeAccountDatasetTransactionBody,proto3,oneof"`
}

type Transaction_ApprovalEscrowTransactionBody struct {
	ApprovalEscrowTransactionBody *ApprovalEscrowTransactionBody `protobuf:"bytes,25,opt,name=approvalEscrowTransactionBody,proto3,oneof"`
}

type Transaction_MultiSignatureTransactionBody struct {
	MultiSignatureTransactionBody *MultiSignatureTransactionBody `protobuf:"bytes,26,opt,name=multiSignatureTransactionBody,proto3,oneof"`
}

type Transaction_FeeVoteCommitTransactionBody struct {
	FeeVoteCommitTransactionBody *FeeVoteCommitTransactionBody `protobuf:"bytes,27,opt,name=feeVoteCommitTransactionBody,proto3,oneof"`
}

type Transaction_FeeVoteRevealTransactionBody struct {
	FeeVoteRevealTransactionBody *FeeVoteRevealTransactionBody `protobuf:"bytes,28,opt,name=feeVoteRevealTransactionBody,proto3,oneof"`
}

type Transaction_LiquidPaymentTransactionBody struct {
	LiquidPaymentTransactionBody *LiquidPaymentTransactionBody `protobuf:"bytes,29,opt,name=liquidPaymentTransactionBody,proto3,oneof"`
}

type Transaction_LiquidPaymentStopTransactionBody struct {
	LiquidPaymentStopTransactionBody *LiquidPaymentStopTransactionBody `protobuf:"bytes,30,opt,name=liquidPaymentStopTransactionBody,proto3,oneof"`
}

type Transaction_AtomicTransactionBody struct {
	AtomicTransactionBody *AtomicTransactionBody `protobuf:"bytes,31,opt,name=atomicTransactionBody,proto3,oneof"`
}

func (*Transaction_EmptyTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_SendMoneyTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_NodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_UpdateNodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_RemoveNodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_ClaimNodeRegistrationTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_SetupAccountDatasetTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_RemoveAccountDatasetTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_ApprovalEscrowTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_MultiSignatureTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_FeeVoteCommitTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_FeeVoteRevealTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_LiquidPaymentTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_LiquidPaymentStopTransactionBody) isTransaction_TransactionBody() {}

func (*Transaction_AtomicTransactionBody) isTransaction_TransactionBody() {}

func (m *Transaction) GetTransactionBody() isTransaction_TransactionBody {
	if m != nil {
		return m.TransactionBody
	}
	return nil
}

func (m *Transaction) GetEmptyTransactionBody() *EmptyTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_EmptyTransactionBody); ok {
		return x.EmptyTransactionBody
	}
	return nil
}

func (m *Transaction) GetSendMoneyTransactionBody() *SendMoneyTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_SendMoneyTransactionBody); ok {
		return x.SendMoneyTransactionBody
	}
	return nil
}

func (m *Transaction) GetNodeRegistrationTransactionBody() *NodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_NodeRegistrationTransactionBody); ok {
		return x.NodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetUpdateNodeRegistrationTransactionBody() *UpdateNodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_UpdateNodeRegistrationTransactionBody); ok {
		return x.UpdateNodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetRemoveNodeRegistrationTransactionBody() *RemoveNodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_RemoveNodeRegistrationTransactionBody); ok {
		return x.RemoveNodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetClaimNodeRegistrationTransactionBody() *ClaimNodeRegistrationTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_ClaimNodeRegistrationTransactionBody); ok {
		return x.ClaimNodeRegistrationTransactionBody
	}
	return nil
}

func (m *Transaction) GetSetupAccountDatasetTransactionBody() *SetupAccountDatasetTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_SetupAccountDatasetTransactionBody); ok {
		return x.SetupAccountDatasetTransactionBody
	}
	return nil
}

func (m *Transaction) GetRemoveAccountDatasetTransactionBody() *RemoveAccountDatasetTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_RemoveAccountDatasetTransactionBody); ok {
		return x.RemoveAccountDatasetTransactionBody
	}
	return nil
}

func (m *Transaction) GetApprovalEscrowTransactionBody() *ApprovalEscrowTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_ApprovalEscrowTransactionBody); ok {
		return x.ApprovalEscrowTransactionBody
	}
	return nil
}

func (m *Transaction) GetMultiSignatureTransactionBody() *MultiSignatureTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_MultiSignatureTransactionBody); ok {
		return x.MultiSignatureTransactionBody
	}
	return nil
}

func (m *Transaction) GetFeeVoteCommitTransactionBody() *FeeVoteCommitTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_FeeVoteCommitTransactionBody); ok {
		return x.FeeVoteCommitTransactionBody
	}
	return nil
}

func (m *Transaction) GetFeeVoteRevealTransactionBody() *FeeVoteRevealTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_FeeVoteRevealTransactionBody); ok {
		return x.FeeVoteRevealTransactionBody
	}
	return nil
}

func (m *Transaction) GetLiquidPaymentTransactionBody() *LiquidPaymentTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_LiquidPaymentTransactionBody); ok {
		return x.LiquidPaymentTransactionBody
	}
	return nil
}

func (m *Transaction) GetLiquidPaymentStopTransactionBody() *LiquidPaymentStopTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_LiquidPaymentStopTransactionBody); ok {
		return x.LiquidPaymentStopTransactionBody
	}
	return nil
}

func (m *Transaction) GetAtomicTransactionBody() *AtomicTransactionBody {
	if x, ok := m.GetTransactionBody().(*Transaction_AtomicTransactionBody); ok {
		return x.AtomicTransactionBody
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetEscrow() *Escrow {
	if m != nil {
		return m.Escrow
	}
	return nil
}

func (m *Transaction) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Transaction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Transaction_EmptyTransactionBody)(nil),
		(*Transaction_SendMoneyTransactionBody)(nil),
		(*Transaction_NodeRegistrationTransactionBody)(nil),
		(*Transaction_UpdateNodeRegistrationTransactionBody)(nil),
		(*Transaction_RemoveNodeRegistrationTransactionBody)(nil),
		(*Transaction_ClaimNodeRegistrationTransactionBody)(nil),
		(*Transaction_SetupAccountDatasetTransactionBody)(nil),
		(*Transaction_RemoveAccountDatasetTransactionBody)(nil),
		(*Transaction_ApprovalEscrowTransactionBody)(nil),
		(*Transaction_MultiSignatureTransactionBody)(nil),
		(*Transaction_FeeVoteCommitTransactionBody)(nil),
		(*Transaction_FeeVoteRevealTransactionBody)(nil),
		(*Transaction_LiquidPaymentTransactionBody)(nil),
		(*Transaction_LiquidPaymentStopTransactionBody)(nil),
		(*Transaction_AtomicTransactionBody)(nil),
	}
}

type EmptyTransactionBody struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyTransactionBody) Reset()         { *m = EmptyTransactionBody{} }
func (m *EmptyTransactionBody) String() string { return proto.CompactTextString(m) }
func (*EmptyTransactionBody) ProtoMessage()    {}
func (*EmptyTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{1}
}

func (m *EmptyTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyTransactionBody.Unmarshal(m, b)
}
func (m *EmptyTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyTransactionBody.Marshal(b, m, deterministic)
}
func (m *EmptyTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyTransactionBody.Merge(m, src)
}
func (m *EmptyTransactionBody) XXX_Size() int {
	return xxx_messageInfo_EmptyTransactionBody.Size(m)
}
func (m *EmptyTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyTransactionBody proto.InternalMessageInfo

type SendMoneyTransactionBody struct {
	Amount               int64    `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMoneyTransactionBody) Reset()         { *m = SendMoneyTransactionBody{} }
func (m *SendMoneyTransactionBody) String() string { return proto.CompactTextString(m) }
func (*SendMoneyTransactionBody) ProtoMessage()    {}
func (*SendMoneyTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{2}
}

func (m *SendMoneyTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMoneyTransactionBody.Unmarshal(m, b)
}
func (m *SendMoneyTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMoneyTransactionBody.Marshal(b, m, deterministic)
}
func (m *SendMoneyTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMoneyTransactionBody.Merge(m, src)
}
func (m *SendMoneyTransactionBody) XXX_Size() int {
	return xxx_messageInfo_SendMoneyTransactionBody.Size(m)
}
func (m *SendMoneyTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMoneyTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_SendMoneyTransactionBody proto.InternalMessageInfo

func (m *SendMoneyTransactionBody) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type NodeRegistrationTransactionBody struct {
	NodePublicKey  []byte `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	AccountAddress []byte `protobuf:"bytes,2,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	// Funds to be locked to register the node
	LockedBalance int64 `protobuf:"varint,3,opt,name=LockedBalance,proto3" json:"LockedBalance,omitempty"`
	// Proof of ownership (message + signature)
	Poown                *ProofOfOwnership `protobuf:"bytes,4,opt,name=Poown,proto3" json:"Poown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeRegistrationTransactionBody) Reset()         { *m = NodeRegistrationTransactionBody{} }
func (m *NodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*NodeRegistrationTransactionBody) ProtoMessage()    {}
func (*NodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{3}
}

func (m *NodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *NodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *NodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegistrationTransactionBody.Merge(m, src)
}
func (m *NodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_NodeRegistrationTransactionBody.Size(m)
}
func (m *NodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *NodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *NodeRegistrationTransactionBody) GetAccountAddress() []byte {
	if m != nil {
		return m.AccountAddress
	}
	return nil
}

func (m *NodeRegistrationTransactionBody) GetLockedBalance() int64 {
	if m != nil {
		return m.LockedBalance
	}
	return 0
}

func (m *NodeRegistrationTransactionBody) GetPoown() *ProofOfOwnership {
	if m != nil {
		return m.Poown
	}
	return nil
}

type UpdateNodeRegistrationTransactionBody struct {
	NodePublicKey []byte `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	// Funds to be locked to register the node
	LockedBalance int64 `protobuf:"varint,2,opt,name=LockedBalance,proto3" json:"LockedBalance,omitempty"`
	// Proof of ownership (message + signature)
	Poown                *ProofOfOwnership `protobuf:"bytes,3,opt,name=Poown,proto3" json:"Poown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateNodeRegistrationTransactionBody) Reset()         { *m = UpdateNodeRegistrationTransactionBody{} }
func (m *UpdateNodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRegistrationTransactionBody) ProtoMessage()    {}
func (*UpdateNodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{4}
}

func (m *UpdateNodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Merge(m, src)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRegistrationTransactionBody.Size(m)
}
func (m *UpdateNodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *UpdateNodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *UpdateNodeRegistrationTransactionBody) GetLockedBalance() int64 {
	if m != nil {
		return m.LockedBalance
	}
	return 0
}

func (m *UpdateNodeRegistrationTransactionBody) GetPoown() *ProofOfOwnership {
	if m != nil {
		return m.Poown
	}
	return nil
}

type RemoveNodeRegistrationTransactionBody struct {
	NodePublicKey        []byte   `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeRegistrationTransactionBody) Reset()         { *m = RemoveNodeRegistrationTransactionBody{} }
func (m *RemoveNodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeRegistrationTransactionBody) ProtoMessage()    {}
func (*RemoveNodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{5}
}

func (m *RemoveNodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Merge(m, src)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeRegistrationTransactionBody.Size(m)
}
func (m *RemoveNodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *RemoveNodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

type ClaimNodeRegistrationTransactionBody struct {
	NodePublicKey []byte `protobuf:"bytes,1,opt,name=NodePublicKey,proto3" json:"NodePublicKey,omitempty"`
	// Proof of ownership (message + signature)
	Poown                *ProofOfOwnership `protobuf:"bytes,2,opt,name=Poown,proto3" json:"Poown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClaimNodeRegistrationTransactionBody) Reset()         { *m = ClaimNodeRegistrationTransactionBody{} }
func (m *ClaimNodeRegistrationTransactionBody) String() string { return proto.CompactTextString(m) }
func (*ClaimNodeRegistrationTransactionBody) ProtoMessage()    {}
func (*ClaimNodeRegistrationTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{6}
}

func (m *ClaimNodeRegistrationTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Unmarshal(m, b)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Marshal(b, m, deterministic)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Merge(m, src)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_Size() int {
	return xxx_messageInfo_ClaimNodeRegistrationTransactionBody.Size(m)
}
func (m *ClaimNodeRegistrationTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimNodeRegistrationTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimNodeRegistrationTransactionBody proto.InternalMessageInfo

func (m *ClaimNodeRegistrationTransactionBody) GetNodePublicKey() []byte {
	if m != nil {
		return m.NodePublicKey
	}
	return nil
}

func (m *ClaimNodeRegistrationTransactionBody) GetPoown() *ProofOfOwnership {
	if m != nil {
		return m.Poown
	}
	return nil
}

type SetupAccountDatasetTransactionBody struct {
	// Property name
	Property string `protobuf:"bytes,1,opt,name=Property,proto3" json:"Property,omitempty"`
	// Value of property
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupAccountDatasetTransactionBody) Reset()         { *m = SetupAccountDatasetTransactionBody{} }
func (m *SetupAccountDatasetTransactionBody) String() string { return proto.CompactTextString(m) }
func (*SetupAccountDatasetTransactionBody) ProtoMessage()    {}
func (*SetupAccountDatasetTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{7}
}

func (m *SetupAccountDatasetTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupAccountDatasetTransactionBody.Unmarshal(m, b)
}
func (m *SetupAccountDatasetTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupAccountDatasetTransactionBody.Marshal(b, m, deterministic)
}
func (m *SetupAccountDatasetTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupAccountDatasetTransactionBody.Merge(m, src)
}
func (m *SetupAccountDatasetTransactionBody) XXX_Size() int {
	return xxx_messageInfo_SetupAccountDatasetTransactionBody.Size(m)
}
func (m *SetupAccountDatasetTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupAccountDatasetTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_SetupAccountDatasetTransactionBody proto.InternalMessageInfo

func (m *SetupAccountDatasetTransactionBody) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *SetupAccountDatasetTransactionBody) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RemoveAccountDatasetTransactionBody struct {
	// Property name
	Property string `protobuf:"bytes,1,opt,name=Property,proto3" json:"Property,omitempty"`
	// Value of property
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAccountDatasetTransactionBody) Reset()         { *m = RemoveAccountDatasetTransactionBody{} }
func (m *RemoveAccountDatasetTransactionBody) String() string { return proto.CompactTextString(m) }
func (*RemoveAccountDatasetTransactionBody) ProtoMessage()    {}
func (*RemoveAccountDatasetTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{8}
}

func (m *RemoveAccountDatasetTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAccountDatasetTransactionBody.Unmarshal(m, b)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAccountDatasetTransactionBody.Marshal(b, m, deterministic)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAccountDatasetTransactionBody.Merge(m, src)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_Size() int {
	return xxx_messageInfo_RemoveAccountDatasetTransactionBody.Size(m)
}
func (m *RemoveAccountDatasetTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAccountDatasetTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAccountDatasetTransactionBody proto.InternalMessageInfo

func (m *RemoveAccountDatasetTransactionBody) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *RemoveAccountDatasetTransactionBody) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ApprovalEscrowTransactionBody struct {
	Approval             EscrowApproval `protobuf:"varint,1,opt,name=Approval,proto3,enum=model.EscrowApproval" json:"Approval,omitempty"`
	TransactionID        int64          `protobuf:"varint,2,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApprovalEscrowTransactionBody) Reset()         { *m = ApprovalEscrowTransactionBody{} }
func (m *ApprovalEscrowTransactionBody) String() string { return proto.CompactTextString(m) }
func (*ApprovalEscrowTransactionBody) ProtoMessage()    {}
func (*ApprovalEscrowTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{9}
}

func (m *ApprovalEscrowTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovalEscrowTransactionBody.Unmarshal(m, b)
}
func (m *ApprovalEscrowTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovalEscrowTransactionBody.Marshal(b, m, deterministic)
}
func (m *ApprovalEscrowTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovalEscrowTransactionBody.Merge(m, src)
}
func (m *ApprovalEscrowTransactionBody) XXX_Size() int {
	return xxx_messageInfo_ApprovalEscrowTransactionBody.Size(m)
}
func (m *ApprovalEscrowTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovalEscrowTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovalEscrowTransactionBody proto.InternalMessageInfo

func (m *ApprovalEscrowTransactionBody) GetApproval() EscrowApproval {
	if m != nil {
		return m.Approval
	}
	return EscrowApproval_Approve
}

func (m *ApprovalEscrowTransactionBody) GetTransactionID() int64 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

type MultiSignatureTransactionBody struct {
	// MultiSignatureInfo represent the information of the multisig-address
	MultiSignatureInfo *MultiSignatureInfo `protobuf:"bytes,1,opt,name=MultiSignatureInfo,proto3" json:"MultiSignatureInfo,omitempty"`
	// Unsigned transaction bytes that will be executed once the transaction is valid
	UnsignedTransactionBytes []byte `protobuf:"bytes,2,opt,name=UnsignedTransactionBytes,proto3" json:"UnsignedTransactionBytes,omitempty"`
	// List of participantAddress-participantSignature with its tx hash
	SignatureInfo        *SignatureInfo `protobuf:"bytes,3,opt,name=SignatureInfo,proto3" json:"SignatureInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MultiSignatureTransactionBody) Reset()         { *m = MultiSignatureTransactionBody{} }
func (m *MultiSignatureTransactionBody) String() string { return proto.CompactTextString(m) }
func (*MultiSignatureTransactionBody) ProtoMessage()    {}
func (*MultiSignatureTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{10}
}

func (m *MultiSignatureTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSignatureTransactionBody.Unmarshal(m, b)
}
func (m *MultiSignatureTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSignatureTransactionBody.Marshal(b, m, deterministic)
}
func (m *MultiSignatureTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSignatureTransactionBody.Merge(m, src)
}
func (m *MultiSignatureTransactionBody) XXX_Size() int {
	return xxx_messageInfo_MultiSignatureTransactionBody.Size(m)
}
func (m *MultiSignatureTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSignatureTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSignatureTransactionBody proto.InternalMessageInfo

func (m *MultiSignatureTransactionBody) GetMultiSignatureInfo() *MultiSignatureInfo {
	if m != nil {
		return m.MultiSignatureInfo
	}
	return nil
}

func (m *MultiSignatureTransactionBody) GetUnsignedTransactionBytes() []byte {
	if m != nil {
		return m.UnsignedTransactionBytes
	}
	return nil
}

func (m *MultiSignatureTransactionBody) GetSignatureInfo() *SignatureInfo {
	if m != nil {
		return m.SignatureInfo
	}
	return nil
}

type FeeVoteCommitTransactionBody struct {
	// VoteHash the hash of fee vote object
	VoteHash             []byte   `protobuf:"bytes,1,opt,name=VoteHash,proto3" json:"VoteHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeVoteCommitTransactionBody) Reset()         { *m = FeeVoteCommitTransactionBody{} }
func (m *FeeVoteCommitTransactionBody) String() string { return proto.CompactTextString(m) }
func (*FeeVoteCommitTransactionBody) ProtoMessage()    {}
func (*FeeVoteCommitTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{11}
}

func (m *FeeVoteCommitTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeVoteCommitTransactionBody.Unmarshal(m, b)
}
func (m *FeeVoteCommitTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeVoteCommitTransactionBody.Marshal(b, m, deterministic)
}
func (m *FeeVoteCommitTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeVoteCommitTransactionBody.Merge(m, src)
}
func (m *FeeVoteCommitTransactionBody) XXX_Size() int {
	return xxx_messageInfo_FeeVoteCommitTransactionBody.Size(m)
}
func (m *FeeVoteCommitTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeVoteCommitTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_FeeVoteCommitTransactionBody proto.InternalMessageInfo

func (m *FeeVoteCommitTransactionBody) GetVoteHash() []byte {
	if m != nil {
		return m.VoteHash
	}
	return nil
}

type FeeVoteRevealTransactionBody struct {
	FeeVoteInfo          *FeeVoteInfo `protobuf:"bytes,1,opt,name=FeeVoteInfo,proto3" json:"FeeVoteInfo,omitempty"`
	VoterSignature       []byte       `protobuf:"bytes,2,opt,name=VoterSignature,proto3" json:"VoterSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FeeVoteRevealTransactionBody) Reset()         { *m = FeeVoteRevealTransactionBody{} }
func (m *FeeVoteRevealTransactionBody) String() string { return proto.CompactTextString(m) }
func (*FeeVoteRevealTransactionBody) ProtoMessage()    {}
func (*FeeVoteRevealTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{12}
}

func (m *FeeVoteRevealTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeVoteRevealTransactionBody.Unmarshal(m, b)
}
func (m *FeeVoteRevealTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeVoteRevealTransactionBody.Marshal(b, m, deterministic)
}
func (m *FeeVoteRevealTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeVoteRevealTransactionBody.Merge(m, src)
}
func (m *FeeVoteRevealTransactionBody) XXX_Size() int {
	return xxx_messageInfo_FeeVoteRevealTransactionBody.Size(m)
}
func (m *FeeVoteRevealTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeVoteRevealTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_FeeVoteRevealTransactionBody proto.InternalMessageInfo

func (m *FeeVoteRevealTransactionBody) GetFeeVoteInfo() *FeeVoteInfo {
	if m != nil {
		return m.FeeVoteInfo
	}
	return nil
}

func (m *FeeVoteRevealTransactionBody) GetVoterSignature() []byte {
	if m != nil {
		return m.VoterSignature
	}
	return nil
}

type LiquidPaymentTransactionBody struct {
	Amount int64 `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	// CompleteMinutes indicates how many minutes is required before the liquid payment is completed
	CompleteMinutes      uint64   `protobuf:"varint,2,opt,name=CompleteMinutes,proto3" json:"CompleteMinutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiquidPaymentTransactionBody) Reset()         { *m = LiquidPaymentTransactionBody{} }
func (m *LiquidPaymentTransactionBody) String() string { return proto.CompactTextString(m) }
func (*LiquidPaymentTransactionBody) ProtoMessage()    {}
func (*LiquidPaymentTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{13}
}

func (m *LiquidPaymentTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidPaymentTransactionBody.Unmarshal(m, b)
}
func (m *LiquidPaymentTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidPaymentTransactionBody.Marshal(b, m, deterministic)
}
func (m *LiquidPaymentTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidPaymentTransactionBody.Merge(m, src)
}
func (m *LiquidPaymentTransactionBody) XXX_Size() int {
	return xxx_messageInfo_LiquidPaymentTransactionBody.Size(m)
}
func (m *LiquidPaymentTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidPaymentTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidPaymentTransactionBody proto.InternalMessageInfo

func (m *LiquidPaymentTransactionBody) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LiquidPaymentTransactionBody) GetCompleteMinutes() uint64 {
	if m != nil {
		return m.CompleteMinutes
	}
	return 0
}

type LiquidPaymentStopTransactionBody struct {
	TransactionID        int64    `protobuf:"varint,1,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiquidPaymentStopTransactionBody) Reset()         { *m = LiquidPaymentStopTransactionBody{} }
func (m *LiquidPaymentStopTransactionBody) String() string { return proto.CompactTextString(m) }
func (*LiquidPaymentStopTransactionBody) ProtoMessage()    {}
func (*LiquidPaymentStopTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{14}
}

func (m *LiquidPaymentStopTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidPaymentStopTransactionBody.Unmarshal(m, b)
}
func (m *LiquidPaymentStopTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidPaymentStopTransactionBody.Marshal(b, m, deterministic)
}
func (m *LiquidPaymentStopTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidPaymentStopTransactionBody.Merge(m, src)
}
func (m *LiquidPaymentStopTransactionBody) XXX_Size() int {
	return xxx_messageInfo_LiquidPaymentStopTransactionBody.Size(m)
}
func (m *LiquidPaymentStopTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidPaymentStopTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidPaymentStopTransactionBody proto.InternalMessageInfo

func (m *LiquidPaymentStopTransactionBody) GetTransactionID() int64 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

type AtomicTransactionBody struct {
	// UnsignedTransactionBytes is collection of unsigned transaction bytes
	UnsignedTransactionBytes [][]byte `protobuf:"bytes,1,rep,name=UnsignedTransactionBytes,proto3" json:"UnsignedTransactionBytes,omitempty"`
	// Signatures is <addressHex, Signature>
	Signatures           map[string][]byte `protobuf:"bytes,2,rep,name=Signatures,proto3" json:"Signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AtomicTransactionBody) Reset()         { *m = AtomicTransactionBody{} }
func (m *AtomicTransactionBody) String() string { return proto.CompactTextString(m) }
func (*AtomicTransactionBody) ProtoMessage()    {}
func (*AtomicTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{15}
}

func (m *AtomicTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtomicTransactionBody.Unmarshal(m, b)
}
func (m *AtomicTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtomicTransactionBody.Marshal(b, m, deterministic)
}
func (m *AtomicTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtomicTransactionBody.Merge(m, src)
}
func (m *AtomicTransactionBody) XXX_Size() int {
	return xxx_messageInfo_AtomicTransactionBody.Size(m)
}
func (m *AtomicTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_AtomicTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_AtomicTransactionBody proto.InternalMessageInfo

func (m *AtomicTransactionBody) GetUnsignedTransactionBytes() [][]byte {
	if m != nil {
		return m.UnsignedTransactionBytes
	}
	return nil
}

func (m *AtomicTransactionBody) GetSignatures() map[string][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// GetTransactionRequest return model.Transaction
type GetTransactionRequest struct {
	// Fetch Transaction by its ID
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{16}
}

func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(m, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

// GetTransactions return GetTransactionsResponse
type GetTransactionsRequest struct {
	AccountAddress       []byte      `protobuf:"bytes,1,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	Height               uint32      `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	TimestampStart       int64       `protobuf:"varint,3,opt,name=TimestampStart,proto3" json:"TimestampStart,omitempty"`
	TimestampEnd         int64       `protobuf:"varint,4,opt,name=TimestampEnd,proto3" json:"TimestampEnd,omitempty"`
	TransactionType      uint32      `protobuf:"varint,5,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,6,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTransactionsRequest) Reset()         { *m = GetTransactionsRequest{} }
func (m *GetTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsRequest) ProtoMessage()    {}
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{17}
}

func (m *GetTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsRequest.Unmarshal(m, b)
}
func (m *GetTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsRequest.Merge(m, src)
}
func (m *GetTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsRequest.Size(m)
}
func (m *GetTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsRequest proto.InternalMessageInfo

func (m *GetTransactionsRequest) GetAccountAddress() []byte {
	if m != nil {
		return m.AccountAddress
	}
	return nil
}

func (m *GetTransactionsRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetTransactionsRequest) GetTimestampStart() int64 {
	if m != nil {
		return m.TimestampStart
	}
	return 0
}

func (m *GetTransactionsRequest) GetTimestampEnd() int64 {
	if m != nil {
		return m.TimestampEnd
	}
	return 0
}

func (m *GetTransactionsRequest) GetTransactionType() uint32 {
	if m != nil {
		return m.TransactionType
	}
	return 0
}

func (m *GetTransactionsRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetTransactionsResponse struct {
	// Number of transactions in total
	Total uint64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	// Transaction transactions returned
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTransactionsResponse) Reset()         { *m = GetTransactionsResponse{} }
func (m *GetTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsResponse) ProtoMessage()    {}
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{18}
}

func (m *GetTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsResponse.Unmarshal(m, b)
}
func (m *GetTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsResponse.Merge(m, src)
}
func (m *GetTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsResponse.Size(m)
}
func (m *GetTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsResponse proto.InternalMessageInfo

func (m *GetTransactionsResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetTransactionsResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// PostTransactionRequest return PostTransactionResponse
type PostTransactionRequest struct {
	// Signed transaction bytes
	TransactionBytes     []byte   `protobuf:"bytes,1,opt,name=TransactionBytes,proto3" json:"TransactionBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostTransactionRequest) Reset()         { *m = PostTransactionRequest{} }
func (m *PostTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*PostTransactionRequest) ProtoMessage()    {}
func (*PostTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{19}
}

func (m *PostTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTransactionRequest.Unmarshal(m, b)
}
func (m *PostTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTransactionRequest.Marshal(b, m, deterministic)
}
func (m *PostTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTransactionRequest.Merge(m, src)
}
func (m *PostTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_PostTransactionRequest.Size(m)
}
func (m *PostTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostTransactionRequest proto.InternalMessageInfo

func (m *PostTransactionRequest) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

type PostTransactionResponse struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PostTransactionResponse) Reset()         { *m = PostTransactionResponse{} }
func (m *PostTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*PostTransactionResponse) ProtoMessage()    {}
func (*PostTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{20}
}

func (m *PostTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTransactionResponse.Unmarshal(m, b)
}
func (m *PostTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTransactionResponse.Marshal(b, m, deterministic)
}
func (m *PostTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTransactionResponse.Merge(m, src)
}
func (m *PostTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_PostTransactionResponse.Size(m)
}
func (m *PostTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostTransactionResponse proto.InternalMessageInfo

func (m *PostTransactionResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

// SendTransactionRequest a model request of send a transaction in p2pCommunication service
type SendTransactionRequest struct {
	TransactionBytes     []byte   `protobuf:"bytes,1,opt,name=TransactionBytes,proto3" json:"TransactionBytes,omitempty"`
	ChainType            int32    `protobuf:"varint,2,opt,name=ChainType,proto3" json:"ChainType,omitempty"`
	SenderPublicKey      []byte   `protobuf:"bytes,3,opt,name=SenderPublicKey,proto3" json:"SenderPublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{21}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

func (m *SendTransactionRequest) GetChainType() int32 {
	if m != nil {
		return m.ChainType
	}
	return 0
}

func (m *SendTransactionRequest) GetSenderPublicKey() []byte {
	if m != nil {
		return m.SenderPublicKey
	}
	return nil
}

// SendTransactionResponse a model response of send a transaction in p2pCommunication service
type SendTransactionResponse struct {
	Receipt              *Receipt `protobuf:"bytes,1,opt,name=Receipt,proto3" json:"Receipt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionResponse) Reset()         { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()    {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{22}
}

func (m *SendTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionResponse.Unmarshal(m, b)
}
func (m *SendTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SendTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionResponse.Merge(m, src)
}
func (m *SendTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SendTransactionResponse.Size(m)
}
func (m *SendTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionResponse proto.InternalMessageInfo

func (m *SendTransactionResponse) GetReceipt() *Receipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

// RequestBlockTransactionsRequest a model request of requesting transaction based on ID transactions
type RequestBlockTransactionsRequest struct {
	TransactionIDs       []int64  `protobuf:"varint,1,rep,packed,name=TransactionIDs,proto3" json:"TransactionIDs,omitempty"`
	ChainType            int32    `protobuf:"varint,2,opt,name=ChainType,proto3" json:"ChainType,omitempty"`
	BlockID              int64    `protobuf:"varint,3,opt,name=BlockID,proto3" json:"BlockID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBlockTransactionsRequest) Reset()         { *m = RequestBlockTransactionsRequest{} }
func (m *RequestBlockTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*RequestBlockTransactionsRequest) ProtoMessage()    {}
func (*RequestBlockTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{23}
}

func (m *RequestBlockTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBlockTransactionsRequest.Unmarshal(m, b)
}
func (m *RequestBlockTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBlockTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *RequestBlockTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBlockTransactionsRequest.Merge(m, src)
}
func (m *RequestBlockTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_RequestBlockTransactionsRequest.Size(m)
}
func (m *RequestBlockTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBlockTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBlockTransactionsRequest proto.InternalMessageInfo

func (m *RequestBlockTransactionsRequest) GetTransactionIDs() []int64 {
	if m != nil {
		return m.TransactionIDs
	}
	return nil
}

func (m *RequestBlockTransactionsRequest) GetChainType() int32 {
	if m != nil {
		return m.ChainType
	}
	return 0
}

func (m *RequestBlockTransactionsRequest) GetBlockID() int64 {
	if m != nil {
		return m.BlockID
	}
	return 0
}

// SendBlockTransactionsRequest a model request for sending block's transactions
type SendBlockTransactionsRequest struct {
	ChainType            int32    `protobuf:"varint,1,opt,name=ChainType,proto3" json:"ChainType,omitempty"`
	TransactionsBytes    [][]byte `protobuf:"bytes,2,rep,name=TransactionsBytes,proto3" json:"TransactionsBytes,omitempty"`
	SenderPublicKey      []byte   `protobuf:"bytes,3,opt,name=SenderPublicKey,proto3" json:"SenderPublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendBlockTransactionsRequest) Reset()         { *m = SendBlockTransactionsRequest{} }
func (m *SendBlockTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*SendBlockTransactionsRequest) ProtoMessage()    {}
func (*SendBlockTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{24}
}

func (m *SendBlockTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendBlockTransactionsRequest.Unmarshal(m, b)
}
func (m *SendBlockTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendBlockTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *SendBlockTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendBlockTransactionsRequest.Merge(m, src)
}
func (m *SendBlockTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_SendBlockTransactionsRequest.Size(m)
}
func (m *SendBlockTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendBlockTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendBlockTransactionsRequest proto.InternalMessageInfo

func (m *SendBlockTransactionsRequest) GetChainType() int32 {
	if m != nil {
		return m.ChainType
	}
	return 0
}

func (m *SendBlockTransactionsRequest) GetTransactionsBytes() [][]byte {
	if m != nil {
		return m.TransactionsBytes
	}
	return nil
}

func (m *SendBlockTransactionsRequest) GetSenderPublicKey() []byte {
	if m != nil {
		return m.SenderPublicKey
	}
	return nil
}

// SendBlockTransactionsResponse a model response of a process sending block's transactions
type SendBlockTransactionsResponse struct {
	Receipts             []*Receipt `protobuf:"bytes,1,rep,name=Receipts,proto3" json:"Receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendBlockTransactionsResponse) Reset()         { *m = SendBlockTransactionsResponse{} }
func (m *SendBlockTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*SendBlockTransactionsResponse) ProtoMessage()    {}
func (*SendBlockTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{25}
}

func (m *SendBlockTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendBlockTransactionsResponse.Unmarshal(m, b)
}
func (m *SendBlockTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendBlockTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *SendBlockTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendBlockTransactionsResponse.Merge(m, src)
}
func (m *SendBlockTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_SendBlockTransactionsResponse.Size(m)
}
func (m *SendBlockTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendBlockTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendBlockTransactionsResponse proto.InternalMessageInfo

func (m *SendBlockTransactionsResponse) GetReceipts() []*Receipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

// GetTransactionMinimumFeeRequest a model request for getting minimum fee required to post the transaction
type GetTransactionMinimumFeeRequest struct {
	TransactionBytes     []byte   `protobuf:"bytes,1,opt,name=TransactionBytes,proto3" json:"TransactionBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionMinimumFeeRequest) Reset()         { *m = GetTransactionMinimumFeeRequest{} }
func (m *GetTransactionMinimumFeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionMinimumFeeRequest) ProtoMessage()    {}
func (*GetTransactionMinimumFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{26}
}

func (m *GetTransactionMinimumFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionMinimumFeeRequest.Unmarshal(m, b)
}
func (m *GetTransactionMinimumFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionMinimumFeeRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionMinimumFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionMinimumFeeRequest.Merge(m, src)
}
func (m *GetTransactionMinimumFeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionMinimumFeeRequest.Size(m)
}
func (m *GetTransactionMinimumFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionMinimumFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionMinimumFeeRequest proto.InternalMessageInfo

func (m *GetTransactionMinimumFeeRequest) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

// GetTransactionMinimumFeeResponse a model response for GetTransactionMinimumFeeRequest, indicates the minimum fee for provided tx
type GetTransactionMinimumFeeResponse struct {
	Fee                  int64    `protobuf:"varint,1,opt,name=Fee,proto3" json:"Fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionMinimumFeeResponse) Reset()         { *m = GetTransactionMinimumFeeResponse{} }
func (m *GetTransactionMinimumFeeResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionMinimumFeeResponse) ProtoMessage()    {}
func (*GetTransactionMinimumFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8333001f09b34082, []int{27}
}

func (m *GetTransactionMinimumFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionMinimumFeeResponse.Unmarshal(m, b)
}
func (m *GetTransactionMinimumFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionMinimumFeeResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionMinimumFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionMinimumFeeResponse.Merge(m, src)
}
func (m *GetTransactionMinimumFeeResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionMinimumFeeResponse.Size(m)
}
func (m *GetTransactionMinimumFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionMinimumFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionMinimumFeeResponse proto.InternalMessageInfo

func (m *GetTransactionMinimumFeeResponse) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func init() {
	proto.RegisterEnum("model.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterEnum("model.TransactionChildType", TransactionChildType_name, TransactionChildType_value)
	proto.RegisterType((*Transaction)(nil), "model.Transaction")
	proto.RegisterType((*EmptyTransactionBody)(nil), "model.EmptyTransactionBody")
	proto.RegisterType((*SendMoneyTransactionBody)(nil), "model.SendMoneyTransactionBody")
	proto.RegisterType((*NodeRegistrationTransactionBody)(nil), "model.NodeRegistrationTransactionBody")
	proto.RegisterType((*UpdateNodeRegistrationTransactionBody)(nil), "model.UpdateNodeRegistrationTransactionBody")
	proto.RegisterType((*RemoveNodeRegistrationTransactionBody)(nil), "model.RemoveNodeRegistrationTransactionBody")
	proto.RegisterType((*ClaimNodeRegistrationTransactionBody)(nil), "model.ClaimNodeRegistrationTransactionBody")
	proto.RegisterType((*SetupAccountDatasetTransactionBody)(nil), "model.SetupAccountDatasetTransactionBody")
	proto.RegisterType((*RemoveAccountDatasetTransactionBody)(nil), "model.RemoveAccountDatasetTransactionBody")
	proto.RegisterType((*ApprovalEscrowTransactionBody)(nil), "model.ApprovalEscrowTransactionBody")
	proto.RegisterType((*MultiSignatureTransactionBody)(nil), "model.MultiSignatureTransactionBody")
	proto.RegisterType((*FeeVoteCommitTransactionBody)(nil), "model.FeeVoteCommitTransactionBody")
	proto.RegisterType((*FeeVoteRevealTransactionBody)(nil), "model.FeeVoteRevealTransactionBody")
	proto.RegisterType((*LiquidPaymentTransactionBody)(nil), "model.LiquidPaymentTransactionBody")
	proto.RegisterType((*LiquidPaymentStopTransactionBody)(nil), "model.LiquidPaymentStopTransactionBody")
	proto.RegisterType((*AtomicTransactionBody)(nil), "model.AtomicTransactionBody")
	proto.RegisterMapType((map[string][]byte)(nil), "model.AtomicTransactionBody.SignaturesEntry")
	proto.RegisterType((*GetTransactionRequest)(nil), "model.GetTransactionRequest")
	proto.RegisterType((*GetTransactionsRequest)(nil), "model.GetTransactionsRequest")
	proto.RegisterType((*GetTransactionsResponse)(nil), "model.GetTransactionsResponse")
	proto.RegisterType((*PostTransactionRequest)(nil), "model.PostTransactionRequest")
	proto.RegisterType((*PostTransactionResponse)(nil), "model.PostTransactionResponse")
	proto.RegisterType((*SendTransactionRequest)(nil), "model.SendTransactionRequest")
	proto.RegisterType((*SendTransactionResponse)(nil), "model.SendTransactionResponse")
	proto.RegisterType((*RequestBlockTransactionsRequest)(nil), "model.RequestBlockTransactionsRequest")
	proto.RegisterType((*SendBlockTransactionsRequest)(nil), "model.SendBlockTransactionsRequest")
	proto.RegisterType((*SendBlockTransactionsResponse)(nil), "model.SendBlockTransactionsResponse")
	proto.RegisterType((*GetTransactionMinimumFeeRequest)(nil), "model.GetTransactionMinimumFeeRequest")
	proto.RegisterType((*GetTransactionMinimumFeeResponse)(nil), "model.GetTransactionMinimumFeeResponse")
}

func init() { proto.RegisterFile("model/transaction.proto", fileDescriptor_8333001f09b34082) }

var fileDescriptor_8333001f09b34082 = []byte{
	// 1758 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdd, 0x6e, 0xdb, 0xca,
	0x11, 0x16, 0x25, 0xcb, 0x3f, 0x23, 0xff, 0xd0, 0x1b, 0xdb, 0x62, 0x14, 0xf9, 0x58, 0x61, 0x6c,
	0x57, 0xf5, 0xc9, 0xb1, 0x7b, 0xdc, 0x20, 0x48, 0x0d, 0xf4, 0xc2, 0x7f, 0xa9, 0x8c, 0xd8, 0xb1,
	0xbb, 0x76, 0x5c, 0xa0, 0x40, 0x2f, 0x68, 0x6a, 0x2d, 0x11, 0x16, 0xb9, 0x0c, 0x49, 0x39, 0x75,
	0x13, 0x14, 0xa8, 0xfb, 0x87, 0x02, 0xbd, 0xec, 0x33, 0xf4, 0x59, 0x7a, 0xd3, 0x77, 0x28, 0xfa,
	0x24, 0xc5, 0x2e, 0x29, 0x8a, 0x4b, 0x52, 0x14, 0x9b, 0x73, 0x63, 0x78, 0x67, 0xbe, 0x9d, 0x6f,
	0x76, 0x34, 0xbb, 0x33, 0x1c, 0xa8, 0x9a, 0xb4, 0x4d, 0x7a, 0x3b, 0x9e, 0xa3, 0x59, 0xae, 0xa6,
	0x7b, 0x06, 0xb5, 0xb6, 0x6d, 0x87, 0x7a, 0x14, 0x95, 0xb9, 0xa2, 0x56, 0xf7, 0xf5, 0xb6, 0x43,
	0xe9, 0xed, 0xf9, 0xed, 0xf9, 0x27, 0x8b, 0x38, 0x6e, 0xd7, 0xb0, 0x7d, 0x50, 0x6d, 0x25, 0xd0,
	0x6a, 0x1d, 0xc3, 0xd2, 0x86, 0x9b, 0x6b, 0x4f, 0x7c, 0xb9, 0x43, 0x74, 0x62, 0xd8, 0x5e, 0x20,
	0x0c, 0x4c, 0x59, 0xb4, 0x4d, 0x30, 0xe9, 0x18, 0xae, 0xe7, 0x44, 0xb7, 0x20, 0x5f, 0x4b, 0x5c,
	0xdd, 0xa1, 0x9f, 0x02, 0x59, 0xcd, 0x97, 0x99, 0xfd, 0x9e, 0x67, 0x5c, 0x1a, 0x1d, 0x4b, 0xf3,
	0xfa, 0x0e, 0x11, 0x29, 0x6e, 0x09, 0xb9, 0xa6, 0x5e, 0x20, 0x54, 0xff, 0x8d, 0xa0, 0x72, 0x35,
	0x3c, 0x0a, 0x52, 0x60, 0xea, 0x9a, 0x38, 0xae, 0x41, 0x2d, 0x45, 0x6a, 0x48, 0xcd, 0x39, 0x3c,
	0x58, 0x22, 0x04, 0xc5, 0x93, 0x23, 0xa5, 0xd8, 0x90, 0x9a, 0xa5, 0x83, 0xe2, 0x4f, 0x24, 0x5c,
	0x3c, 0x39, 0x42, 0x75, 0x98, 0x3a, 0xe8, 0x51, 0xfd, 0xee, 0xe4, 0x48, 0x29, 0x85, 0x8a, 0x81,
	0x08, 0xad, 0xc0, 0x64, 0x8b, 0x18, 0x9d, 0xae, 0xa7, 0x4c, 0x70, 0x53, 0xc1, 0x0a, 0xed, 0xc2,
	0xd2, 0x25, 0xb1, 0xda, 0xc4, 0xd9, 0xd7, 0x75, 0xda, 0xb7, 0xbc, 0xfd, 0x76, 0xdb, 0x21, 0xae,
	0xab, 0x94, 0x1b, 0x52, 0x73, 0x16, 0xa7, 0xea, 0xd0, 0x1b, 0xa8, 0x62, 0xa2, 0x1b, 0xb6, 0x41,
	0x2c, 0x2f, 0xb6, 0x6d, 0x92, 0x6f, 0x1b, 0xa5, 0x46, 0x4d, 0x58, 0x88, 0x1c, 0xf0, 0xea, 0xc1,
	0x26, 0xca, 0x14, 0x77, 0x27, 0x2e, 0x46, 0x4b, 0x50, 0x7a, 0x4b, 0x88, 0x32, 0x1d, 0x9e, 0x84,
	0x2d, 0x51, 0x03, 0x66, 0xae, 0x0c, 0x93, 0xb8, 0x9e, 0x66, 0xda, 0xca, 0x4c, 0xa8, 0x1b, 0x0a,
	0x63, 0x0c, 0x2d, 0xcd, 0xed, 0x2a, 0xc0, 0x7d, 0x8a, 0x8b, 0xd1, 0x2b, 0x58, 0x8e, 0x88, 0x0e,
	0x68, 0xfb, 0xe1, 0x94, 0x58, 0x1d, 0xaf, 0xab, 0x54, 0xb8, 0x47, 0xe9, 0x4a, 0x16, 0xaf, 0x98,
	0xe2, 0xe0, 0xc1, 0x23, 0xae, 0x32, 0xeb, 0xc7, 0x2b, 0x4d, 0x87, 0xb6, 0x40, 0x8e, 0xc8, 0x4f,
	0xac, 0x36, 0xf9, 0xad, 0x32, 0xc7, 0x49, 0x12, 0x72, 0xf4, 0x33, 0x98, 0x39, 0xec, 0x1a, 0xbd,
	0x36, 0x8f, 0xcd, 0x7c, 0x43, 0x6a, 0xce, 0xef, 0x3e, 0xdb, 0xe6, 0xc9, 0xb2, 0x1d, 0xc1, 0x86,
	0x10, 0x3c, 0x44, 0xa3, 0x5f, 0xc2, 0x12, 0x31, 0x6d, 0xef, 0x21, 0xe6, 0x83, 0xb2, 0xd8, 0x90,
	0x9a, 0x95, 0xd0, 0xca, 0x71, 0x0a, 0xa4, 0x55, 0xc0, 0xa9, 0x5b, 0xd1, 0x6f, 0x40, 0x71, 0x89,
	0xd5, 0x3e, 0xa3, 0x16, 0x49, 0x98, 0x45, 0xdc, 0xec, 0x5a, 0x60, 0xf6, 0x72, 0x04, 0xac, 0x55,
	0xc0, 0x23, 0x4d, 0x20, 0x07, 0xd6, 0xe2, 0xf7, 0x29, 0xce, 0xf2, 0x84, 0xb3, 0x6c, 0x06, 0x2c,
	0xef, 0xb3, 0xd1, 0xad, 0x02, 0x1e, 0x67, 0x10, 0xfd, 0x49, 0x82, 0x8d, 0xbe, 0xdd, 0xd6, 0x3c,
	0x32, 0xc6, 0x98, 0xb2, 0xc4, 0xa9, 0x5f, 0x06, 0xd4, 0x1f, 0xf2, 0xec, 0x69, 0x15, 0x70, 0x3e,
	0xe3, 0xdc, 0x0d, 0x87, 0x98, 0xf4, 0x7e, 0xac, 0x1b, 0xcb, 0x82, 0x1b, 0x38, 0xcf, 0x1e, 0xe6,
	0x46, 0x2e, 0xe3, 0xe8, 0x0f, 0x12, 0xac, 0xeb, 0x3d, 0xcd, 0x30, 0xc7, 0x79, 0xb1, 0xc2, 0xbd,
	0xf8, 0x36, 0xf0, 0xe2, 0x30, 0xc7, 0x96, 0x56, 0x01, 0xe7, 0x32, 0x8d, 0x3e, 0x83, 0xea, 0x12,
	0xaf, 0x6f, 0x07, 0x6f, 0xc5, 0x91, 0xe6, 0x69, 0x2e, 0xf1, 0xe2, 0x0e, 0x54, 0xb9, 0x03, 0x3f,
	0x0e, 0xd3, 0x6d, 0xdc, 0x86, 0x56, 0x01, 0xe7, 0x30, 0x8b, 0x7e, 0x0f, 0x2f, 0xfc, 0x48, 0x65,
	0xb3, 0x2b, 0x9c, 0x7d, 0x4b, 0xf8, 0x11, 0xc6, 0xd1, 0xe7, 0x31, 0x8c, 0x7a, 0xb0, 0xaa, 0xd9,
	0xb6, 0x43, 0xef, 0xb5, 0xde, 0x31, 0x2f, 0x1e, 0x71, 0xe6, 0xa7, 0x9c, 0x79, 0x3d, 0x60, 0xde,
	0xcf, 0xc2, 0xb6, 0x0a, 0x38, 0xdb, 0x18, 0x63, 0x13, 0xcb, 0x51, 0x9c, 0xad, 0x26, 0xb0, 0x9d,
	0x65, 0x61, 0x19, 0x5b, 0xa6, 0x31, 0x64, 0x40, 0x3d, 0x28, 0x70, 0x87, 0xd4, 0x34, 0x8d, 0x44,
	0x50, 0x9f, 0x71, 0xb2, 0x17, 0x01, 0xd9, 0xdb, 0x0c, 0x68, 0xab, 0x80, 0x33, 0x4d, 0x45, 0xa8,
	0x30, 0xb9, 0x27, 0x5a, 0x2f, 0x4e, 0x55, 0x4f, 0xa3, 0x4a, 0x85, 0x46, 0xa8, 0x52, 0xf5, 0x8c,
	0xaa, 0x67, 0x7c, 0xec, 0x1b, 0xed, 0x0b, 0xed, 0xc1, 0x24, 0x56, 0xe2, 0x54, 0xab, 0x02, 0xd5,
	0x69, 0x06, 0x94, 0x51, 0x65, 0x99, 0x42, 0x7d, 0x68, 0x08, 0xfa, 0x4b, 0x8f, 0xda, 0x71, 0xba,
	0x6f, 0x38, 0xdd, 0x8f, 0xd2, 0xe8, 0x52, 0xe0, 0xad, 0x02, 0x1e, 0x6b, 0x12, 0x5d, 0xc1, 0xb2,
	0xe6, 0x51, 0xd3, 0xd0, 0xe3, 0x5c, 0x6b, 0x9c, 0xab, 0x3e, 0xc8, 0xc5, 0x34, 0x4c, 0xab, 0x80,
	0xd3, 0x37, 0xa3, 0x3a, 0xcc, 0x84, 0x99, 0xa2, 0x34, 0x78, 0xb9, 0x1c, 0x0a, 0xd0, 0x06, 0x4c,
	0xfa, 0x29, 0xab, 0x3c, 0xe7, 0x24, 0x73, 0x83, 0x72, 0xc5, 0x85, 0x38, 0x50, 0xb2, 0x96, 0xe8,
	0x8c, 0xb8, 0xae, 0xd6, 0x21, 0x8a, 0xca, 0x4d, 0x0c, 0x96, 0x07, 0x8b, 0x42, 0xe1, 0x67, 0x8c,
	0xea, 0x0a, 0x2c, 0xa5, 0x55, 0x3b, 0xf5, 0x35, 0x28, 0xa3, 0xca, 0x15, 0xaa, 0xc1, 0xe4, 0xbe,
	0xc9, 0xee, 0x2b, 0x6f, 0xb9, 0xfc, 0xf6, 0x22, 0x90, 0xa8, 0xff, 0x92, 0x60, 0x6d, 0xdc, 0x63,
	0xb6, 0x0e, 0x73, 0x0c, 0x72, 0xd1, 0xbf, 0xe9, 0x19, 0xfa, 0x3b, 0xf2, 0xc0, 0xcd, 0xcc, 0x62,
	0x51, 0x88, 0x36, 0x61, 0x3e, 0xd6, 0x38, 0x15, 0x39, 0x6c, 0x3e, 0xd1, 0x2f, 0xcd, 0x9d, 0x52,
	0xfd, 0x8e, 0xb4, 0x0f, 0xb4, 0x9e, 0x66, 0xe9, 0x24, 0xd2, 0xd9, 0x89, 0x0a, 0xf4, 0x1d, 0x94,
	0x2f, 0x28, 0xfd, 0x64, 0xf1, 0xf6, 0xae, 0xb2, 0x5b, 0x0d, 0xc2, 0x77, 0x11, 0xeb, 0x7c, 0xb1,
	0x8f, 0x52, 0xff, 0x29, 0xc1, 0x46, 0xae, 0x8a, 0x96, 0xf3, 0x40, 0x09, 0x47, 0x8b, 0x63, 0x1d,
	0x2d, 0xe5, 0x72, 0xf4, 0x0c, 0x36, 0x72, 0x95, 0xbc, 0x7c, 0x7e, 0xaa, 0x9f, 0x61, 0x3d, 0x4f,
	0xed, 0xca, 0x79, 0xea, 0xf0, 0x2c, 0xc5, 0x5c, 0x67, 0xb9, 0x06, 0x75, 0x7c, 0xdd, 0x42, 0x35,
	0x98, 0xbe, 0x70, 0xa8, 0x4d, 0x1c, 0xcf, 0x67, 0x9d, 0xc1, 0xe1, 0x1a, 0x2d, 0x41, 0xf9, 0x5a,
	0xeb, 0xf5, 0xfd, 0xf0, 0xce, 0x60, 0x7f, 0xa1, 0xfe, 0x0a, 0x5e, 0xe4, 0xa8, 0x48, 0x5f, 0x61,
	0xf8, 0x0b, 0xac, 0x66, 0x16, 0x1c, 0xf4, 0x3d, 0x4c, 0x0f, 0x00, 0xdc, 0xe4, 0xfc, 0xee, 0xb2,
	0x70, 0x6f, 0x07, 0x4a, 0x1c, 0xc2, 0x58, 0xa6, 0x44, 0x9b, 0xde, 0xe8, 0x57, 0x8c, 0xa8, 0x50,
	0xff, 0x2b, 0xc1, 0x6a, 0x66, 0x05, 0x42, 0x27, 0x80, 0x44, 0xc0, 0x89, 0x75, 0x4b, 0xb9, 0x23,
	0x95, 0xdd, 0xa7, 0xa9, 0x35, 0x8c, 0x01, 0x70, 0xca, 0x26, 0xb4, 0x07, 0xca, 0x07, 0xcb, 0x35,
	0x3a, 0x16, 0x69, 0x47, 0x59, 0x78, 0x6f, 0xef, 0xdf, 0xcd, 0x91, 0x7a, 0xb4, 0x07, 0x73, 0xa2,
	0x07, 0x7e, 0x6a, 0x2f, 0x0d, 0x7a, 0x15, 0x81, 0x5c, 0x84, 0xaa, 0x7b, 0x50, 0xcf, 0x2a, 0x7c,
	0xec, 0x47, 0x63, 0x4a, 0xfe, 0x21, 0xe3, 0xe7, 0x60, 0xb8, 0x56, 0xbf, 0x84, 0x7b, 0xd3, 0x2b,
	0xd5, 0x2b, 0xa8, 0x04, 0xfa, 0x48, 0x5c, 0x90, 0x58, 0x03, 0xb9, 0x4f, 0x51, 0x18, 0x7b, 0x9b,
	0xd8, 0xff, 0xce, 0xf0, 0xb1, 0x0e, 0xde, 0x26, 0x51, 0xaa, 0x76, 0xa1, 0x9e, 0x55, 0xdc, 0xb2,
	0x5e, 0x52, 0xf4, 0x12, 0x16, 0x0e, 0xa9, 0x69, 0xf7, 0x88, 0x47, 0xce, 0x0c, 0xab, 0x3f, 0x08,
	0xf2, 0x04, 0x07, 0xc5, 0x55, 0xea, 0x29, 0x34, 0xc6, 0xd5, 0xb5, 0x64, 0x5a, 0x49, 0xa3, 0xd2,
	0xea, 0x3f, 0x12, 0x2c, 0xa7, 0x96, 0xae, 0xcc, 0x1c, 0x90, 0x1a, 0xa5, 0xcc, 0x1c, 0x38, 0x05,
	0x08, 0x43, 0xc3, 0x0e, 0x53, 0x8a, 0xf4, 0xec, 0xa9, 0x6c, 0xc3, 0xb4, 0x70, 0x8f, 0x2d, 0xcf,
	0x79, 0xc0, 0x91, 0xfd, 0xb5, 0x9f, 0xc3, 0x42, 0x4c, 0x8d, 0x64, 0x28, 0xdd, 0x91, 0xc1, 0xc5,
	0x65, 0xff, 0xb2, 0x3b, 0x7b, 0x1f, 0xde, 0xd9, 0x59, 0xec, 0x2f, 0xf6, 0x8a, 0x6f, 0x24, 0xf5,
	0x5b, 0x58, 0xfe, 0x85, 0x70, 0xff, 0x31, 0xf9, 0xd8, 0x27, 0xae, 0x17, 0xcc, 0x0d, 0xa4, 0xe8,
	0xdc, 0x40, 0xfd, 0x5b, 0x11, 0x56, 0x44, 0xb4, 0x3b, 0x80, 0x27, 0xcb, 0x94, 0x94, 0x5a, 0xa6,
	0x86, 0xc3, 0x85, 0xa2, 0x30, 0x5c, 0xd8, 0x82, 0xf9, 0xf0, 0xcb, 0xfc, 0xd2, 0xd3, 0x1c, 0x2f,
	0x52, 0xbf, 0x62, 0x1a, 0xb4, 0x09, 0xb3, 0xa1, 0xe4, 0xd8, 0x6a, 0xf3, 0x3a, 0xe6, 0x23, 0x05,
	0x79, 0xda, 0x08, 0xa1, 0x9c, 0x3e, 0x42, 0xf8, 0x1e, 0xe0, 0x22, 0x1c, 0xed, 0xf0, 0xc9, 0x44,
	0x65, 0x77, 0x71, 0xf0, 0x44, 0x87, 0x0a, 0x1c, 0x01, 0xa9, 0x77, 0x50, 0x4d, 0x84, 0xc2, 0xb5,
	0xa9, 0xe5, 0x12, 0xa4, 0x40, 0xf9, 0x8a, 0x7a, 0xc1, 0x3b, 0xe7, 0x27, 0xaa, 0x2f, 0x40, 0xaf,
	0x61, 0x36, 0xba, 0x23, 0xf8, 0xf1, 0x51, 0xf2, 0xab, 0x1d, 0x0b, 0x38, 0xf5, 0x08, 0x56, 0x2e,
	0xa8, 0x9b, 0xf6, 0x33, 0x89, 0x03, 0x83, 0x41, 0x02, 0xb2, 0xc8, 0x27, 0xe4, 0xea, 0x39, 0x54,
	0x13, 0x56, 0x02, 0x97, 0x5f, 0x09, 0xe3, 0xa4, 0xd8, 0xfd, 0x8f, 0x6e, 0x88, 0xc2, 0xd4, 0xbf,
	0x4b, 0xb0, 0xc2, 0xda, 0xa3, 0x1f, 0xe6, 0x17, 0x6b, 0xf7, 0x0e, 0xbb, 0x9a, 0xe1, 0xff, 0x42,
	0x2c, 0x2d, 0xca, 0x78, 0x28, 0x60, 0xbf, 0xa2, 0x3f, 0x5a, 0x1a, 0x56, 0xd8, 0x92, 0x3f, 0xa6,
	0x89, 0x89, 0xd5, 0x43, 0xa8, 0x26, 0xbc, 0x09, 0xce, 0xd7, 0x84, 0x29, 0xec, 0xcf, 0xe8, 0x82,
	0xb3, 0xcd, 0x87, 0xdf, 0x67, 0x5c, 0x8a, 0x07, 0x6a, 0xf5, 0xcf, 0x12, 0xac, 0x05, 0x87, 0xe0,
	0x03, 0xb1, 0x11, 0xc9, 0x2e, 0x3c, 0x14, 0xfe, 0x9d, 0x2f, 0xe1, 0x98, 0x74, 0xcc, 0xc1, 0x32,
	0xa7, 0x70, 0xea, 0x3f, 0x24, 0xa8, 0xb3, 0xd3, 0x8c, 0x74, 0x42, 0x30, 0x2e, 0xc5, 0x8d, 0xbf,
	0x84, 0xc5, 0xe8, 0xa6, 0x41, 0x75, 0x62, 0x2f, 0x53, 0x52, 0xf1, 0x7f, 0xc4, 0xf8, 0x1d, 0xac,
	0x8e, 0xf0, 0x2a, 0x88, 0xf4, 0x16, 0x4c, 0x07, 0xa1, 0xf4, 0xa3, 0x92, 0x0c, 0x75, 0xa8, 0x57,
	0xcf, 0x60, 0x4d, 0xbc, 0x43, 0x67, 0x86, 0x65, 0x98, 0x7d, 0xf3, 0x2d, 0x21, 0x5f, 0x93, 0xdf,
	0x6f, 0xa0, 0x31, 0xda, 0x5c, 0xe0, 0x5e, 0x30, 0x2c, 0x94, 0x84, 0x61, 0xe1, 0xd6, 0xe3, 0x04,
	0xa4, 0x8c, 0x15, 0xe5, 0xf8, 0x27, 0x81, 0x5c, 0x40, 0x8a, 0x3f, 0x04, 0x8d, 0x7f, 0x10, 0xc8,
	0x12, 0x5a, 0x83, 0x67, 0x19, 0xad, 0xa2, 0x5c, 0x44, 0x9b, 0xf0, 0x7c, 0x6c, 0x1f, 0x2d, 0x3f,
	0x72, 0xdc, 0xd8, 0x3e, 0x56, 0x7e, 0x9c, 0x40, 0x1b, 0xd0, 0x18, 0xd7, 0xa0, 0xca, 0x8f, 0x93,
	0x48, 0x85, 0x6f, 0xb2, 0x5b, 0x49, 0xb9, 0x84, 0xd6, 0x59, 0xce, 0x67, 0xb6, 0x85, 0xf2, 0x1f,
	0x8b, 0x68, 0x15, 0x9e, 0x8e, 0xec, 0xf1, 0xe4, 0x09, 0xa6, 0x1e, 0xd9, 0x83, 0xc9, 0x65, 0x54,
	0x07, 0x65, 0x54, 0x13, 0x20, 0x4f, 0xa2, 0xe7, 0xb1, 0x16, 0x21, 0x56, 0xb8, 0xe5, 0xbf, 0x14,
	0xd1, 0x3a, 0x34, 0x84, 0xfe, 0x87, 0xc1, 0xd8, 0x2a, 0x0a, 0x9b, 0x62, 0x86, 0x84, 0x4e, 0x27,
	0x8e, 0xf8, 0x6b, 0x11, 0x2d, 0xc3, 0x62, 0xa2, 0xce, 0xca, 0xd3, 0x5b, 0xe7, 0xc2, 0xbc, 0x76,
	0x38, 0x2c, 0x9d, 0x83, 0x99, 0xf7, 0xd4, 0x22, 0x5c, 0x20, 0x17, 0x50, 0x15, 0x9e, 0x88, 0xc7,
	0xf4, 0x15, 0x12, 0x5a, 0x80, 0x8a, 0x6f, 0xd6, 0x17, 0x14, 0x0f, 0xb6, 0x7e, 0xdd, 0xec, 0x18,
	0x5e, 0xb7, 0x7f, 0xb3, 0xad, 0x53, 0x73, 0xe7, 0x77, 0x94, 0xde, 0xe8, 0xfe, 0xdf, 0xef, 0x74,
	0xea, 0x90, 0x1d, 0x9d, 0x9a, 0x26, 0xb5, 0x76, 0xf8, 0xe5, 0xb8, 0x99, 0xe4, 0x73, 0xfd, 0x9f,
	0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x86, 0x32, 0x40, 0xa7, 0x18, 0x00, 0x00,
}
