dbPath = "/data/zoobc-core/"
dbName = "zoobc.db"
badgerDbPath="/data/zoobc-core/"
badgerDbName="zoobc_kv"
configPath = "/data/zoobc-core/"
nodeKeyFile = "node_keys.json"

# Peer
peerPort=8001
myAddress="127.0.0.1"
wellknownPeers=["192.168.21.254:8001"]

apiRPCPort=7000
# comment out or set to 0 to disable http proxy, only enable in dev mode
apiHTTPPort=3031
apiReqTimeoutSec=2

ownerAccountAddress = ""

smithing=false
proofOfOwnershipReqTimeoutSec = 2
# Log Levels
logLevels=["warn", "fatal", "error", "panic"]
